#!/usr/bin/env python3
"""Generates values/strings.xml and values-kn/strings.xml from tools/strings_source.py.
Fails if the two languages do not have exactly the same keys and format placeholders."""
import os, re, sys
from xml.sax.saxutils import escape

sys.path.insert(0, os.path.dirname(__file__))
from strings_source import EN, KN  # noqa: E402

ROOT = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "res")
PH = re.compile(r"%\d\$[sd]")

def android_escape(s):
    s = escape(s)
    return s.replace("\\", "\\\\").replace("'", "\\'").replace('"', '\\"').replace("\n", "\\n")

def write(folder, table):
    os.makedirs(os.path.join(ROOT, folder), exist_ok=True)
    lines = ['<?xml version="1.0" encoding="utf-8"?>', "<!-- Generated by tools/gen_strings.py. Edit tools/strings_source.py instead. -->", "<resources>"]
    for k in EN:
        extra = ' translatable="false"' if folder == "values" and k in ("app_name_display",) else ""
        lines.append(f'    <string name="{k}"{extra}>{android_escape(table[k])}</string>')
    lines.append("</resources>\n")
    with open(os.path.join(ROOT, folder, "strings.xml"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

problems = []
if set(EN) != set(KN):
    problems.append(f"missing in kn: {sorted(set(EN)-set(KN))}; extra in kn: {sorted(set(KN)-set(EN))}")
for k in EN:
    if k in KN and sorted(PH.findall(EN[k])) != sorted(PH.findall(KN[k])):
        problems.append(f"placeholder mismatch in {k}")
if problems:
    print("\n".join(problems)); sys.exit(1)
write("values", EN)
KN_OUT = {k: v for k, v in KN.items() if k != "app_name_display"}
os.makedirs(os.path.join(ROOT, "values-kn"), exist_ok=True)
lines = ['<?xml version="1.0" encoding="utf-8"?>', "<!-- Generated by tools/gen_strings.py. Edit tools/strings_source.py instead. -->", "<resources>"]
for k in EN:
    if k in KN_OUT:
        lines.append(f'    <string name="{k}">{android_escape(KN_OUT[k])}</string>')
lines.append("</resources>\n")
open(os.path.join(ROOT, "values-kn", "strings.xml"), "w", encoding="utf-8").write("\n".join(lines))
print(f"wrote {len(EN)} strings (en + kn)")
