# Source of truth for UI text in English (en) and Kannada (kn).
# Run `python3 tools/gen_strings.py` to regenerate app/src/main/res/values*/strings.xml.
EN = {
"app_name": "Kairos Era",
"app_name_display": "KAIROS ERA",
"tagline": "RIGHT TIME. A BETTER YOU.",
"nav_home": "Home", "nav_today": "Today", "nav_track": "Track", "nav_read": "Read", "nav_more": "More",
"greeting_morning": "Good morning", "greeting_afternoon": "Good afternoon", "greeting_evening": "Good evening", "greeting_night": "Good night",
"home_subtitle": "Let's make today count.",
"home_customize": "Customize Home", "home_customize_summary": "Choose which cards appear on Home and in what order.",
"home_today_progress": "Today's progress", "home_tasks": "Tasks", "home_tasks_done": "%1$d / %2$d completed",
"home_progress_a11y": "Today's progress: %1$d of %2$d tasks completed",
"home_nothing_planned": "Nothing planned yet.", "home_all_done": "Everything planned is done.", "home_remaining": "%1$d left today",
"home_next_up": "Next up", "home_next_empty": "Your day is open. Add one useful thing.", "home_next_clear": "Nothing left for now. Well done.",
"home_daily_motivation": "Daily motivation", "home_trackers": "Trackers",
"home_open_today": "Open today's plan",
"quote_action": "Today: %1$s", "quote_favorite": "Save quote to favorites", "quote_unfavorite": "Remove quote from favorites",
"all_day": "All day", "all_day_short": "Any time",
"quick_add_title": "What do you want to add?", "quick_add_soon_note": "Journal arrives in the next update.",
"quick_add_task": "Task", "quick_add_tracker": "Tracker", "quick_add_book": "Book", "quick_add_journal": "Journal", "quick_add_study": "Study",
"yesterday": "Yesterday", "today": "Today", "tomorrow": "Tomorrow",
"mode_day": "Day", "mode_week": "Week", "mode_month": "Month",
"previous": "Previous", "next": "Next", "pick_date": "Pick a date",
"day_empty_title": "A clear day", "day_empty_body": "Nothing is planned for this day. Tap + to add a task.",
"week_day_free": "Free", "month_legend": "A filled green dot means everything planned was done. An orange dot means tasks are planned; it gets stronger as more are done.",
"month_cell_a11y": "Day %1$d, %2$d of %3$d done",
"subtasks_count": "%1$d/%2$d steps", "skipped": "Moved", "example_badge": "Example", "repeats": "Repeats", "has_reminder": "Has a reminder",
"edit": "Edit", "move_to_trash": "Move to Trash", "task_moved_to_trash": "Moved to Trash", "undo": "Undo",
"priority_none": "None", "priority_low": "Low", "priority_medium": "Medium", "priority_high": "High",
"new_task": "New task", "edit_task": "Edit task", "save": "Save", "close": "Close", "cancel": "Cancel", "ok": "OK", "back": "Back", "clear": "Clear",
"retry": "Try again", "optional": "Optional",
"field_title": "Title", "field_description": "Description", "field_notes": "Notes", "field_tags": "Tags", "field_tags_hint": "Separate with commas",
"section_when": "When", "section_repeat": "Repeat", "section_reminders": "Reminders", "section_priority": "Priority", "section_category": "Category", "section_subtasks": "Steps",
"starts_at": "Starts %1$s", "ends_at": "Ends %1$s", "add_end_time": "Add end time", "remove_end_time": "Remove end time",
"repeat_none": "Once", "repeat_daily": "Daily", "repeat_weekdays": "Weekdays", "repeat_weekly": "Weekly", "repeat_monthly": "Monthly", "repeat_yearly": "Yearly",
"repeat_every": "Every %1$d", "repeat_until": "Until %1$s", "repeat_forever": "No end date",
"add_reminder": "Add reminder", "remove_reminder": "Remove reminder", "reminder_at_start": "At start time", "reminder_before": "%1$d min before",
"reminder_custom_time": "At a specific time…", "reminder_at": "At %1$s", "reminder_persistent": "Keep until I act",
"add_subtask": "Add a step", "remove_subtask": "Remove step",
"example_note": "This is an example task. You can edit it or remove all examples in Settings.",
"error_title_empty": "Give the task a title.", "error_title_long": "Keep the title under %1$d characters.",
"error_end_before_start": "The end time is before the start time.", "error_reminder_needs_time": "\"Before start\" reminders need a start time.",
"error_too_many_reminders": "Up to %1$d reminders per task.",
"error_title": "Something went wrong", "error_body": "Your data is safe. Please try again.", "error_save_body": "The task could not be saved. Nothing was lost; please try again.",
"error_action_failed": "That didn't work. Please try again.",
"task_missing": "This task no longer exists", "task_missing_body": "It may have been deleted or moved to Trash.",
"trash_confirm_body": "The task moves to Trash. You can restore it from More > Trash.",
"reschedule_title": "Reschedule", "reschedule_recurring_note": "Only this occurrence moves. The repeating plan stays as it is.",
"action_done": "Done", "action_snooze": "Snooze", "action_reschedule": "Reschedule",
"reminder_label": "Task", "reminder_all_day": "Today", "reminder_public_title": "Kairos Era reminder",
"channel_group_reminders": "Task reminders", "channel_default": "Reminders (default sound)", "channel_general": "General",
"channel_reminders_description": "Reminders for tasks you scheduled.",
"sound_default": "Default", "sound_kairos_bell": "Kairos Bell", "sound_soft_chime": "Soft Chime", "sound_focus": "Focus", "sound_silent": "Silent",
"settings": "Settings", "settings_summary": "Language, appearance, notifications, sounds", "calendar": "Calendar", "calendar_summary": "Month view of your plan",
"trash": "Trash", "trash_summary": "Restore deleted tasks, trackers and books", "privacy": "Privacy", "privacy_summary": "Your data stays on this device",
"about": "About", "about_summary": "Kairos Era and what it stands for", "coming_next": "Coming next", "soon": "In a coming update",
"journal": "Journal", "statistics": "Statistics", "backup": "Backup", "diagnostics": "Diagnostics",
"settings_general": "General", "settings_language": "Language", "language_system": "Phone language", "language_english": "English", "language_kannada": "ಕನ್ನಡ",
"settings_appearance": "Appearance", "theme_system": "System", "theme_light": "Light", "theme_dark": "Dark",
"dynamic_color": "Wallpaper colors", "dynamic_color_summary": "Use colors from your wallpaper instead of the Kairos palette.",
"settings_notifications": "Notifications", "notif_permission": "Notifications", "status_allowed": "Allowed", "status_off": "Off", "allow": "Allow",
"notif_permission_off_body": "Reminders can't appear until notifications are allowed. Everything else works normally.",
"exact_alarms": "On-time reminders", "exact_alarms_off_body": "Without this, Android may deliver reminders a few minutes late to save battery.",
"open_settings": "Open settings", "battery_title": "Battery optimization",
"battery_body": "Some phones stop apps in the background. If reminders arrive late, allow Kairos Era to run without restrictions.",
"test_notification": "Send a test notification", "test_notification_summary": "Check sound and appearance.",
"test_notification_title": "Kairos Era", "test_notification_text": "Notifications are working.",
"settings_sounds": "Sounds", "default_sound": "Default sound for new reminders",
"sound_channel_note": "Android lets you change each sound's volume, vibration and importance in system settings. Your choices there are respected.",
"open_sound_settings": "Open notification settings",
"default_persistent": "Keep reminders until I act", "default_persistent_summary": "New reminders stay in the notification shade until you tap Done, Snooze or Reschedule.",
"snooze_length": "Snooze length", "minutes_short": "%1$d min",
"settings_data": "Data", "add_examples": "Add example content", "add_examples_summary": "A few sample tasks so you can see how things look.",
"remove_examples": "Remove examples", "remove_examples_summary": "Moves all example tasks to Trash.", "remove_examples_confirm": "Move all example tasks to Trash? You can restore them later.",
"settings_footer": "Kairos Era works fully offline. It has no account, no cloud sync, no analytics and no ads.",
"move_up": "Move up", "move_down": "Move down",
"trash_empty_title": "Trash is empty", "trash_empty_body": "Deleted tasks, trackers and books wait here until you restore them or delete them forever.",
"trash_explainer": "Items stay in Trash until you choose. Nothing is removed automatically.",
"restore": "Restore", "delete_forever": "Delete forever", "delete_forever_title": "Delete forever?",
"delete_forever_body": "\"%1$s\" will be permanently deleted. This can't be undone.", "deleted_on": "Deleted %1$s",
"about_philosophy": "Plan your day. Learn something. Move your body. Read something meaningful. Reflect. Repeat.",
"about_meaning": "Kairos is the Greek idea of the right, opportune moment. The emblem is a path moving toward a rising sun: a new day, steady progress, and growth.",
"about_version": "Version %1$s",
"onboarding_welcome": "Your time is yours.", "onboarding_private": "Private: only you can see your plans.", "onboarding_local": "Local: everything is stored on this phone.",
"onboarding_no_account": "No account, no sign-in.", "onboarding_no_cloud": "No cloud sync, no tracking, no ads.",
"onboarding_begin": "Begin", "onboarding_about_you": "A little about you", "onboarding_name_label": "Name or nickname",
"onboarding_focus": "What do you want to focus on?", "focus_learning": "Learning", "focus_health": "Health", "focus_reading": "Reading", "focus_work": "Work",
"focus_personal": "Personal", "focus_custom": "Something else",
"onboarding_first_task": "One thing to do today", "onboarding_first_task_hint": "Optional. You can add more later.",
"onboarding_examples": "Show example tasks (you can remove them anytime)",
"onboarding_reminders_title": "Reminders", "onboarding_reminders_body": "Kairos Era can remind you when a task is due. Notifications are the only permission it asks for, and you can change this anytime.",
"onboarding_allow_reminders": "Allow reminders", "onboarding_not_now": "Not now",
"sample_java": "Java: Collections", "sample_java_1": "List and ArrayList", "sample_java_2": "HashMap internals", "sample_java_3": "Solve 3 problems",
"sample_walk": "Morning walk", "sample_project": "Project work", "sample_workout": "Workout", "sample_read": "Read 20 pages", "sample_reflection": "Daily reflection",
# Phase 2: trackers, study, reading
"add": "Add", "yes": "Yes", "no": "No", "see_all": "See all", "color_option": "Colour %1$d",
"new_tracker": "New tracker", "edit_tracker": "Edit tracker",
"track_empty_title": "Track what matters to you", "track_empty_body": "Study, workouts, sleep, water, habits, projects or anything else. Pick a template or build your own.",
"track_today_summary": "Today: %1$d of %2$d done",
"tracker_card_a11y": "%1$s, %2$d%% today, streak %3$d",
"tracker_rest_day": "Not planned for today", "tracker_done_today": "Done", "tracker_percent_today": "%1$d%% today",
"template_pick_title": "Start a tracker", "template_pick_body": "Templates are only a starting point. You can rename, add or switch off any field.",
"template_study": "Study", "template_study_summary": "Study time, practice and a topic plan with daily targets",
"template_fitness": "Fitness", "template_fitness_summary": "Workout, steps, sleep, water, energy and mood",
"template_reading": "Reading goal", "template_reading_summary": "Pages and minutes read each day",
"template_habit": "Habit", "template_habit_summary": "One simple yes or no each day",
"template_project": "Project", "template_project_summary": "Time spent, progress and the next step",
"template_finance": "Money", "template_finance_summary": "Track spending and no-spend days",
"template_learning": "Learning a skill", "template_learning_summary": "Practice time and what you learned",
"template_health": "Health", "template_health_summary": "Water, sleep, medicine and energy",
"template_personal": "Personal growth", "template_personal_summary": "Meditation, screen-free time and gratitude",
"template_custom": "Custom", "template_custom_summary": "Start from a blank tracker",
"tf_study_time": "Study time", "tf_practice": "Practice problems", "tf_revision": "Revision done", "tf_notes": "Notes",
"tf_workout": "Workout done", "tf_steps": "Steps", "tf_workout_minutes": "Workout time", "tf_sleep": "Sleep", "tf_water": "Water",
"tf_walk": "Walk", "tf_stretching": "Stretching", "tf_energy": "Energy", "tf_mood": "Mood", "tf_weight": "Weight",
"tf_pages": "Pages read", "tf_reading_minutes": "Reading time", "tf_done": "Done",
"tf_worked_on_it": "Worked on it", "tf_time_spent": "Time spent", "tf_progress": "Progress", "tf_next_step": "Next step",
"tf_tracked_spending": "Wrote down spending", "tf_no_spend": "No-spend day",
"tf_practice_time": "Practice time", "tf_learned_count": "New things learned",
"tf_medicine": "Medicine taken", "tf_meditation": "Meditation", "tf_screen_free": "Screen-free hour", "tf_gratitude": "Grateful for",
"unit_steps": "steps", "unit_hours": "h", "unit_litres": "L", "unit_kg": "kg", "unit_pages": "pages", "unit_minutes": "min",
"tracker_missing": "This tracker no longer exists", "tracker_missing_body": "It may have been moved to Trash.",
"tracker_trash_body": "The tracker and its history move to Trash. You can restore them from More > Trash.",
"tracker_why_line": "Why: %1$s", "tracker_gain_line": "What I gain: %1$s",
"tracker_log": "Log", "tracker_no_fields": "This tracker has no active fields. Edit it to add one.",
"field_target_line": "Target %1$s %2$s",
"tracker_stats": "Progress", "stat_current_streak": "Current streak", "stat_best_streak": "Best streak",
"stat_completion_30": "Done in the last 30 days", "stat_active_days": "Days with any progress",
"tracker_missed_yesterday": "Yesterday was missed. That's fine: every day is a fresh start.",
"tracker_history": "Last 5 weeks", "history_cell_a11y": "%1$s, %2$d%%",
"tracker_name": "Name", "error_tracker_name": "Give the tracker a name.",
"tracker_icon": "Icon", "tracker_color": "Colour",
"tracker_why": "Why this matters", "tracker_why_hint": "e.g. I want to switch to a backend role",
"tracker_gain": "What I will gain", "tracker_gain_hint": "e.g. Confidence in interviews",
"tracker_frequency": "How often", "freq_daily": "Every day", "freq_selected_days": "Some days", "freq_per_week": "Times a week", "freq_per_month": "Times a month",
"freq_times_week": "%1$d times a week", "freq_times_month": "%1$d times a month",
"tracker_fields": "What to track", "tracker_fields_note": "The first field is the main goal: completing it completes the day. Removed fields keep their history.",
"error_tracker_fields": "Switch on at least one field.", "error_checklist_empty": "A checklist needs at least one item.",
"add_field": "Add field", "edit_field": "Edit field", "field_label": "Label", "field_type": "Type",
"field_target": "Daily target", "field_target_hint": "Optional. Leave empty if any amount counts.", "field_unit": "Unit",
"checklist_options": "Items, one per line", "checklist_items": "%1$d items", "field_off": "Off",
"remove_field": "Remove field", "remove_field_note": "Past values are kept; the field is only hidden.",
"type_checkbox": "Yes / no", "type_number": "Number", "type_decimal": "Decimal", "type_duration": "Minutes", "type_pages": "Pages",
"type_percentage": "Percent", "type_rating": "Rating 1-5", "type_text": "Text", "type_checklist": "Checklist",
"study_plan_for_day": "Study plan", "study_plan_note": "Ticking a target records practice on its topic. You decide when a topic is done.",
"add_study_target": "Add target", "remove_target": "Remove target", "study_target_hint": "What will you study?", "study_target_topic": "Topic: %1$s",
"study_topics": "Topics", "study_topics_done": "%1$d of %2$d done", "study_topics_empty": "Break your subject into topics, e.g. Java Core > Collections.",
"add_topic": "Add topic", "edit_topic": "Edit topic", "delete_topic": "Delete topic",
"delete_topic_body": "The topic is deleted. Its sub-topics move up one level and targets keep their text.",
"topic_status": "Status", "topic_not_started": "Not started", "topic_learning": "Learning", "topic_reviewing": "Reviewing", "topic_done": "Done",
"topic_confidence": "Confidence", "topic_resources": "Resources", "topic_questions": "Questions to answer",
"topic_parent": "Inside: %1$s", "topic_no_parent": "None", "topic_practice_count": "%1$d practice",
"add_book": "Add book", "edit_book": "Edit book",
"read_empty_title": "Read, understand, remember, apply", "read_empty_body": "Add a book to track pages and capture why you started, what you learned and what you applied.",
"reading_this_week": "This week", "pages_today": "Pages today", "pages_week": "Pages this week", "minutes_week": "Minutes this week",
"reading_days_line": "Read on %1$d days this week · %2$d books finished this year",
"shelf_reading": "Reading now", "shelf_paused": "Paused", "shelf_want": "Want to read", "shelf_finished": "Finished",
"status_want": "Want to read", "status_reading": "Reading", "status_paused": "Paused", "status_finished": "Finished",
"book_page_of": "Page %1$d of %2$d", "book_page_of_percent": "Page %1$d of %2$d (%3$d%%)", "book_page_only": "Page %1$d",
"book_pages_per_day": "%1$d pages a day to finish on time",
"book_progress": "Progress", "book_target_line": "Target: %1$s", "book_finished_on": "Finished %1$s",
"log_reading": "Log reading", "pages_read": "Pages read", "minutes_read": "Minutes (optional)",
"book_insights": "What this book gives you", "book_insights_note": "Saved automatically as you type.",
"insight_why": "Why I started", "insight_expected": "What I expected", "insight_learned": "What I learned",
"insight_key_ideas": "Key ideas", "insight_applied": "What I applied", "insight_changed": "What changed in me",
"insight_skills": "Skills I improved", "insight_takeaway": "Final takeaway", "insight_recommend": "Would I read it again?",
"book_notes": "Notes and highlights", "book_notes_empty": "Capture a highlight, a note or a lesson while you read.",
"add_note": "Add", "delete_note": "Delete note", "note_kind_note": "Note", "note_kind_highlight": "Highlight", "note_kind_lesson": "Lesson",
"note_text": "Text", "note_page": "Page (optional)", "page_short": "p. %1$d",
"book_sessions": "Reading sessions", "book_sessions_empty": "No sessions yet.", "session_line": "%1$d pages · %2$d min",
"delete_session": "Delete session", "delete_session_body": "Delete this session? Its pages are taken off your bookmark.",
"book_missing": "This book no longer exists", "book_missing_body": "It may have been moved to Trash.",
"book_trash_body": "The book, its notes and sessions move to Trash. You can restore them from More > Trash.",
"book_title": "Title", "book_author": "Author", "book_total_pages": "Total pages", "book_current_page": "Current page",
"book_status": "Status", "book_target_date": "Finish by", "book_no_target": "No target date",
"error_book_title": "Give the book a title.", "error_page_beyond": "The current page is past the last page.",
"home_trackers_line": "Trackers: %1$d of %2$d done", "home_reading_line": "Reading: %1$d pages today · %2$s",
"home_trackers_empty": "No trackers yet. Tap to create one for study, fitness or a habit.",
"home_trackers_rest": "Nothing is planned for today. Enjoy the rest.",
"trash_kind_task": "Task", "trash_kind_tracker": "Tracker", "trash_kind_book": "Book",
"delete_forever_body_history": "\"%1$s\" and all its history will be permanently deleted. This can't be undone.",
"sample_fitness_why": "More energy for everything else", "sample_study_name": "Java backend",
"sample_study_why": "To become confident in backend interviews",
"sample_topic_core": "Java Core", "sample_topic_collections": "Collections", "sample_topic_oop": "OOP basics",
"sample_topic_streams": "Streams and lambdas", "sample_topic_spring": "Spring Boot",
"sample_target_1": "Read about HashMap internals", "sample_target_2": "Solve 2 collection problems",
"sample_book_title": "Atomic Habits", "sample_book_author": "James Clear", "sample_book_why": "To build habits that last",
}

KN = {
"app_name": "ಕೈರೋಸ್ ಎರಾ",
"app_name_display": "KAIROS ERA",
"tagline": "ಸರಿಯಾದ ಸಮಯ. ಉತ್ತಮ ನೀವು.",
"nav_home": "ಮುಖಪುಟ", "nav_today": "ಇಂದು", "nav_track": "ಟ್ರ್ಯಾಕ್", "nav_read": "ಓದು", "nav_more": "ಇನ್ನಷ್ಟು",
"greeting_morning": "ಶುಭೋದಯ", "greeting_afternoon": "ಶುಭ ಮಧ್ಯಾಹ್ನ", "greeting_evening": "ಶುಭ ಸಂಜೆ", "greeting_night": "ಶುಭ ರಾತ್ರಿ",
"home_subtitle": "ಇಂದಿನ ದಿನವನ್ನು ಅರ್ಥಪೂರ್ಣವಾಗಿಸೋಣ.",
"home_customize": "ಮುಖಪುಟ ಹೊಂದಿಸಿ", "home_customize_summary": "ಮುಖಪುಟದಲ್ಲಿ ಯಾವ ಕಾರ್ಡ್‌ಗಳು ಯಾವ ಕ್ರಮದಲ್ಲಿ ಕಾಣಬೇಕು ಎಂದು ಆಯ್ಕೆಮಾಡಿ.",
"home_today_progress": "ಇಂದಿನ ಪ್ರಗತಿ", "home_tasks": "ಕಾರ್ಯಗಳು", "home_tasks_done": "%1$d / %2$d ಪೂರ್ಣಗೊಂಡಿವೆ",
"home_progress_a11y": "ಇಂದಿನ ಪ್ರಗತಿ: %2$d ಕಾರ್ಯಗಳಲ್ಲಿ %1$d ಪೂರ್ಣಗೊಂಡಿವೆ",
"home_nothing_planned": "ಇನ್ನೂ ಏನೂ ಯೋಜಿಸಿಲ್ಲ.", "home_all_done": "ಯೋಜಿಸಿದ್ದೆಲ್ಲವೂ ಪೂರ್ಣಗೊಂಡಿದೆ.", "home_remaining": "ಇಂದು ಇನ್ನೂ %1$d ಬಾಕಿ",
"home_next_up": "ಮುಂದಿನದು", "home_next_empty": "ನಿಮ್ಮ ದಿನ ಖಾಲಿಯಿದೆ. ಒಂದು ಉಪಯುಕ್ತ ಕೆಲಸ ಸೇರಿಸಿ.", "home_next_clear": "ಸದ್ಯಕ್ಕೆ ಏನೂ ಬಾಕಿ ಇಲ್ಲ. ಚೆನ್ನಾಗಿದೆ.",
"home_daily_motivation": "ದಿನದ ಪ್ರೇರಣೆ", "home_trackers": "ಟ್ರ್ಯಾಕರ್‌ಗಳು",
"home_open_today": "ಇಂದಿನ ಯೋಜನೆ ತೆರೆಯಿರಿ",
"quote_action": "ಇಂದು: %1$s", "quote_favorite": "ಉಲ್ಲೇಖವನ್ನು ಮೆಚ್ಚಿನವುಗಳಿಗೆ ಸೇರಿಸಿ", "quote_unfavorite": "ಉಲ್ಲೇಖವನ್ನು ಮೆಚ್ಚಿನವುಗಳಿಂದ ತೆಗೆಯಿರಿ",
"all_day": "ಇಡೀ ದಿನ", "all_day_short": "ಯಾವಾಗ ಬೇಕಾದರೂ",
"quick_add_title": "ಏನನ್ನು ಸೇರಿಸಲು ಬಯಸುವಿರಿ?", "quick_add_soon_note": "ದಿನಚರಿ ಮುಂದಿನ ಅಪ್‌ಡೇಟ್‌ನಲ್ಲಿ ಬರಲಿದೆ.",
"quick_add_task": "ಕಾರ್ಯ", "quick_add_tracker": "ಟ್ರ್ಯಾಕರ್", "quick_add_book": "ಪುಸ್ತಕ", "quick_add_journal": "ದಿನಚರಿ", "quick_add_study": "ಅಧ್ಯಯನ",
"yesterday": "ನಿನ್ನೆ", "today": "ಇಂದು", "tomorrow": "ನಾಳೆ",
"mode_day": "ದಿನ", "mode_week": "ವಾರ", "mode_month": "ತಿಂಗಳು",
"previous": "ಹಿಂದಿನದು", "next": "ಮುಂದೆ", "pick_date": "ದಿನಾಂಕ ಆರಿಸಿ",
"day_empty_title": "ಖಾಲಿ ದಿನ", "day_empty_body": "ಈ ದಿನಕ್ಕೆ ಏನೂ ಯೋಜಿಸಿಲ್ಲ. ಕಾರ್ಯ ಸೇರಿಸಲು + ಒತ್ತಿ.",
"week_day_free": "ಖಾಲಿ", "month_legend": "ತುಂಬಿದ ಹಸಿರು ಚುಕ್ಕೆ ಎಂದರೆ ಯೋಜಿಸಿದ್ದೆಲ್ಲವೂ ಮುಗಿದಿದೆ. ಕಿತ್ತಳೆ ಚುಕ್ಕೆ ಎಂದರೆ ಕಾರ್ಯಗಳಿವೆ; ಹೆಚ್ಚು ಮುಗಿದಂತೆ ಅದು ಗಾಢವಾಗುತ್ತದೆ.",
"month_cell_a11y": "ದಿನ %1$d, %3$d ರಲ್ಲಿ %2$d ಮುಗಿದಿವೆ",
"subtasks_count": "%1$d/%2$d ಹಂತಗಳು", "skipped": "ಸ್ಥಳಾಂತರಿಸಲಾಗಿದೆ", "example_badge": "ಉದಾಹರಣೆ", "repeats": "ಪುನರಾವರ್ತನೆ", "has_reminder": "ಜ್ಞಾಪನೆ ಇದೆ",
"edit": "ತಿದ್ದಿ", "move_to_trash": "ಕಸದ ಬುಟ್ಟಿಗೆ ಸರಿಸಿ", "task_moved_to_trash": "ಕಸದ ಬುಟ್ಟಿಗೆ ಸರಿಸಲಾಗಿದೆ", "undo": "ರದ್ದುಮಾಡಿ",
"priority_none": "ಯಾವುದೂ ಇಲ್ಲ", "priority_low": "ಕಡಿಮೆ", "priority_medium": "ಮಧ್ಯಮ", "priority_high": "ಹೆಚ್ಚು",
"new_task": "ಹೊಸ ಕಾರ್ಯ", "edit_task": "ಕಾರ್ಯ ತಿದ್ದಿ", "save": "ಉಳಿಸಿ", "close": "ಮುಚ್ಚಿ", "cancel": "ರದ್ದು", "ok": "ಸರಿ", "back": "ಹಿಂದೆ", "clear": "ತೆರವುಗೊಳಿಸಿ",
"retry": "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ", "optional": "ಐಚ್ಛಿಕ",
"field_title": "ಶೀರ್ಷಿಕೆ", "field_description": "ವಿವರಣೆ", "field_notes": "ಟಿಪ್ಪಣಿಗಳು", "field_tags": "ಟ್ಯಾಗ್‌ಗಳು", "field_tags_hint": "ಅಲ್ಪವಿರಾಮದಿಂದ ಬೇರ್ಪಡಿಸಿ",
"section_when": "ಯಾವಾಗ", "section_repeat": "ಪುನರಾವರ್ತನೆ", "section_reminders": "ಜ್ಞಾಪನೆಗಳು", "section_priority": "ಆದ್ಯತೆ", "section_category": "ವರ್ಗ", "section_subtasks": "ಹಂತಗಳು",
"starts_at": "ಆರಂಭ %1$s", "ends_at": "ಮುಕ್ತಾಯ %1$s", "add_end_time": "ಮುಕ್ತಾಯ ಸಮಯ ಸೇರಿಸಿ", "remove_end_time": "ಮುಕ್ತಾಯ ಸಮಯ ತೆಗೆಯಿರಿ",
"repeat_none": "ಒಮ್ಮೆ", "repeat_daily": "ಪ್ರತಿದಿನ", "repeat_weekdays": "ವಾರದ ದಿನಗಳು", "repeat_weekly": "ಪ್ರತಿವಾರ", "repeat_monthly": "ಪ್ರತಿ ತಿಂಗಳು", "repeat_yearly": "ಪ್ರತಿ ವರ್ಷ",
"repeat_every": "ಪ್ರತಿ %1$d", "repeat_until": "%1$s ರವರೆಗೆ", "repeat_forever": "ಕೊನೆಯ ದಿನಾಂಕವಿಲ್ಲ",
"add_reminder": "ಜ್ಞಾಪನೆ ಸೇರಿಸಿ", "remove_reminder": "ಜ್ಞಾಪನೆ ತೆಗೆಯಿರಿ", "reminder_at_start": "ಆರಂಭದ ಸಮಯದಲ್ಲಿ", "reminder_before": "%1$d ನಿಮಿಷ ಮೊದಲು",
"reminder_custom_time": "ನಿರ್ದಿಷ್ಟ ಸಮಯಕ್ಕೆ…", "reminder_at": "%1$s ಕ್ಕೆ", "reminder_persistent": "ನಾನು ಕ್ರಮ ಕೈಗೊಳ್ಳುವವರೆಗೆ ಇರಲಿ",
"add_subtask": "ಹಂತ ಸೇರಿಸಿ", "remove_subtask": "ಹಂತ ತೆಗೆಯಿರಿ",
"example_note": "ಇದು ಉದಾಹರಣೆ ಕಾರ್ಯ. ಇದನ್ನು ತಿದ್ದಬಹುದು ಅಥವಾ ಸೆಟ್ಟಿಂಗ್ಸ್‌ನಲ್ಲಿ ಎಲ್ಲಾ ಉದಾಹರಣೆಗಳನ್ನು ತೆಗೆಯಬಹುದು.",
"error_title_empty": "ಕಾರ್ಯಕ್ಕೆ ಶೀರ್ಷಿಕೆ ನೀಡಿ.", "error_title_long": "ಶೀರ್ಷಿಕೆ %1$d ಅಕ್ಷರಗಳಿಗಿಂತ ಕಡಿಮೆ ಇರಲಿ.",
"error_end_before_start": "ಮುಕ್ತಾಯ ಸಮಯ ಆರಂಭಕ್ಕಿಂತ ಮೊದಲಿದೆ.", "error_reminder_needs_time": "\"ಆರಂಭಕ್ಕೆ ಮೊದಲು\" ಜ್ಞಾಪನೆಗಳಿಗೆ ಆರಂಭ ಸಮಯ ಬೇಕು.",
"error_too_many_reminders": "ಒಂದು ಕಾರ್ಯಕ್ಕೆ ಗರಿಷ್ಠ %1$d ಜ್ಞಾಪನೆಗಳು.",
"error_title": "ಏನೋ ತಪ್ಪಾಗಿದೆ", "error_body": "ನಿಮ್ಮ ಮಾಹಿತಿ ಸುರಕ್ಷಿತವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.", "error_save_body": "ಕಾರ್ಯವನ್ನು ಉಳಿಸಲಾಗಲಿಲ್ಲ. ಏನೂ ಕಳೆದುಹೋಗಿಲ್ಲ; ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
"error_action_failed": "ಅದು ಆಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
"task_missing": "ಈ ಕಾರ್ಯ ಈಗ ಇಲ್ಲ", "task_missing_body": "ಇದನ್ನು ಅಳಿಸಿರಬಹುದು ಅಥವಾ ಕಸದ ಬುಟ್ಟಿಗೆ ಸರಿಸಿರಬಹುದು.",
"trash_confirm_body": "ಕಾರ್ಯ ಕಸದ ಬುಟ್ಟಿಗೆ ಹೋಗುತ್ತದೆ. ಇನ್ನಷ್ಟು > ಕಸದ ಬುಟ್ಟಿ ಇಂದ ಮರಳಿ ಪಡೆಯಬಹುದು.",
"reschedule_title": "ಮರುನಿಗದಿ", "reschedule_recurring_note": "ಈ ಒಂದು ಬಾರಿ ಮಾತ್ರ ಸರಿಯುತ್ತದೆ. ಪುನರಾವರ್ತಿತ ಯೋಜನೆ ಹಾಗೆಯೇ ಇರುತ್ತದೆ.",
"action_done": "ಮುಗಿದಿದೆ", "action_snooze": "ಮುಂದೂಡಿ", "action_reschedule": "ಮರುನಿಗದಿ",
"reminder_label": "ಕಾರ್ಯ", "reminder_all_day": "ಇಂದು", "reminder_public_title": "ಕೈರೋಸ್ ಎರಾ ಜ್ಞಾಪನೆ",
"channel_group_reminders": "ಕಾರ್ಯ ಜ್ಞಾಪನೆಗಳು", "channel_default": "ಜ್ಞಾಪನೆಗಳು (ಡೀಫಾಲ್ಟ್ ಧ್ವನಿ)", "channel_general": "ಸಾಮಾನ್ಯ",
"channel_reminders_description": "ನೀವು ನಿಗದಿಪಡಿಸಿದ ಕಾರ್ಯಗಳ ಜ್ಞಾಪನೆಗಳು.",
"sound_default": "ಡೀಫಾಲ್ಟ್", "sound_kairos_bell": "ಕೈರೋಸ್ ಗಂಟೆ", "sound_soft_chime": "ಮೃದು ನಾದ", "sound_focus": "ಏಕಾಗ್ರತೆ", "sound_silent": "ನಿಶ್ಶಬ್ದ",
"settings": "ಸೆಟ್ಟಿಂಗ್ಸ್", "settings_summary": "ಭಾಷೆ, ನೋಟ, ಅಧಿಸೂಚನೆಗಳು, ಧ್ವನಿಗಳು", "calendar": "ಕ್ಯಾಲೆಂಡರ್", "calendar_summary": "ನಿಮ್ಮ ಯೋಜನೆಯ ತಿಂಗಳ ನೋಟ",
"trash": "ಕಸದ ಬುಟ್ಟಿ", "trash_summary": "ಅಳಿಸಿದ ಕಾರ್ಯಗಳು, ಟ್ರ್ಯಾಕರ್‌ಗಳು ಮತ್ತು ಪುಸ್ತಕಗಳನ್ನು ಮರಳಿ ಪಡೆಯಿರಿ", "privacy": "ಗೌಪ್ಯತೆ", "privacy_summary": "ನಿಮ್ಮ ಮಾಹಿತಿ ಈ ಸಾಧನದಲ್ಲೇ ಇರುತ್ತದೆ",
"about": "ಕುರಿತು", "about_summary": "ಕೈರೋಸ್ ಎರಾ ಮತ್ತು ಅದರ ಅರ್ಥ", "coming_next": "ಮುಂದೆ ಬರಲಿರುವುದು", "soon": "ಮುಂಬರುವ ಅಪ್‌ಡೇಟ್‌ನಲ್ಲಿ",
"journal": "ದಿನಚರಿ", "statistics": "ಅಂಕಿಅಂಶಗಳು", "backup": "ಬ್ಯಾಕಪ್", "diagnostics": "ರೋಗನಿರ್ಣಯ",
"settings_general": "ಸಾಮಾನ್ಯ", "settings_language": "ಭಾಷೆ", "language_system": "ಫೋನ್ ಭಾಷೆ", "language_english": "English", "language_kannada": "ಕನ್ನಡ",
"settings_appearance": "ನೋಟ", "theme_system": "ಸಿಸ್ಟಮ್", "theme_light": "ತಿಳಿ", "theme_dark": "ಗಾಢ",
"dynamic_color": "ವಾಲ್‌ಪೇಪರ್ ಬಣ್ಣಗಳು", "dynamic_color_summary": "ಕೈರೋಸ್ ಬಣ್ಣಗಳ ಬದಲು ನಿಮ್ಮ ವಾಲ್‌ಪೇಪರ್‌ನ ಬಣ್ಣಗಳನ್ನು ಬಳಸಿ.",
"settings_notifications": "ಅಧಿಸೂಚನೆಗಳು", "notif_permission": "ಅಧಿಸೂಚನೆಗಳು", "status_allowed": "ಅನುಮತಿ ಇದೆ", "status_off": "ಆಫ್", "allow": "ಅನುಮತಿಸಿ",
"notif_permission_off_body": "ಅಧಿಸೂಚನೆಗಳಿಗೆ ಅನುಮತಿ ನೀಡುವವರೆಗೆ ಜ್ಞಾಪನೆಗಳು ಕಾಣುವುದಿಲ್ಲ. ಉಳಿದೆಲ್ಲವೂ ಸಾಮಾನ್ಯವಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ.",
"exact_alarms": "ಸಮಯಕ್ಕೆ ಸರಿಯಾದ ಜ್ಞಾಪನೆಗಳು", "exact_alarms_off_body": "ಇದಿಲ್ಲದಿದ್ದರೆ, ಬ್ಯಾಟರಿ ಉಳಿಸಲು Android ಜ್ಞಾಪನೆಗಳನ್ನು ಕೆಲವು ನಿಮಿಷ ತಡವಾಗಿ ನೀಡಬಹುದು.",
"open_settings": "ಸೆಟ್ಟಿಂಗ್ಸ್ ತೆರೆಯಿರಿ", "battery_title": "ಬ್ಯಾಟರಿ ಆಪ್ಟಿಮೈಸೇಶನ್",
"battery_body": "ಕೆಲವು ಫೋನ್‌ಗಳು ಹಿನ್ನೆಲೆಯಲ್ಲಿ ಆ್ಯಪ್‌ಗಳನ್ನು ನಿಲ್ಲಿಸುತ್ತವೆ. ಜ್ಞಾಪನೆಗಳು ತಡವಾದರೆ, ಕೈರೋಸ್ ಎರಾಗೆ ನಿರ್ಬಂಧವಿಲ್ಲದೆ ಓಡಲು ಅನುಮತಿಸಿ.",
"test_notification": "ಪರೀಕ್ಷಾ ಅಧಿಸೂಚನೆ ಕಳುಹಿಸಿ", "test_notification_summary": "ಧ್ವನಿ ಮತ್ತು ನೋಟವನ್ನು ಪರಿಶೀಲಿಸಿ.",
"test_notification_title": "ಕೈರೋಸ್ ಎರಾ", "test_notification_text": "ಅಧಿಸೂಚನೆಗಳು ಕೆಲಸ ಮಾಡುತ್ತಿವೆ.",
"settings_sounds": "ಧ್ವನಿಗಳು", "default_sound": "ಹೊಸ ಜ್ಞಾಪನೆಗಳ ಡೀಫಾಲ್ಟ್ ಧ್ವನಿ",
"sound_channel_note": "ಪ್ರತಿ ಧ್ವನಿಯ ವಾಲ್ಯೂಮ್, ಕಂಪನ ಮತ್ತು ಪ್ರಾಮುಖ್ಯತೆಯನ್ನು Android ಸಿಸ್ಟಮ್ ಸೆಟ್ಟಿಂಗ್ಸ್‌ನಲ್ಲಿ ಬದಲಾಯಿಸಬಹುದು. ಅಲ್ಲಿನ ನಿಮ್ಮ ಆಯ್ಕೆಗಳನ್ನು ಗೌರವಿಸಲಾಗುತ್ತದೆ.",
"open_sound_settings": "ಅಧಿಸೂಚನೆ ಸೆಟ್ಟಿಂಗ್ಸ್ ತೆರೆಯಿರಿ",
"default_persistent": "ನಾನು ಕ್ರಮ ಕೈಗೊಳ್ಳುವವರೆಗೆ ಜ್ಞಾಪನೆ ಇರಲಿ", "default_persistent_summary": "ಮುಗಿದಿದೆ, ಮುಂದೂಡಿ ಅಥವಾ ಮರುನಿಗದಿ ಒತ್ತುವವರೆಗೆ ಹೊಸ ಜ್ಞಾಪನೆಗಳು ಅಧಿಸೂಚನೆ ಪಟ್ಟಿಯಲ್ಲಿ ಇರುತ್ತವೆ.",
"snooze_length": "ಮುಂದೂಡುವ ಅವಧಿ", "minutes_short": "%1$d ನಿಮಿಷ",
"settings_data": "ಮಾಹಿತಿ", "add_examples": "ಉದಾಹರಣೆಗಳನ್ನು ಸೇರಿಸಿ", "add_examples_summary": "ಆ್ಯಪ್ ಹೇಗೆ ಕಾಣುತ್ತದೆ ಎಂದು ನೋಡಲು ಕೆಲವು ಮಾದರಿ ಕಾರ್ಯಗಳು.",
"remove_examples": "ಉದಾಹರಣೆಗಳನ್ನು ತೆಗೆಯಿರಿ", "remove_examples_summary": "ಎಲ್ಲಾ ಉದಾಹರಣೆ ಕಾರ್ಯಗಳನ್ನು ಕಸದ ಬುಟ್ಟಿಗೆ ಸರಿಸುತ್ತದೆ.", "remove_examples_confirm": "ಎಲ್ಲಾ ಉದಾಹರಣೆ ಕಾರ್ಯಗಳನ್ನು ಕಸದ ಬುಟ್ಟಿಗೆ ಸರಿಸಬೇಕೆ? ನಂತರ ಮರಳಿ ಪಡೆಯಬಹುದು.",
"settings_footer": "ಕೈರೋಸ್ ಎರಾ ಸಂಪೂರ್ಣವಾಗಿ ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ. ಖಾತೆ, ಕ್ಲೌಡ್ ಸಿಂಕ್, ವಿಶ್ಲೇಷಣೆ ಅಥವಾ ಜಾಹೀರಾತುಗಳು ಇಲ್ಲ.",
"move_up": "ಮೇಲೆ ಸರಿಸಿ", "move_down": "ಕೆಳಗೆ ಸರಿಸಿ",
"trash_empty_title": "ಕಸದ ಬುಟ್ಟಿ ಖಾಲಿಯಿದೆ", "trash_empty_body": "ಅಳಿಸಿದ ಕಾರ್ಯಗಳು, ಟ್ರ್ಯಾಕರ್‌ಗಳು ಮತ್ತು ಪುಸ್ತಕಗಳು, ನೀವು ಮರಳಿ ಪಡೆಯುವವರೆಗೆ ಅಥವಾ ಶಾಶ್ವತವಾಗಿ ಅಳಿಸುವವರೆಗೆ ಇಲ್ಲಿರುತ್ತವೆ.",
"trash_explainer": "ನೀವು ನಿರ್ಧರಿಸುವವರೆಗೆ ಐಟಂಗಳು ಇಲ್ಲೇ ಇರುತ್ತವೆ. ಯಾವುದನ್ನೂ ತಾನಾಗಿಯೇ ತೆಗೆಯಲಾಗುವುದಿಲ್ಲ.",
"restore": "ಮರಳಿ ಪಡೆಯಿರಿ", "delete_forever": "ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಿ", "delete_forever_title": "ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಬೇಕೆ?",
"delete_forever_body": "\"%1$s\" ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಲ್ಪಡುತ್ತದೆ. ಇದನ್ನು ಹಿಂಪಡೆಯಲು ಸಾಧ್ಯವಿಲ್ಲ.", "deleted_on": "%1$s ರಂದು ಅಳಿಸಲಾಗಿದೆ",
"about_philosophy": "ದಿನವನ್ನು ಯೋಜಿಸಿ. ಏನಾದರೂ ಕಲಿಯಿರಿ. ದೇಹವನ್ನು ಚಲಿಸಿ. ಅರ್ಥಪೂರ್ಣವಾದುದನ್ನು ಓದಿ. ಚಿಂತಿಸಿ. ಪುನರಾವರ್ತಿಸಿ.",
"about_meaning": "ಕೈರೋಸ್ ಎಂದರೆ ಗ್ರೀಕ್ ಭಾಷೆಯಲ್ಲಿ ಸರಿಯಾದ, ಸೂಕ್ತ ಕ್ಷಣ. ಲಾಂಛನವು ಉದಯಿಸುವ ಸೂರ್ಯನತ್ತ ಸಾಗುವ ದಾರಿ: ಹೊಸ ದಿನ, ನಿರಂತರ ಪ್ರಗತಿ ಮತ್ತು ಬೆಳವಣಿಗೆ.",
"about_version": "ಆವೃತ್ತಿ %1$s",
"onboarding_welcome": "ನಿಮ್ಮ ಸಮಯ ನಿಮ್ಮದು.", "onboarding_private": "ಖಾಸಗಿ: ನಿಮ್ಮ ಯೋಜನೆಗಳು ನಿಮಗೆ ಮಾತ್ರ ಕಾಣುತ್ತವೆ.", "onboarding_local": "ಸ್ಥಳೀಯ: ಎಲ್ಲವೂ ಈ ಫೋನ್‌ನಲ್ಲೇ ಉಳಿಯುತ್ತದೆ.",
"onboarding_no_account": "ಖಾತೆ ಇಲ್ಲ, ಸೈನ್-ಇನ್ ಇಲ್ಲ.", "onboarding_no_cloud": "ಕ್ಲೌಡ್ ಸಿಂಕ್ ಇಲ್ಲ, ಟ್ರ್ಯಾಕಿಂಗ್ ಇಲ್ಲ, ಜಾಹೀರಾತು ಇಲ್ಲ.",
"onboarding_begin": "ಆರಂಭಿಸಿ", "onboarding_about_you": "ನಿಮ್ಮ ಬಗ್ಗೆ ಸ್ವಲ್ಪ", "onboarding_name_label": "ಹೆಸರು ಅಥವಾ ಅಡ್ಡಹೆಸರು",
"onboarding_focus": "ಯಾವುದರ ಮೇಲೆ ಗಮನ ಹರಿಸಲು ಬಯಸುವಿರಿ?", "focus_learning": "ಕಲಿಕೆ", "focus_health": "ಆರೋಗ್ಯ", "focus_reading": "ಓದು", "focus_work": "ಕೆಲಸ",
"focus_personal": "ವೈಯಕ್ತಿಕ", "focus_custom": "ಬೇರೆ ಏನಾದರೂ",
"onboarding_first_task": "ಇಂದು ಮಾಡಬೇಕಾದ ಒಂದು ಕೆಲಸ", "onboarding_first_task_hint": "ಐಚ್ಛಿಕ. ನಂತರ ಇನ್ನಷ್ಟು ಸೇರಿಸಬಹುದು.",
"onboarding_examples": "ಉದಾಹರಣೆ ಕಾರ್ಯಗಳನ್ನು ತೋರಿಸಿ (ಯಾವಾಗ ಬೇಕಾದರೂ ತೆಗೆಯಬಹುದು)",
"onboarding_reminders_title": "ಜ್ಞಾಪನೆಗಳು", "onboarding_reminders_body": "ಕಾರ್ಯದ ಸಮಯ ಬಂದಾಗ ಕೈರೋಸ್ ಎರಾ ನಿಮಗೆ ನೆನಪಿಸಬಹುದು. ಅದು ಕೇಳುವ ಏಕೈಕ ಅನುಮತಿ ಅಧಿಸೂಚನೆಗಳು; ಇದನ್ನು ಯಾವಾಗ ಬೇಕಾದರೂ ಬದಲಾಯಿಸಬಹುದು.",
"onboarding_allow_reminders": "ಜ್ಞಾಪನೆಗಳಿಗೆ ಅನುಮತಿಸಿ", "onboarding_not_now": "ಈಗ ಬೇಡ",
"sample_java": "ಜಾವಾ: ಕಲೆಕ್ಷನ್ಸ್", "sample_java_1": "List ಮತ್ತು ArrayList", "sample_java_2": "HashMap ಒಳರಚನೆ", "sample_java_3": "3 ಸಮಸ್ಯೆಗಳನ್ನು ಬಿಡಿಸಿ",
"sample_walk": "ಬೆಳಗಿನ ನಡಿಗೆ", "sample_project": "ಪ್ರಾಜೆಕ್ಟ್ ಕೆಲಸ", "sample_workout": "ವ್ಯಾಯಾಮ", "sample_read": "20 ಪುಟ ಓದಿ", "sample_reflection": "ದಿನದ ಚಿಂತನೆ",
# ಹಂತ 2: ಟ್ರ್ಯಾಕರ್‌ಗಳು, ಅಧ್ಯಯನ, ಓದುವಿಕೆ
"add": "ಸೇರಿಸಿ", "yes": "ಹೌದು", "no": "ಇಲ್ಲ", "see_all": "ಎಲ್ಲಾ ನೋಡಿ", "color_option": "ಬಣ್ಣ %1$d",
"new_tracker": "ಹೊಸ ಟ್ರ್ಯಾಕರ್", "edit_tracker": "ಟ್ರ್ಯಾಕರ್ ತಿದ್ದಿ",
"track_empty_title": "ನಿಮಗೆ ಮುಖ್ಯವಾದುದನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ", "track_empty_body": "ಅಧ್ಯಯನ, ವ್ಯಾಯಾಮ, ನಿದ್ರೆ, ನೀರು, ಅಭ್ಯಾಸಗಳು, ಪ್ರಾಜೆಕ್ಟ್‌ಗಳು ಅಥವಾ ಇನ್ನೇನಾದರೂ. ಒಂದು ಟೆಂಪ್ಲೇಟ್ ಆರಿಸಿ ಅಥವಾ ನಿಮ್ಮದೇ ರಚಿಸಿ.",
"track_today_summary": "ಇಂದು: %2$d ರಲ್ಲಿ %1$d ಪೂರ್ಣ",
"tracker_card_a11y": "%1$s, ಇಂದು %2$d%%, ಸತತ %3$d",
"tracker_rest_day": "ಇಂದಿಗೆ ಯೋಜಿಸಿಲ್ಲ", "tracker_done_today": "ಪೂರ್ಣ", "tracker_percent_today": "ಇಂದು %1$d%%",
"template_pick_title": "ಟ್ರ್ಯಾಕರ್ ಆರಂಭಿಸಿ", "template_pick_body": "ಟೆಂಪ್ಲೇಟ್‌ಗಳು ಕೇವಲ ಆರಂಭ. ಯಾವುದೇ ಅಂಶವನ್ನು ಮರುಹೆಸರಿಸಬಹುದು, ಸೇರಿಸಬಹುದು ಅಥವಾ ಆಫ್ ಮಾಡಬಹುದು.",
"template_study": "ಅಧ್ಯಯನ", "template_study_summary": "ಅಧ್ಯಯನ ಸಮಯ, ಅಭ್ಯಾಸ ಮತ್ತು ದೈನಂದಿನ ಗುರಿಗಳೊಂದಿಗೆ ವಿಷಯ ಯೋಜನೆ",
"template_fitness": "ಫಿಟ್‌ನೆಸ್", "template_fitness_summary": "ವ್ಯಾಯಾಮ, ಹೆಜ್ಜೆಗಳು, ನಿದ್ರೆ, ನೀರು, ಶಕ್ತಿ ಮತ್ತು ಮನಸ್ಥಿತಿ",
"template_reading": "ಓದುವ ಗುರಿ", "template_reading_summary": "ಪ್ರತಿದಿನ ಓದಿದ ಪುಟಗಳು ಮತ್ತು ನಿಮಿಷಗಳು",
"template_habit": "ಅಭ್ಯಾಸ", "template_habit_summary": "ಪ್ರತಿದಿನ ಒಂದು ಸರಳ ಹೌದು ಅಥವಾ ಇಲ್ಲ",
"template_project": "ಪ್ರಾಜೆಕ್ಟ್", "template_project_summary": "ಕಳೆದ ಸಮಯ, ಪ್ರಗತಿ ಮತ್ತು ಮುಂದಿನ ಹೆಜ್ಜೆ",
"template_finance": "ಹಣ", "template_finance_summary": "ಖರ್ಚು ಮತ್ತು ಖರ್ಚಿಲ್ಲದ ದಿನಗಳನ್ನು ದಾಖಲಿಸಿ",
"template_learning": "ಕೌಶಲ್ಯ ಕಲಿಕೆ", "template_learning_summary": "ಅಭ್ಯಾಸದ ಸಮಯ ಮತ್ತು ನೀವು ಕಲಿತದ್ದು",
"template_health": "ಆರೋಗ್ಯ", "template_health_summary": "ನೀರು, ನಿದ್ರೆ, ಔಷಧ ಮತ್ತು ಶಕ್ತಿ",
"template_personal": "ವೈಯಕ್ತಿಕ ಬೆಳವಣಿಗೆ", "template_personal_summary": "ಧ್ಯಾನ, ಪರದೆರಹಿತ ಸಮಯ ಮತ್ತು ಕೃತಜ್ಞತೆ",
"template_custom": "ನಿಮ್ಮದೇ", "template_custom_summary": "ಖಾಲಿ ಟ್ರ್ಯಾಕರ್‌ನಿಂದ ಆರಂಭಿಸಿ",
"tf_study_time": "ಅಧ್ಯಯನ ಸಮಯ", "tf_practice": "ಅಭ್ಯಾಸ ಸಮಸ್ಯೆಗಳು", "tf_revision": "ಪುನರಾವರ್ತನೆ ಆಯಿತು", "tf_notes": "ಟಿಪ್ಪಣಿಗಳು",
"tf_workout": "ವ್ಯಾಯಾಮ ಆಯಿತು", "tf_steps": "ಹೆಜ್ಜೆಗಳು", "tf_workout_minutes": "ವ್ಯಾಯಾಮ ಸಮಯ", "tf_sleep": "ನಿದ್ರೆ", "tf_water": "ನೀರು",
"tf_walk": "ನಡಿಗೆ", "tf_stretching": "ಸ್ಟ್ರೆಚಿಂಗ್", "tf_energy": "ಶಕ್ತಿ", "tf_mood": "ಮನಸ್ಥಿತಿ", "tf_weight": "ತೂಕ",
"tf_pages": "ಓದಿದ ಪುಟಗಳು", "tf_reading_minutes": "ಓದಿನ ಸಮಯ", "tf_done": "ಆಯಿತು",
"tf_worked_on_it": "ಕೆಲಸ ಮಾಡಿದೆ", "tf_time_spent": "ಕಳೆದ ಸಮಯ", "tf_progress": "ಪ್ರಗತಿ", "tf_next_step": "ಮುಂದಿನ ಹೆಜ್ಜೆ",
"tf_tracked_spending": "ಖರ್ಚು ಬರೆದಿಟ್ಟೆ", "tf_no_spend": "ಖರ್ಚಿಲ್ಲದ ದಿನ",
"tf_practice_time": "ಅಭ್ಯಾಸ ಸಮಯ", "tf_learned_count": "ಕಲಿತ ಹೊಸ ವಿಷಯಗಳು",
"tf_medicine": "ಔಷಧ ತೆಗೆದುಕೊಂಡೆ", "tf_meditation": "ಧ್ಯಾನ", "tf_screen_free": "ಪರದೆರಹಿತ ಒಂದು ಗಂಟೆ", "tf_gratitude": "ಕೃತಜ್ಞತೆ",
"unit_steps": "ಹೆಜ್ಜೆ", "unit_hours": "ಗಂ", "unit_litres": "ಲೀ", "unit_kg": "ಕೆಜಿ", "unit_pages": "ಪುಟ", "unit_minutes": "ನಿಮಿ",
"tracker_missing": "ಈ ಟ್ರ್ಯಾಕರ್ ಈಗ ಇಲ್ಲ", "tracker_missing_body": "ಇದನ್ನು ಕಸದ ಬುಟ್ಟಿಗೆ ಸರಿಸಿರಬಹುದು.",
"tracker_trash_body": "ಟ್ರ್ಯಾಕರ್ ಮತ್ತು ಅದರ ಇತಿಹಾಸ ಕಸದ ಬುಟ್ಟಿಗೆ ಹೋಗುತ್ತವೆ. ಇನ್ನಷ್ಟು > ಕಸದ ಬುಟ್ಟಿ ಇಂದ ಮರಳಿ ಪಡೆಯಬಹುದು.",
"tracker_why_line": "ಏಕೆ: %1$s", "tracker_gain_line": "ನನಗೆ ಸಿಗುವುದು: %1$s",
"tracker_log": "ದಾಖಲೆ", "tracker_no_fields": "ಈ ಟ್ರ್ಯಾಕರ್‌ನಲ್ಲಿ ಸಕ್ರಿಯ ಅಂಶಗಳಿಲ್ಲ. ಒಂದನ್ನು ಸೇರಿಸಲು ತಿದ್ದಿ.",
"field_target_line": "ಗುರಿ %1$s %2$s",
"tracker_stats": "ಪ್ರಗತಿ", "stat_current_streak": "ಈಗಿನ ಸತತ ದಿನಗಳು", "stat_best_streak": "ಅತ್ಯುತ್ತಮ ಸತತ",
"stat_completion_30": "ಕಳೆದ 30 ದಿನಗಳಲ್ಲಿ ಪೂರ್ಣ", "stat_active_days": "ಪ್ರಗತಿ ಇದ್ದ ದಿನಗಳು",
"tracker_missed_yesterday": "ನಿನ್ನೆ ತಪ್ಪಿತು. ಪರವಾಗಿಲ್ಲ: ಪ್ರತಿದಿನವೂ ಹೊಸ ಆರಂಭ.",
"tracker_history": "ಕಳೆದ 5 ವಾರಗಳು", "history_cell_a11y": "%1$s, %2$d%%",
"tracker_name": "ಹೆಸರು", "error_tracker_name": "ಟ್ರ್ಯಾಕರ್‌ಗೆ ಹೆಸರು ನೀಡಿ.",
"tracker_icon": "ಚಿಹ್ನೆ", "tracker_color": "ಬಣ್ಣ",
"tracker_why": "ಇದು ಏಕೆ ಮುಖ್ಯ", "tracker_why_hint": "ಉದಾ. ಬ್ಯಾಕೆಂಡ್ ಕೆಲಸಕ್ಕೆ ಬದಲಾಗಲು ಬಯಸುತ್ತೇನೆ",
"tracker_gain": "ನನಗೆ ಏನು ಸಿಗುತ್ತದೆ", "tracker_gain_hint": "ಉದಾ. ಸಂದರ್ಶನಗಳಲ್ಲಿ ಆತ್ಮವಿಶ್ವಾಸ",
"tracker_frequency": "ಎಷ್ಟು ಬಾರಿ", "freq_daily": "ಪ್ರತಿದಿನ", "freq_selected_days": "ಕೆಲವು ದಿನಗಳು", "freq_per_week": "ವಾರಕ್ಕೆ ಇಷ್ಟು ಬಾರಿ", "freq_per_month": "ತಿಂಗಳಿಗೆ ಇಷ್ಟು ಬಾರಿ",
"freq_times_week": "ವಾರಕ್ಕೆ %1$d ಬಾರಿ", "freq_times_month": "ತಿಂಗಳಿಗೆ %1$d ಬಾರಿ",
"tracker_fields": "ಏನನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಬೇಕು", "tracker_fields_note": "ಮೊದಲ ಅಂಶವೇ ಮುಖ್ಯ ಗುರಿ: ಅದು ಪೂರ್ಣವಾದರೆ ದಿನ ಪೂರ್ಣ. ತೆಗೆದ ಅಂಶಗಳ ಇತಿಹಾಸ ಉಳಿಯುತ್ತದೆ.",
"error_tracker_fields": "ಕನಿಷ್ಠ ಒಂದು ಅಂಶವನ್ನು ಆನ್ ಮಾಡಿ.", "error_checklist_empty": "ಪರಿಶೀಲನಾಪಟ್ಟಿಗೆ ಕನಿಷ್ಠ ಒಂದು ಐಟಂ ಬೇಕು.",
"add_field": "ಅಂಶ ಸೇರಿಸಿ", "edit_field": "ಅಂಶ ತಿದ್ದಿ", "field_label": "ಹೆಸರು", "field_type": "ಬಗೆ",
"field_target": "ದೈನಂದಿನ ಗುರಿ", "field_target_hint": "ಐಚ್ಛಿಕ. ಯಾವುದೇ ಮೊತ್ತ ಸಾಕಾದರೆ ಖಾಲಿ ಬಿಡಿ.", "field_unit": "ಘಟಕ",
"checklist_options": "ಐಟಂಗಳು, ಸಾಲಿಗೆ ಒಂದು", "checklist_items": "%1$d ಐಟಂಗಳು", "field_off": "ಆಫ್",
"remove_field": "ಅಂಶ ತೆಗೆಯಿರಿ", "remove_field_note": "ಹಿಂದಿನ ಮೌಲ್ಯಗಳು ಉಳಿಯುತ್ತವೆ; ಅಂಶವನ್ನು ಮರೆಮಾಡಲಾಗುತ್ತದೆ ಅಷ್ಟೇ.",
"type_checkbox": "ಹೌದು / ಇಲ್ಲ", "type_number": "ಸಂಖ್ಯೆ", "type_decimal": "ದಶಮಾಂಶ", "type_duration": "ನಿಮಿಷಗಳು", "type_pages": "ಪುಟಗಳು",
"type_percentage": "ಶೇಕಡಾ", "type_rating": "ರೇಟಿಂಗ್ 1-5", "type_text": "ಪಠ್ಯ", "type_checklist": "ಪರಿಶೀಲನಾಪಟ್ಟಿ",
"study_plan_for_day": "ಅಧ್ಯಯನ ಯೋಜನೆ", "study_plan_note": "ಗುರಿಯನ್ನು ಗುರುತಿಸಿದರೆ ಅದರ ವಿಷಯಕ್ಕೆ ಅಭ್ಯಾಸ ದಾಖಲಾಗುತ್ತದೆ. ವಿಷಯ ಯಾವಾಗ ಪೂರ್ಣ ಎಂದು ನೀವೇ ನಿರ್ಧರಿಸಿ.",
"add_study_target": "ಗುರಿ ಸೇರಿಸಿ", "remove_target": "ಗುರಿ ತೆಗೆಯಿರಿ", "study_target_hint": "ಏನನ್ನು ಅಧ್ಯಯನ ಮಾಡುವಿರಿ?", "study_target_topic": "ವಿಷಯ: %1$s",
"study_topics": "ವಿಷಯಗಳು", "study_topics_done": "%2$d ರಲ್ಲಿ %1$d ಪೂರ್ಣ", "study_topics_empty": "ನಿಮ್ಮ ವಿಷಯವನ್ನು ಉಪವಿಷಯಗಳಾಗಿ ವಿಂಗಡಿಸಿ, ಉದಾ. Java Core > Collections.",
"add_topic": "ವಿಷಯ ಸೇರಿಸಿ", "edit_topic": "ವಿಷಯ ತಿದ್ದಿ", "delete_topic": "ವಿಷಯ ಅಳಿಸಿ",
"delete_topic_body": "ವಿಷಯ ಅಳಿಸಲಾಗುತ್ತದೆ. ಅದರ ಉಪವಿಷಯಗಳು ಒಂದು ಹಂತ ಮೇಲಕ್ಕೆ ಹೋಗುತ್ತವೆ ಮತ್ತು ಗುರಿಗಳ ಪಠ್ಯ ಉಳಿಯುತ್ತದೆ.",
"topic_status": "ಸ್ಥಿತಿ", "topic_not_started": "ಆರಂಭಿಸಿಲ್ಲ", "topic_learning": "ಕಲಿಯುತ್ತಿದ್ದೇನೆ", "topic_reviewing": "ಪುನರಾವರ್ತನೆ", "topic_done": "ಪೂರ್ಣ",
"topic_confidence": "ಆತ್ಮವಿಶ್ವಾಸ", "topic_resources": "ಸಂಪನ್ಮೂಲಗಳು", "topic_questions": "ಉತ್ತರಿಸಬೇಕಾದ ಪ್ರಶ್ನೆಗಳು",
"topic_parent": "ಒಳಗೆ: %1$s", "topic_no_parent": "ಯಾವುದೂ ಇಲ್ಲ", "topic_practice_count": "%1$d ಅಭ್ಯಾಸ",
"add_book": "ಪುಸ್ತಕ ಸೇರಿಸಿ", "edit_book": "ಪುಸ್ತಕ ತಿದ್ದಿ",
"read_empty_title": "ಓದಿ, ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ, ನೆನಪಿಡಿ, ಅಳವಡಿಸಿ", "read_empty_body": "ಪುಟಗಳನ್ನು ದಾಖಲಿಸಲು ಮತ್ತು ಏಕೆ ಆರಂಭಿಸಿದಿರಿ, ಏನು ಕಲಿತಿರಿ, ಏನು ಅಳವಡಿಸಿದಿರಿ ಎಂದು ಬರೆದಿಡಲು ಪುಸ್ತಕ ಸೇರಿಸಿ.",
"reading_this_week": "ಈ ವಾರ", "pages_today": "ಇಂದಿನ ಪುಟಗಳು", "pages_week": "ಈ ವಾರದ ಪುಟಗಳು", "minutes_week": "ಈ ವಾರದ ನಿಮಿಷಗಳು",
"reading_days_line": "ಈ ವಾರ %1$d ದಿನ ಓದಿದ್ದೀರಿ · ಈ ವರ್ಷ %2$d ಪುಸ್ತಕ ಮುಗಿಸಿದ್ದೀರಿ",
"shelf_reading": "ಈಗ ಓದುತ್ತಿರುವುದು", "shelf_paused": "ನಿಲ್ಲಿಸಿದ್ದು", "shelf_want": "ಓದಬೇಕಿರುವುದು", "shelf_finished": "ಮುಗಿದಿದ್ದು",
"status_want": "ಓದಬೇಕು", "status_reading": "ಓದುತ್ತಿದ್ದೇನೆ", "status_paused": "ನಿಲ್ಲಿಸಿದೆ", "status_finished": "ಮುಗಿಯಿತು",
"book_page_of": "%2$d ರಲ್ಲಿ %1$d ನೇ ಪುಟ", "book_page_of_percent": "%2$d ರಲ್ಲಿ %1$d ನೇ ಪುಟ (%3$d%%)", "book_page_only": "%1$d ನೇ ಪುಟ",
"book_pages_per_day": "ಸಮಯಕ್ಕೆ ಮುಗಿಸಲು ದಿನಕ್ಕೆ %1$d ಪುಟ",
"book_progress": "ಪ್ರಗತಿ", "book_target_line": "ಗುರಿ: %1$s", "book_finished_on": "%1$s ರಂದು ಮುಗಿಯಿತು",
"log_reading": "ಓದು ದಾಖಲಿಸಿ", "pages_read": "ಓದಿದ ಪುಟಗಳು", "minutes_read": "ನಿಮಿಷಗಳು (ಐಚ್ಛಿಕ)",
"book_insights": "ಈ ಪುಸ್ತಕ ನಿಮಗೆ ಕೊಡುವುದು", "book_insights_note": "ನೀವು ಬರೆಯುತ್ತಿದ್ದಂತೆ ತಾನಾಗಿಯೇ ಉಳಿಸಲಾಗುತ್ತದೆ.",
"insight_why": "ನಾನು ಏಕೆ ಆರಂಭಿಸಿದೆ", "insight_expected": "ನಾನು ಏನು ನಿರೀಕ್ಷಿಸಿದ್ದೆ", "insight_learned": "ನಾನು ಏನು ಕಲಿತೆ",
"insight_key_ideas": "ಮುಖ್ಯ ವಿಚಾರಗಳು", "insight_applied": "ನಾನು ಏನು ಅಳವಡಿಸಿದೆ", "insight_changed": "ನನ್ನಲ್ಲಿ ಏನು ಬದಲಾಯಿತು",
"insight_skills": "ಸುಧಾರಿಸಿದ ಕೌಶಲ್ಯಗಳು", "insight_takeaway": "ಅಂತಿಮ ಪಾಠ", "insight_recommend": "ಮತ್ತೆ ಓದುತ್ತೇನೆಯೇ?",
"book_notes": "ಟಿಪ್ಪಣಿಗಳು ಮತ್ತು ಮುಖ್ಯಾಂಶಗಳು", "book_notes_empty": "ಓದುವಾಗ ಮುಖ್ಯಾಂಶ, ಟಿಪ್ಪಣಿ ಅಥವಾ ಪಾಠವನ್ನು ಬರೆದಿಡಿ.",
"add_note": "ಸೇರಿಸಿ", "delete_note": "ಟಿಪ್ಪಣಿ ಅಳಿಸಿ", "note_kind_note": "ಟಿಪ್ಪಣಿ", "note_kind_highlight": "ಮುಖ್ಯಾಂಶ", "note_kind_lesson": "ಪಾಠ",
"note_text": "ಪಠ್ಯ", "note_page": "ಪುಟ (ಐಚ್ಛಿಕ)", "page_short": "ಪು. %1$d",
"book_sessions": "ಓದಿನ ಅವಧಿಗಳು", "book_sessions_empty": "ಇನ್ನೂ ಯಾವುದೇ ಅವಧಿಗಳಿಲ್ಲ.", "session_line": "%1$d ಪುಟ · %2$d ನಿಮಿ",
"delete_session": "ಅವಧಿ ಅಳಿಸಿ", "delete_session_body": "ಈ ಅವಧಿಯನ್ನು ಅಳಿಸಬೇಕೆ? ಅದರ ಪುಟಗಳನ್ನು ನಿಮ್ಮ ಬುಕ್‌ಮಾರ್ಕ್‌ನಿಂದ ಕಳೆಯಲಾಗುತ್ತದೆ.",
"book_missing": "ಈ ಪುಸ್ತಕ ಈಗ ಇಲ್ಲ", "book_missing_body": "ಇದನ್ನು ಕಸದ ಬುಟ್ಟಿಗೆ ಸರಿಸಿರಬಹುದು.",
"book_trash_body": "ಪುಸ್ತಕ, ಅದರ ಟಿಪ್ಪಣಿಗಳು ಮತ್ತು ಅವಧಿಗಳು ಕಸದ ಬುಟ್ಟಿಗೆ ಹೋಗುತ್ತವೆ. ಇನ್ನಷ್ಟು > ಕಸದ ಬುಟ್ಟಿ ಇಂದ ಮರಳಿ ಪಡೆಯಬಹುದು.",
"book_title": "ಶೀರ್ಷಿಕೆ", "book_author": "ಲೇಖಕರು", "book_total_pages": "ಒಟ್ಟು ಪುಟಗಳು", "book_current_page": "ಈಗಿನ ಪುಟ",
"book_status": "ಸ್ಥಿತಿ", "book_target_date": "ಮುಗಿಸುವ ದಿನಾಂಕ", "book_no_target": "ಗುರಿ ದಿನಾಂಕವಿಲ್ಲ",
"error_book_title": "ಪುಸ್ತಕಕ್ಕೆ ಶೀರ್ಷಿಕೆ ನೀಡಿ.", "error_page_beyond": "ಈಗಿನ ಪುಟ ಕೊನೆಯ ಪುಟವನ್ನು ಮೀರಿದೆ.",
"home_trackers_line": "ಟ್ರ್ಯಾಕರ್‌ಗಳು: %2$d ರಲ್ಲಿ %1$d ಪೂರ್ಣ", "home_reading_line": "ಓದು: ಇಂದು %1$d ಪುಟ · %2$s",
"home_trackers_empty": "ಇನ್ನೂ ಟ್ರ್ಯಾಕರ್‌ಗಳಿಲ್ಲ. ಅಧ್ಯಯನ, ಫಿಟ್‌ನೆಸ್ ಅಥವಾ ಅಭ್ಯಾಸಕ್ಕಾಗಿ ಒಂದನ್ನು ರಚಿಸಲು ಒತ್ತಿ.",
"home_trackers_rest": "ಇಂದಿಗೆ ಏನೂ ಯೋಜಿಸಿಲ್ಲ. ವಿಶ್ರಾಂತಿ ಆನಂದಿಸಿ.",
"trash_kind_task": "ಕಾರ್ಯ", "trash_kind_tracker": "ಟ್ರ್ಯಾಕರ್", "trash_kind_book": "ಪುಸ್ತಕ",
"delete_forever_body_history": "\"%1$s\" ಮತ್ತು ಅದರ ಎಲ್ಲಾ ಇತಿಹಾಸ ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಲ್ಪಡುತ್ತದೆ. ಇದನ್ನು ಹಿಂಪಡೆಯಲು ಸಾಧ್ಯವಿಲ್ಲ.",
"sample_fitness_why": "ಉಳಿದೆಲ್ಲದಕ್ಕೂ ಹೆಚ್ಚು ಶಕ್ತಿ", "sample_study_name": "ಜಾವಾ ಬ್ಯಾಕೆಂಡ್",
"sample_study_why": "ಬ್ಯಾಕೆಂಡ್ ಸಂದರ್ಶನಗಳಲ್ಲಿ ಆತ್ಮವಿಶ್ವಾಸ ಪಡೆಯಲು",
"sample_topic_core": "Java Core", "sample_topic_collections": "Collections", "sample_topic_oop": "OOP ಮೂಲಗಳು",
"sample_topic_streams": "Streams ಮತ್ತು lambdas", "sample_topic_spring": "Spring Boot",
"sample_target_1": "HashMap ಒಳರಚನೆ ಬಗ್ಗೆ ಓದಿ", "sample_target_2": "Collections ಕುರಿತ 2 ಸಮಸ್ಯೆಗಳನ್ನು ಬಿಡಿಸಿ",
"sample_book_title": "Atomic Habits", "sample_book_author": "James Clear", "sample_book_why": "ಉಳಿಯುವ ಅಭ್ಯಾಸಗಳನ್ನು ಬೆಳೆಸಲು",
}

# Android plurals. Kannada uses "one" and "other" like English.
PLURALS_EN = {
"streak_days": {"one": "%1$d day", "other": "%1$d days"},
"streak_weeks": {"one": "%1$d week", "other": "%1$d weeks"},
"streak_months": {"one": "%1$d month", "other": "%1$d months"},
}

PLURALS_KN = {
"streak_days": {"one": "%1$d ದಿನ", "other": "%1$d ದಿನಗಳು"},
"streak_weeks": {"one": "%1$d ವಾರ", "other": "%1$d ವಾರಗಳು"},
"streak_months": {"one": "%1$d ತಿಂಗಳು", "other": "%1$d ತಿಂಗಳುಗಳು"},
}

# ---- Calm redesign (Home, Today, Add Task, Track, Study, Reading, Widgets) ----
EN.update({
"home_quick_add": "Quick add", "home_thought": "Today's thought", "home_stat_tasks": "Tasks done", "home_stat_progress": "Day progress",
"home_see_day": "See day", "home_keep_going": "Keep going",
"task_done_toast": "Done. One step closer.", "task_mark_done_a11y": "Mark \"%1$s\" as done", "done": "Done",
"quote_todays_action": "Today's action", "quote_save": "Save", "quote_saved": "Saved", "quote_share": "Share",
"quick_add_log": "Log progress",
"quick_add_task_hint": "Something to do today or later", "quick_add_log_hint": "Update a tracker for today",
"quick_add_study_hint": "A subject with topics to master", "quick_add_book_hint": "Start tracking a book",
"quick_add_tracker_hint": "Habit, fitness or anything else",
"quick_add_soon_note": "Coming soon",
})
KN.update({
"home_quick_add": "ತ್ವರಿತ ಸೇರ್ಪಡೆ", "home_thought": "ಇಂದಿನ ಚಿಂತನೆ", "home_stat_tasks": "ಮುಗಿದ ಕಾರ್ಯಗಳು", "home_stat_progress": "ದಿನದ ಪ್ರಗತಿ",
"home_see_day": "ದಿನ ನೋಡಿ", "home_keep_going": "ಮುಂದುವರಿಸಿ",
"task_done_toast": "ಮುಗಿಯಿತು. ಇನ್ನೊಂದು ಹೆಜ್ಜೆ ಮುಂದೆ.", "task_mark_done_a11y": "\"%1$s\" ಮುಗಿದಿದೆ ಎಂದು ಗುರುತಿಸಿ", "done": "ಮುಗಿದಿದೆ",
"quote_todays_action": "ಇಂದಿನ ಕ್ರಿಯೆ", "quote_save": "ಉಳಿಸಿ", "quote_saved": "ಉಳಿಸಲಾಗಿದೆ", "quote_share": "ಹಂಚಿಕೊಳ್ಳಿ",
"quick_add_log": "ಪ್ರಗತಿ ದಾಖಲಿಸಿ",
"quick_add_task_hint": "ಇಂದು ಅಥವಾ ನಂತರ ಮಾಡಬೇಕಾದದ್ದು", "quick_add_log_hint": "ಇಂದಿನ ಟ್ರ್ಯಾಕರ್ ನವೀಕರಿಸಿ",
"quick_add_study_hint": "ಕಲಿಯಬೇಕಾದ ವಿಷಯಗಳ ಅಧ್ಯಯನ", "quick_add_book_hint": "ಪುಸ್ತಕವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಪ್ರಾರಂಭಿಸಿ",
"quick_add_tracker_hint": "ಅಭ್ಯಾಸ, ಫಿಟ್‌ನೆಸ್ ಅಥವಾ ಬೇರೆ ಯಾವುದಾದರೂ",
"quick_add_soon_note": "ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ",
})
EN.update({
"planner_calendar": "Calendar", "planner_show_timeline": "Show timeline", "planner_show_calendar": "Show calendar",
"planner_summary": "%1$d tasks · %2$d completed", "planner_mark_open": "Mark as not done", "planner_delete": "Delete",
"planner_until": "until %1$s", "planner_month_summary": "%1$d of %2$d tasks done this month",
"reschedule_moved": "Moved to %1$s", "reschedule_later_today": "Later today", "reschedule_next_week": "Next week", "reschedule_pick": "Pick a date…",
})
KN.update({
"planner_calendar": "ಕ್ಯಾಲೆಂಡರ್", "planner_show_timeline": "ಸಮಯರೇಖೆ ತೋರಿಸಿ", "planner_show_calendar": "ಕ್ಯಾಲೆಂಡರ್ ತೋರಿಸಿ",
"planner_summary": "%1$d ಕಾರ್ಯಗಳು · %2$d ಮುಗಿದಿವೆ", "planner_mark_open": "ಮುಗಿದಿಲ್ಲ ಎಂದು ಗುರುತಿಸಿ", "planner_delete": "ಅಳಿಸಿ",
"planner_until": "%1$s ವರೆಗೆ", "planner_month_summary": "ಈ ತಿಂಗಳು %2$d ರಲ್ಲಿ %1$d ಕಾರ್ಯಗಳು ಮುಗಿದಿವೆ",
"reschedule_moved": "%1$s ಗೆ ಸರಿಸಲಾಗಿದೆ", "reschedule_later_today": "ಇಂದು ನಂತರ", "reschedule_next_week": "ಮುಂದಿನ ವಾರ", "reschedule_pick": "ದಿನಾಂಕ ಆರಿಸಿ…",
})
EN.update({
"task_what": "What needs to be done?", "task_pick_day": "Pick a day", "task_time": "Time", "task_set_time": "Set a time",
"section_reminder": "Reminder", "reminder_none": "None", "repeat_never": "Never",
"task_new_category": "New", "task_new_category_title": "New category", "task_new_category_hint": "e.g. Family",
"priority_normal": "Normal", "task_more_details": "More details", "task_create": "Create", "task_save_changes": "Save changes",
})
KN.update({
"task_what": "ಏನು ಮಾಡಬೇಕಿದೆ?", "task_pick_day": "ದಿನ ಆರಿಸಿ", "task_time": "ಸಮಯ", "task_set_time": "ಸಮಯ ಹೊಂದಿಸಿ",
"section_reminder": "ಜ್ಞಾಪನೆ", "reminder_none": "ಇಲ್ಲ", "repeat_never": "ಎಂದಿಗೂ ಇಲ್ಲ",
"task_new_category": "ಹೊಸದು", "task_new_category_title": "ಹೊಸ ವರ್ಗ", "task_new_category_hint": "ಉದಾ. ಕುಟುಂಬ",
"priority_normal": "ಸಾಮಾನ್ಯ", "task_more_details": "ಹೆಚ್ಚಿನ ವಿವರಗಳು", "task_create": "ರಚಿಸಿ", "task_save_changes": "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
})
EN.update({
"tracker_logged": "Logged. Nice work.", "tracker_todays_log": "Today's log", "tracker_daily_log": "Daily log",
"tracker_your_why": "Your why", "tracker_gaining": "What you're gaining",
"field_target_short": "Goal %1$s", "decrease_value": "Decrease %1$s", "increase_value": "Increase %1$s", "circle_value_a11y": "%1$s: %2$d",
"study_overall": "Overall", "study_completed_of": "%1$d completed / %2$d",
})
KN.update({
"tracker_logged": "ದಾಖಲಾಯಿತು. ಚೆನ್ನಾಗಿದೆ.", "tracker_todays_log": "ಇಂದಿನ ದಾಖಲೆ", "tracker_daily_log": "ದೈನಂದಿನ ದಾಖಲೆ",
"tracker_your_why": "ನಿಮ್ಮ ಕಾರಣ", "tracker_gaining": "ನೀವು ಪಡೆಯುತ್ತಿರುವುದು",
"field_target_short": "ಗುರಿ %1$s", "decrease_value": "%1$s ಕಡಿಮೆ ಮಾಡಿ", "increase_value": "%1$s ಹೆಚ್ಚಿಸಿ", "circle_value_a11y": "%1$s: %2$d",
"study_overall": "ಒಟ್ಟಾರೆ", "study_completed_of": "%1$d ಮುಗಿದಿದೆ / %2$d",
})
EN.update({
"track_subtitle": "Your progress", "track_active": "Active", "track_create_own": "Create your own tracker",
"track_topics_line": "%1$d/%2$d topics", "track_today_line": "Today %1$d/%2$d", "template_start_blank": "Start from blank",
})
KN.update({
"track_subtitle": "ನಿಮ್ಮ ಪ್ರಗತಿ", "track_active": "ಸಕ್ರಿಯ", "track_create_own": "ನಿಮ್ಮದೇ ಟ್ರ್ಯಾಕರ್ ರಚಿಸಿ",
"track_topics_line": "%1$d/%2$d ವಿಷಯಗಳು", "track_today_line": "ಇಂದು %1$d/%2$d", "template_start_blank": "ಖಾಲಿಯಿಂದ ಪ್ರಾರಂಭಿಸಿ",
})
EN.update({
"read_subtitle": "Your personal library", "read_currently": "Currently reading", "read_pages": "Pages today", "read_minutes": "Minutes today",
"read_week_line": "%1$d pages this week · %2$d reading days · %3$d finished this year",
"read_why_started": "Why I started", "read_gaining": "What I'm gaining", "read_my_library": "My library (%1$d)", "read_continue": "Continue reading",
"reading_logged": "Reading logged. Keep turning pages.", "book_reflection": "Reflection", "book_reflection_empty": "Not written yet.",
"book_add_reflection": "Add reflection", "book_edit_reflection": "Edit reflection", "read_to_end": "To the end (%1$d)",
})
KN.update({
"read_subtitle": "ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಗ್ರಂಥಾಲಯ", "read_currently": "ಈಗ ಓದುತ್ತಿರುವುದು", "read_pages": "ಇಂದಿನ ಪುಟಗಳು", "read_minutes": "ಇಂದಿನ ನಿಮಿಷಗಳು",
"read_week_line": "ಈ ವಾರ %1$d ಪುಟಗಳು · %2$d ಓದಿನ ದಿನಗಳು · ಈ ವರ್ಷ %3$d ಮುಗಿದಿವೆ",
"read_why_started": "ನಾನು ಏಕೆ ಪ್ರಾರಂಭಿಸಿದೆ", "read_gaining": "ನಾನು ಪಡೆಯುತ್ತಿರುವುದು", "read_my_library": "ನನ್ನ ಗ್ರಂಥಾಲಯ (%1$d)", "read_continue": "ಓದು ಮುಂದುವರಿಸಿ",
"reading_logged": "ಓದು ದಾಖಲಾಯಿತು. ಪುಟಗಳನ್ನು ತಿರುಗಿಸುತ್ತಿರಿ.", "book_reflection": "ಚಿಂತನೆ", "book_reflection_empty": "ಇನ್ನೂ ಬರೆದಿಲ್ಲ.",
"book_add_reflection": "ಚಿಂತನೆ ಸೇರಿಸಿ", "book_edit_reflection": "ಚಿಂತನೆ ಸಂಪಾದಿಸಿ", "read_to_end": "ಕೊನೆಯವರೆಗೆ (%1$d)",
})
EN.update({
"widget_motivation_label": "Motivation", "widget_motivation_desc": "Today's thought and one small action.",
"widget_tasks_label": "Today's tasks", "widget_tasks_desc": "Check off today's tasks from your home screen.",
"widget_progress_label": "Progress", "widget_progress_desc": "Tasks, study, reading and fitness at a glance.",
"widget_quick_add_label": "Quick add", "widget_quick_add_desc": "Add a task or log progress in one tap.",
"widget_add": "Add", "widget_done_count": "%1$d/%2$d done", "widget_empty": "Nothing planned. Enjoy the space.",
"widget_more_tasks": "+%1$d more", "widget_progress_title": "Today's progress", "widget_tasks": "Tasks",
"widget_study": "Study", "widget_reading": "Reading", "widget_fitness": "Fitness", "widget_keep_going": "Keep going.",
"widget_task": "Task", "widget_log": "Log", "widget_more": "More", "widget_brand": "KAIROS ERA",
"widget_mark_done": "Mark %1$s done", "widget_mark_open": "Mark %1$s not done", "widget_all_day": "Any time",
})
KN.update({
"widget_motivation_label": "ಪ್ರೇರಣೆ", "widget_motivation_desc": "ಇಂದಿನ ಚಿಂತನೆ ಮತ್ತು ಒಂದು ಸಣ್ಣ ಕ್ರಿಯೆ.",
"widget_tasks_label": "ಇಂದಿನ ಕಾರ್ಯಗಳು", "widget_tasks_desc": "ಹೋಮ್ ಸ್ಕ್ರೀನ್‌ನಿಂದಲೇ ಇಂದಿನ ಕಾರ್ಯಗಳನ್ನು ಗುರುತಿಸಿ.",
"widget_progress_label": "ಪ್ರಗತಿ", "widget_progress_desc": "ಕಾರ್ಯಗಳು, ಅಧ್ಯಯನ, ಓದು ಮತ್ತು ಫಿಟ್‌ನೆಸ್ ಒಂದೇ ನೋಟದಲ್ಲಿ.",
"widget_quick_add_label": "ತ್ವರಿತ ಸೇರ್ಪಡೆ", "widget_quick_add_desc": "ಒಂದೇ ಟ್ಯಾಪ್‌ನಲ್ಲಿ ಕಾರ್ಯ ಸೇರಿಸಿ ಅಥವಾ ಪ್ರಗತಿ ದಾಖಲಿಸಿ.",
"widget_add": "ಸೇರಿಸಿ", "widget_done_count": "%1$d/%2$d ಮುಗಿದಿದೆ", "widget_empty": "ಏನೂ ಯೋಜಿಸಿಲ್ಲ. ಈ ಬಿಡುವನ್ನು ಆನಂದಿಸಿ.",
"widget_more_tasks": "+%1$d ಇನ್ನಷ್ಟು", "widget_progress_title": "ಇಂದಿನ ಪ್ರಗತಿ", "widget_tasks": "ಕಾರ್ಯಗಳು",
"widget_study": "ಅಧ್ಯಯನ", "widget_reading": "ಓದು", "widget_fitness": "ಫಿಟ್‌ನೆಸ್", "widget_keep_going": "ಮುಂದುವರಿಸಿ.",
"widget_task": "ಕಾರ್ಯ", "widget_log": "ದಾಖಲಿಸಿ", "widget_more": "ಇನ್ನಷ್ಟು", "widget_brand": "ಕೈರೋಸ್ ಎರಾ",
"widget_mark_done": "%1$s ಮುಗಿದಿದೆ ಎಂದು ಗುರುತಿಸಿ", "widget_mark_open": "%1$s ಮುಗಿದಿಲ್ಲ ಎಂದು ಗುರುತಿಸಿ", "widget_all_day": "ಯಾವಾಗಲಾದರೂ",
})
EN.update({
"onb_step_of": "%1$s of %2$s", "onb_step_a11y": "Step %1$d of %2$d",
"onb_welcome_body": "Kairos Era helps you plan your day, build skills, track what matters, read with purpose, and reflect — all on your phone.",
"onb_feat_plan": "Plan", "onb_feat_plan_sub": "Organize your day", "onb_feat_learn": "Learn", "onb_feat_learn_sub": "Build new skills",
"onb_feat_track": "Track", "onb_feat_track_sub": "See your progress", "onb_feat_reflect": "Reflect", "onb_feat_reflect_sub": "Grow every day",
"onb_priv_private": "Private", "onb_priv_local": "Local", "onb_priv_no_account": "No account", "onb_priv_no_cloud": "No cloud sync",
"onb_priv_a11y": "Private and local: everything stays on this device. No account required. No cloud sync and no tracking.",
"onb_lets_begin": "Let's begin", "onb_change_later": "Everything can be changed later.",
"onb_focus_title": "What matters to you right now?", "onb_focus_sub": "Choose anything. You can change this later.",
"onb_focus_tasks": "Get things done", "onb_focus_tasks_sub": "Plan tasks and stay organized",
"onb_focus_learn": "Learn & study", "onb_focus_learn_sub": "Build skills and make progress",
"onb_focus_habits": "Build habits", "onb_focus_habits_sub": "Create routines that stick",
"onb_focus_health": "Health & movement", "onb_focus_health_sub": "Track your activity and wellness",
"onb_focus_read": "Read & remember", "onb_focus_read_sub": "Track books and capture insights",
"onb_focus_goals": "Personal goals", "onb_focus_goals_sub": "Turn your goals into action",
"onb_selected": "Selected", "onb_not_selected": "Not selected", "onb_continue": "Continue", "onb_skip": "Skip for now",
"onb_first_title": "Start with one thing.", "onb_first_sub": "You don't need a perfect plan. Add one thing you want to accomplish today.",
"onb_first_hint": "What would make today feel worthwhile?", "onb_first_example": "For example: Finish Java Collections",
"onb_when": "When?", "onb_anytime": "Anytime", "onb_morning": "Morning", "onb_afternoon": "Afternoon", "onb_evening": "Evening", "onb_pick_time": "Pick a time…",
"onb_quick_ideas": "Quick ideas (tap to use)", "onb_idea_1": "Study Java", "onb_idea_2": "Read 20 pages", "onb_idea_3": "Go for a walk", "onb_idea_4": "Plan tomorrow",
"onb_add_to_day": "Add to my day", "onb_later": "I'll do this later",
"onb_rem_title": "Want Kairos Era to remind you?", "onb_rem_sub": "Only when you ask it to. You control every reminder.",
"onb_rem_now": "now", "onb_rem_example_task": "Java — Collections", "onb_rem_body": "Time to focus. You got this.",
"onb_rem_done": "Done", "onb_rem_snooze": "Snooze", "onb_rem_preview_a11y": "Example reminder: %1$s at %2$s, with Done and Snooze buttons.",
"onb_rem_why1": "Reminders help you stay consistent with what matters.", "onb_rem_why2": "They stay on your phone and work without an account.",
"onb_rem_why3": "Kairos Era only asks for permissions when a feature needs them.",
"onb_ready_title": "Your day is ready.", "onb_ready_sub": "A small step today can create big changes tomorrow.",
"onb_optional": "Optional", "onb_starter_study": "Study plan", "onb_starter_study_sub": "Topics and small daily targets",
"onb_starter_habit": "Daily habit", "onb_starter_habit_sub": "One small yes each day",
"onb_starter_move": "Daily movement", "onb_starter_move_sub": "Stay active and feel better",
"onb_nothing_yet": "Nothing planned yet. Add something whenever you're ready.",
"onb_reminders_off": "Reminders are off. You can turn them on anytime in Android settings.",
"onb_stored": "Stored on this device", "onb_stored_sub": "Your data stays private and under your control.",
"onb_open": "Open Kairos Era", "onb_customize": "Customize anytime in Settings", "onb_todays_thought": "Today's thought",
})
KN.update({
"onb_step_of": "%2$s ರಲ್ಲಿ %1$s", "onb_step_a11y": "%2$d ರಲ್ಲಿ ಹಂತ %1$d",
"onb_welcome_body": "ನಿಮ್ಮ ದಿನವನ್ನು ಯೋಜಿಸಲು, ಕೌಶಲ್ಯಗಳನ್ನು ಬೆಳೆಸಲು, ಮುಖ್ಯವಾದುದನ್ನು ಗಮನಿಸಲು, ಉದ್ದೇಶದಿಂದ ಓದಲು ಮತ್ತು ಚಿಂತಿಸಲು ಕೈರೋಸ್ ಎರಾ ಸಹಾಯ ಮಾಡುತ್ತದೆ — ಎಲ್ಲವೂ ನಿಮ್ಮ ಫೋನ್‌ನಲ್ಲೇ.",
"onb_feat_plan": "ಯೋಜಿಸಿ", "onb_feat_plan_sub": "ನಿಮ್ಮ ದಿನವನ್ನು ಅಣಿಗೊಳಿಸಿ", "onb_feat_learn": "ಕಲಿಯಿರಿ", "onb_feat_learn_sub": "ಹೊಸ ಕೌಶಲ್ಯ ಬೆಳೆಸಿ",
"onb_feat_track": "ಗಮನಿಸಿ", "onb_feat_track_sub": "ನಿಮ್ಮ ಪ್ರಗತಿ ನೋಡಿ", "onb_feat_reflect": "ಚಿಂತಿಸಿ", "onb_feat_reflect_sub": "ಪ್ರತಿದಿನ ಬೆಳೆಯಿರಿ",
"onb_priv_private": "ಖಾಸಗಿ", "onb_priv_local": "ಸ್ಥಳೀಯ", "onb_priv_no_account": "ಖಾತೆ ಇಲ್ಲ", "onb_priv_no_cloud": "ಕ್ಲೌಡ್ ಸಿಂಕ್ ಇಲ್ಲ",
"onb_priv_a11y": "ಖಾಸಗಿ ಮತ್ತು ಸ್ಥಳೀಯ: ಎಲ್ಲವೂ ಈ ಸಾಧನದಲ್ಲೇ ಉಳಿಯುತ್ತದೆ. ಖಾತೆ ಬೇಕಿಲ್ಲ. ಕ್ಲೌಡ್ ಸಿಂಕ್ ಇಲ್ಲ, ಟ್ರ್ಯಾಕಿಂಗ್ ಇಲ್ಲ.",
"onb_lets_begin": "ಆರಂಭಿಸೋಣ", "onb_change_later": "ಎಲ್ಲವನ್ನೂ ನಂತರ ಬದಲಾಯಿಸಬಹುದು.",
"onb_focus_title": "ಈಗ ನಿಮಗೆ ಯಾವುದು ಮುಖ್ಯ?", "onb_focus_sub": "ಯಾವುದನ್ನಾದರೂ ಆರಿಸಿ. ನಂತರ ಬದಲಾಯಿಸಬಹುದು.",
"onb_focus_tasks": "ಕೆಲಸ ಮುಗಿಸಿ", "onb_focus_tasks_sub": "ಕಾರ್ಯಗಳನ್ನು ಯೋಜಿಸಿ, ಅಣಿಯಾಗಿರಿ",
"onb_focus_learn": "ಕಲಿಕೆ ಮತ್ತು ಅಧ್ಯಯನ", "onb_focus_learn_sub": "ಕೌಶಲ್ಯ ಬೆಳೆಸಿ, ಪ್ರಗತಿ ಸಾಧಿಸಿ",
"onb_focus_habits": "ಅಭ್ಯಾಸ ರೂಪಿಸಿ", "onb_focus_habits_sub": "ಉಳಿಯುವ ದಿನಚರಿ ರಚಿಸಿ",
"onb_focus_health": "ಆರೋಗ್ಯ ಮತ್ತು ಚಲನೆ", "onb_focus_health_sub": "ಚಟುವಟಿಕೆ ಮತ್ತು ಆರೋಗ್ಯ ಗಮನಿಸಿ",
"onb_focus_read": "ಓದಿ ಮತ್ತು ನೆನಪಿಡಿ", "onb_focus_read_sub": "ಪುಸ್ತಕಗಳು ಮತ್ತು ಒಳನೋಟಗಳನ್ನು ದಾಖಲಿಸಿ",
"onb_focus_goals": "ವೈಯಕ್ತಿಕ ಗುರಿಗಳು", "onb_focus_goals_sub": "ಗುರಿಗಳನ್ನು ಕ್ರಿಯೆಯಾಗಿಸಿ",
"onb_selected": "ಆಯ್ಕೆಯಾಗಿದೆ", "onb_not_selected": "ಆಯ್ಕೆಯಾಗಿಲ್ಲ", "onb_continue": "ಮುಂದುವರಿಸಿ", "onb_skip": "ಸದ್ಯಕ್ಕೆ ಬಿಡಿ",
"onb_first_title": "ಒಂದು ವಿಷಯದಿಂದ ಆರಂಭಿಸಿ.", "onb_first_sub": "ಪರಿಪೂರ್ಣ ಯೋಜನೆ ಬೇಕಿಲ್ಲ. ಇಂದು ಸಾಧಿಸಬೇಕೆನಿಸುವ ಒಂದು ವಿಷಯ ಸೇರಿಸಿ.",
"onb_first_hint": "ಯಾವುದು ಇಂದಿನ ದಿನವನ್ನು ಸಾರ್ಥಕಗೊಳಿಸುತ್ತದೆ?", "onb_first_example": "ಉದಾಹರಣೆಗೆ: ಜಾವಾ ಕಲೆಕ್ಷನ್ಸ್ ಮುಗಿಸಿ",
"onb_when": "ಯಾವಾಗ?", "onb_anytime": "ಯಾವಾಗಲಾದರೂ", "onb_morning": "ಬೆಳಿಗ್ಗೆ", "onb_afternoon": "ಮಧ್ಯಾಹ್ನ", "onb_evening": "ಸಂಜೆ", "onb_pick_time": "ಸಮಯ ಆರಿಸಿ…",
"onb_quick_ideas": "ತ್ವರಿತ ಆಲೋಚನೆಗಳು (ಬಳಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ)", "onb_idea_1": "ಜಾವಾ ಅಧ್ಯಯನ", "onb_idea_2": "20 ಪುಟ ಓದಿ", "onb_idea_3": "ನಡಿಗೆಗೆ ಹೋಗಿ", "onb_idea_4": "ನಾಳೆಯನ್ನು ಯೋಜಿಸಿ",
"onb_add_to_day": "ನನ್ನ ದಿನಕ್ಕೆ ಸೇರಿಸಿ", "onb_later": "ನಂತರ ಮಾಡುತ್ತೇನೆ",
"onb_rem_title": "ಕೈರೋಸ್ ಎರಾ ನಿಮಗೆ ನೆನಪಿಸಬೇಕೆ?", "onb_rem_sub": "ನೀವು ಕೇಳಿದಾಗ ಮಾತ್ರ. ಪ್ರತಿ ಜ್ಞಾಪನೆಯೂ ನಿಮ್ಮ ನಿಯಂತ್ರಣದಲ್ಲಿ.",
"onb_rem_now": "ಈಗ", "onb_rem_example_task": "ಜಾವಾ — ಕಲೆಕ್ಷನ್ಸ್", "onb_rem_body": "ಗಮನ ಹರಿಸುವ ಸಮಯ. ನೀವು ಮಾಡಬಲ್ಲಿರಿ.",
"onb_rem_done": "ಮುಗಿದಿದೆ", "onb_rem_snooze": "ಸ್ನೂಜ್", "onb_rem_preview_a11y": "ಉದಾಹರಣೆ ಜ್ಞಾಪನೆ: %2$s ಕ್ಕೆ %1$s, ಮುಗಿದಿದೆ ಮತ್ತು ಸ್ನೂಜ್ ಬಟನ್‌ಗಳೊಂದಿಗೆ.",
"onb_rem_why1": "ಮುಖ್ಯವಾದುದರಲ್ಲಿ ಸ್ಥಿರವಾಗಿರಲು ಜ್ಞಾಪನೆಗಳು ಸಹಾಯ ಮಾಡುತ್ತವೆ.", "onb_rem_why2": "ಅವು ನಿಮ್ಮ ಫೋನ್‌ನಲ್ಲೇ ಉಳಿಯುತ್ತವೆ, ಖಾತೆ ಇಲ್ಲದೆ ಕೆಲಸ ಮಾಡುತ್ತವೆ.",
"onb_rem_why3": "ಯಾವುದಾದರೂ ವೈಶಿಷ್ಟ್ಯಕ್ಕೆ ಬೇಕಾದಾಗ ಮಾತ್ರ ಕೈರೋಸ್ ಎರಾ ಅನುಮತಿ ಕೇಳುತ್ತದೆ.",
"onb_ready_title": "ನಿಮ್ಮ ದಿನ ಸಿದ್ಧವಾಗಿದೆ.", "onb_ready_sub": "ಇಂದಿನ ಒಂದು ಸಣ್ಣ ಹೆಜ್ಜೆ ನಾಳೆ ದೊಡ್ಡ ಬದಲಾವಣೆ ತರಬಹುದು.",
"onb_optional": "ಐಚ್ಛಿಕ", "onb_starter_study": "ಅಧ್ಯಯನ ಯೋಜನೆ", "onb_starter_study_sub": "ವಿಷಯಗಳು ಮತ್ತು ಸಣ್ಣ ದೈನಂದಿನ ಗುರಿಗಳು",
"onb_starter_habit": "ದೈನಂದಿನ ಅಭ್ಯಾಸ", "onb_starter_habit_sub": "ಪ್ರತಿದಿನ ಒಂದು ಸಣ್ಣ ಹೌದು",
"onb_starter_move": "ದೈನಂದಿನ ಚಲನೆ", "onb_starter_move_sub": "ಚುರುಕಾಗಿರಿ, ಚೆನ್ನಾಗಿರಿ",
"onb_nothing_yet": "ಇನ್ನೂ ಏನೂ ಯೋಜಿಸಿಲ್ಲ. ಸಿದ್ಧರಾದಾಗ ಸೇರಿಸಿ.",
"onb_reminders_off": "ಜ್ಞಾಪನೆಗಳು ಆಫ್ ಆಗಿವೆ. Android ಸೆಟ್ಟಿಂಗ್ಸ್‌ನಲ್ಲಿ ಯಾವಾಗ ಬೇಕಾದರೂ ಆನ್ ಮಾಡಬಹುದು.",
"onb_stored": "ಈ ಸಾಧನದಲ್ಲೇ ಸಂಗ್ರಹ", "onb_stored_sub": "ನಿಮ್ಮ ಮಾಹಿತಿ ಖಾಸಗಿಯಾಗಿ, ನಿಮ್ಮ ನಿಯಂತ್ರಣದಲ್ಲಿ ಉಳಿಯುತ್ತದೆ.",
"onb_open": "ಕೈರೋಸ್ ಎರಾ ತೆರೆಯಿರಿ", "onb_customize": "ಸೆಟ್ಟಿಂಗ್ಸ್‌ನಲ್ಲಿ ಯಾವಾಗ ಬೇಕಾದರೂ ಬದಲಿಸಿ", "onb_todays_thought": "ಇಂದಿನ ಚಿಂತನೆ",
})

# --- 0.5.0: Journal, Statistics, Life Calendar -------------------------------------------------
EN.update({
"nav_journal": "Journal",
"journal_hero_line": "A few lines today create a clearer tomorrow.",
"journal_new": "New reflection",
"journal_search": "Search your journal",
"journal_no_matches": "No reflections match that search.",
"journal_empty_body": "Your reflections will gather here, one date and one line each. Write a few words tonight and look back on them next month.",
"journal_today": "Today",
"journal_continue": "Continue writing",
"journal_write_today": "Write today's reflection",
"journal_summary_line": "%1$d this month · %2$d in all",
"journal_mood_question": "How was today?",
"journal_mood_optional": "Optional. Skip it if you like.",
"journal_reflection_label": "Reflection",
"journal_what_happened": "What happened today?",
"journal_lesson": "What did I learn?",
"journal_lesson_hint": "One thing you understood or noticed",
"journal_tomorrow": "What do I want to do tomorrow?",
"journal_tomorrow_hint": "One thing that would make tomorrow good",
"journal_plan_tomorrow": "Add it to tomorrow's plan",
"journal_plan_tomorrow_hint": "Creates a task for tomorrow when you save",
"journal_more_prompts": "More prompts",
"journal_fewer_prompts": "Fewer prompts",
"journal_win": "A small win",
"journal_win_hint": "Something that went well",
"journal_gratitude": "Grateful for",
"journal_gratitude_hint": "A person, a moment, anything",
"journal_save_reflection": "Save reflection",
"journal_private_note": "Your journal stays on this phone. It is never uploaded or shared.",
"journal_saved": "Reflection saved",
"journal_saved_task": "Reflection saved and added to tomorrow",
"journal_trashed": "Reflection moved to Trash",
"journal_discard_title": "Leave without saving?",
"journal_discard_body": "What you wrote since opening this page will be lost.",
"journal_delete_title": "Move this reflection to Trash?",
"journal_delete_body": "You can restore it from More › Trash.",
"journal_prompt_1": "What moved you forward today?",
"journal_prompt_2": "What took your attention today, and was it worth it?",
"journal_prompt_3": "What would you do differently if today started again?",
"journal_prompt_4": "When did you feel most like yourself today?",
"journal_prompt_5": "What did you finish, even if it was small?",
"journal_prompt_6": "What is one thing you want to remember about today?",
"journal_prompt_7": "What did today teach you?",
"journal_summary": "Your reflections, one day at a time",
"mood_great": "Great",
"mood_good": "Good",
"mood_okay": "Okay",
"mood_low": "Low",
"mood_hard": "Hard",
"delete": "Delete",
"discard": "Discard",
"trash_kind_journal": "Reflection",
"quick_add_journal_hint": "A few lines about today",
"widget_note": "Note",
"sample_journal_text": "Finally understood how HashMap handles collisions. The walk in the evening cleared my head.",
"sample_journal_win": "Finished three Java topics",
"sample_journal_lesson": "Short focused sessions work better than one long one",
"sample_journal_gratitude": "A quiet morning to study",
"sample_journal_tomorrow": "Revise TreeMap before lunch",
"sample_journal_text_2": "Slow start, but I still read ten pages before bed. Need to sleep earlier.",

"statistics_summary": "Am I actually making progress?",
"life_calendar": "Life Calendar",
"life_calendar_summary": "What you actually did with your days",
"reading_summary": "Your books and reading sessions",
"more_reflect": "Reflect",
"more_app": "App",
"more_options": "More options",
"try_again": "Try again",
"history_error_title": "Something went wrong",
"history_error_body": "Something went wrong loading your history. Your data is safe.",
"stats_range_7d": "7D",
"stats_range_30d": "30D",
"stats_range_90d": "90D",
"stats_range_1y": "1Y",
"stats_last_7": "Last 7 days",
"stats_last_30": "Last 30 days",
"stats_last_90": "Last 90 days",
"stats_last_year": "Last 12 months",
"stats_consistency_title": "Your consistency",
"stats_consistency_a11y": "Consistency %1$d percent: active on %2$d of %3$d days",
"stats_active_of": "%1$d active days out of %2$d",
"stats_change_up": "↑ %1$d%% compared with the period before",
"stats_change_down": "↓ %1$d%% compared with the period before",
"stats_change_same": "The same as the period before",
"stats_active_day_explain": "An active day is a day you completed at least one thing: a task, a tracker log, a study topic, a reading session or a reflection.",
"stats_activity": "Activity",
"stats_less": "Less",
"stats_more": "More",
"stats_day_a11y": "%1$s, %2$d things done",
"stats_map_a11y": "Activity map: active on %1$d of %2$d days. Tap a day to open it in the Life Calendar.",
"stats_your_areas": "Your areas",
"stats_area_tasks": "Tasks",
"stats_area_reading": "Reading",
"stats_area_journal": "Reflection",
"stats_completed": "What you completed",
"stats_tile_tasks": "Tasks done",
"stats_tile_study": "Study sessions",
"stats_tile_topics": "Topics learned",
"stats_tile_pages": "Pages read",
"stats_tile_active_minutes": "Active minutes",
"stats_tile_workouts": "Workouts",
"stats_tile_reflections": "Reflections",
"stats_momentum": "Your momentum",
"momentum_rising": "You're showing up more consistently than the week before: something done on %1$d of the last 7 days.",
"momentum_steady": "Your activity has been steady this week: something done on %1$d of the last 7 days.",
"momentum_easing": "You completed something on %1$d of the last 7 days. One small step today keeps the thread going.",
"momentum_started": "You've been active on %1$d of your first %2$d days. Every day you show up adds to your story.",
"momentum_quiet": "A quiet stretch. Pick one small thing for today and your story continues.",
"stats_milestones": "Personal milestones",
"stats_milestones_note": "Your own bests in this period. No comparisons with anyone else.",
"record_streak": "Longest active streak",
"record_tasks": "Most tasks completed in one day",
"record_pages": "Most pages in one week",
"record_session": "Longest study or reading session",
"stats_private": "Your data stays on this device. No account, no cloud, no tracking.",
"stats_empty_title": "Your story starts here",
"stats_empty_body": "Complete your first task, finish a study session, read a few pages or create your first tracker. Kairos Era will start building your progress history.",
"stats_empty_action": "Create something",
"duration_hm": "%1$dh %2$dm",
"duration_m": "%1$d min",

"previous_month": "Previous month",
"next_month": "Next month",
"previous_year": "Previous year",
"next_year": "Next year",
"calendar_view_year": "View year",
"calendar_view_month": "View month",
"calendar_has_reflection": "reflection written",
"calendar_so_far": "%1$s so far",
"calendar_future_month": "This month hasn't happened yet. Its story starts when it arrives.",
"calendar_quiet_month": "Nothing recorded this month yet.",
"calendar_todays_story": "Today's story",
"calendar_days_story": "The day's story",
"calendar_planned": "Planned",
"calendar_nothing_planned": "Nothing planned for this day yet.",
"calendar_quiet_day": "A quiet day. Nothing was recorded.",
"calendar_of_planned": "%1$s of %2$d planned",
"calendar_reflection": "Reflection",
"calendar_view_full_day": "View full day",
"calendar_read_journal": "Read journal",
"calendar_write": "Write a reflection",
"calendar_open_day": "Open in Today",
"previous_activity": "Previous activity",
"activity_task_done": "Task completed",
"activity_topic_done": "Study topic done",
"activity_reflection": "Reflection written",
"day_plan": "Plan",
"day_timeline": "Timeline",
"day_during": "During the day",
})

KN.update({
"nav_journal": "ಜರ್ನಲ್",
"journal_hero_line": "ಇಂದು ಬರೆದ ಕೆಲವು ಸಾಲುಗಳು ನಾಳೆಯನ್ನು ಸ್ಪಷ್ಟಗೊಳಿಸುತ್ತವೆ.",
"journal_new": "ಹೊಸ ಚಿಂತನೆ",
"journal_search": "ನಿಮ್ಮ ಜರ್ನಲ್‌ನಲ್ಲಿ ಹುಡುಕಿ",
"journal_no_matches": "ಈ ಹುಡುಕಾಟಕ್ಕೆ ಯಾವುದೇ ಚಿಂತನೆ ಹೊಂದುತ್ತಿಲ್ಲ.",
"journal_empty_body": "ನಿಮ್ಮ ಚಿಂತನೆಗಳು ಇಲ್ಲಿ ಸೇರುತ್ತವೆ, ಪ್ರತಿ ದಿನಾಂಕಕ್ಕೆ ಒಂದು ಸಾಲು. ಇಂದು ರಾತ್ರಿ ಕೆಲವು ಪದಗಳನ್ನು ಬರೆಯಿರಿ, ಮುಂದಿನ ತಿಂಗಳು ಹಿಂತಿರುಗಿ ನೋಡಿ.",
"journal_today": "ಇಂದು",
"journal_continue": "ಬರೆಯುವುದನ್ನು ಮುಂದುವರಿಸಿ",
"journal_write_today": "ಇಂದಿನ ಚಿಂತನೆ ಬರೆಯಿರಿ",
"journal_summary_line": "ಈ ತಿಂಗಳು %1$d · ಒಟ್ಟು %2$d",
"journal_mood_question": "ಇಂದು ಹೇಗಿತ್ತು?",
"journal_mood_optional": "ಐಚ್ಛಿಕ. ಬೇಕಿದ್ದರೆ ಬಿಟ್ಟುಬಿಡಿ.",
"journal_reflection_label": "ಚಿಂತನೆ",
"journal_what_happened": "ಇಂದು ಏನಾಯಿತು?",
"journal_lesson": "ನಾನು ಏನು ಕಲಿತೆ?",
"journal_lesson_hint": "ನೀವು ಅರ್ಥಮಾಡಿಕೊಂಡ ಅಥವಾ ಗಮನಿಸಿದ ಒಂದು ವಿಷಯ",
"journal_tomorrow": "ನಾಳೆ ನಾನು ಏನು ಮಾಡಬೇಕು?",
"journal_tomorrow_hint": "ನಾಳೆಯನ್ನು ಚೆನ್ನಾಗಿಸುವ ಒಂದು ವಿಷಯ",
"journal_plan_tomorrow": "ನಾಳೆಯ ಯೋಜನೆಗೆ ಸೇರಿಸಿ",
"journal_plan_tomorrow_hint": "ಉಳಿಸಿದಾಗ ನಾಳೆಗೆ ಒಂದು ಕಾರ್ಯ ರಚಿಸುತ್ತದೆ",
"journal_more_prompts": "ಇನ್ನಷ್ಟು ಪ್ರಶ್ನೆಗಳು",
"journal_fewer_prompts": "ಕಡಿಮೆ ಪ್ರಶ್ನೆಗಳು",
"journal_win": "ಒಂದು ಸಣ್ಣ ಗೆಲುವು",
"journal_win_hint": "ಚೆನ್ನಾಗಿ ನಡೆದ ಒಂದು ವಿಷಯ",
"journal_gratitude": "ಕೃತಜ್ಞತೆ",
"journal_gratitude_hint": "ಒಬ್ಬ ವ್ಯಕ್ತಿ, ಒಂದು ಕ್ಷಣ, ಏನಾದರೂ",
"journal_save_reflection": "ಚಿಂತನೆ ಉಳಿಸಿ",
"journal_private_note": "ನಿಮ್ಮ ಜರ್ನಲ್ ಈ ಫೋನ್‌ನಲ್ಲೇ ಇರುತ್ತದೆ. ಅದನ್ನು ಎಂದಿಗೂ ಅಪ್‌ಲೋಡ್ ಅಥವಾ ಹಂಚಿಕೊಳ್ಳಲಾಗುವುದಿಲ್ಲ.",
"journal_saved": "ಚಿಂತನೆ ಉಳಿಸಲಾಗಿದೆ",
"journal_saved_task": "ಚಿಂತನೆ ಉಳಿಸಲಾಗಿದೆ ಮತ್ತು ನಾಳೆಗೆ ಸೇರಿಸಲಾಗಿದೆ",
"journal_trashed": "ಚಿಂತನೆಯನ್ನು ಕಸದ ಬುಟ್ಟಿಗೆ ಸರಿಸಲಾಗಿದೆ",
"journal_discard_title": "ಉಳಿಸದೆ ಹೊರಹೋಗಬೇಕೆ?",
"journal_discard_body": "ಈ ಪುಟ ತೆರೆದ ನಂತರ ನೀವು ಬರೆದದ್ದು ಕಳೆದುಹೋಗುತ್ತದೆ.",
"journal_delete_title": "ಈ ಚಿಂತನೆಯನ್ನು ಕಸದ ಬುಟ್ಟಿಗೆ ಸರಿಸಬೇಕೆ?",
"journal_delete_body": "ಇನ್ನಷ್ಟು › ಕಸದ ಬುಟ್ಟಿಯಿಂದ ಅದನ್ನು ಮರಳಿ ಪಡೆಯಬಹುದು.",
"journal_prompt_1": "ಇಂದು ನಿಮ್ಮನ್ನು ಮುಂದಕ್ಕೆ ಕೊಂಡೊಯ್ದದ್ದು ಯಾವುದು?",
"journal_prompt_2": "ಇಂದು ನಿಮ್ಮ ಗಮನ ಸೆಳೆದದ್ದು ಏನು, ಅದು ಯೋಗ್ಯವಾಗಿತ್ತೇ?",
"journal_prompt_3": "ಇಂದು ಮತ್ತೆ ಶುರುವಾದರೆ ನೀವು ಏನನ್ನು ಬೇರೆ ರೀತಿ ಮಾಡುತ್ತೀರಿ?",
"journal_prompt_4": "ಇಂದು ಯಾವಾಗ ನೀವು ನೀವಾಗಿಯೇ ಇದ್ದಿರಿ ಎನಿಸಿತು?",
"journal_prompt_5": "ಸಣ್ಣದಾದರೂ, ಇಂದು ನೀವು ಏನನ್ನು ಮುಗಿಸಿದಿರಿ?",
"journal_prompt_6": "ಇಂದಿನ ಬಗ್ಗೆ ನೆನಪಿಡಬೇಕಾದ ಒಂದು ವಿಷಯ ಯಾವುದು?",
"journal_prompt_7": "ಇಂದು ನಿಮಗೆ ಏನು ಕಲಿಸಿತು?",
"journal_summary": "ನಿಮ್ಮ ಚಿಂತನೆಗಳು, ದಿನಕ್ಕೆ ಒಂದು",
"mood_great": "ಅದ್ಭುತ",
"mood_good": "ಚೆನ್ನಾಗಿತ್ತು",
"mood_okay": "ಪರವಾಗಿಲ್ಲ",
"mood_low": "ಮಂದ",
"mood_hard": "ಕಷ್ಟ",
"delete": "ಅಳಿಸಿ",
"discard": "ತ್ಯಜಿಸಿ",
"trash_kind_journal": "ಚಿಂತನೆ",
"quick_add_journal_hint": "ಇಂದಿನ ಬಗ್ಗೆ ಕೆಲವು ಸಾಲುಗಳು",
"widget_note": "ಟಿಪ್ಪಣಿ",
"sample_journal_text": "HashMap ಘರ್ಷಣೆಗಳನ್ನು ಹೇಗೆ ನಿಭಾಯಿಸುತ್ತದೆ ಎಂದು ಕೊನೆಗೂ ಅರ್ಥವಾಯಿತು. ಸಂಜೆಯ ನಡಿಗೆ ಮನಸ್ಸನ್ನು ಹಗುರಗೊಳಿಸಿತು.",
"sample_journal_win": "ಮೂರು Java ವಿಷಯಗಳನ್ನು ಮುಗಿಸಿದೆ",
"sample_journal_lesson": "ಒಂದು ದೀರ್ಘ ಅವಧಿಗಿಂತ ಸಣ್ಣ ಕೇಂದ್ರೀಕೃತ ಅವಧಿಗಳು ಉತ್ತಮ",
"sample_journal_gratitude": "ಓದಲು ಶಾಂತವಾದ ಬೆಳಗು",
"sample_journal_tomorrow": "ಊಟಕ್ಕೆ ಮೊದಲು TreeMap ಪುನರಾವರ್ತಿಸು",
"sample_journal_text_2": "ನಿಧಾನ ಆರಂಭ, ಆದರೂ ಮಲಗುವ ಮೊದಲು ಹತ್ತು ಪುಟ ಓದಿದೆ. ಬೇಗ ಮಲಗಬೇಕು.",

"statistics_summary": "ನಾನು ನಿಜವಾಗಿ ಮುನ್ನಡೆಯುತ್ತಿದ್ದೇನೆಯೇ?",
"life_calendar": "ಜೀವನ ಕ್ಯಾಲೆಂಡರ್",
"life_calendar_summary": "ನಿಮ್ಮ ದಿನಗಳಲ್ಲಿ ನೀವು ನಿಜವಾಗಿ ಮಾಡಿದ್ದು",
"reading_summary": "ನಿಮ್ಮ ಪುಸ್ತಕಗಳು ಮತ್ತು ಓದಿನ ಅವಧಿಗಳು",
"more_reflect": "ಚಿಂತನೆ",
"more_app": "ಆ್ಯಪ್",
"more_options": "ಇನ್ನಷ್ಟು ಆಯ್ಕೆಗಳು",
"try_again": "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
"history_error_title": "ಏನೋ ತಪ್ಪಾಗಿದೆ",
"history_error_body": "ನಿಮ್ಮ ಇತಿಹಾಸವನ್ನು ತೆರೆಯುವಾಗ ಏನೋ ತಪ್ಪಾಗಿದೆ. ನಿಮ್ಮ ಡೇಟಾ ಸುರಕ್ಷಿತವಾಗಿದೆ.",
"stats_range_7d": "7ದಿ",
"stats_range_30d": "30ದಿ",
"stats_range_90d": "90ದಿ",
"stats_range_1y": "1ವ",
"stats_last_7": "ಕಳೆದ 7 ದಿನಗಳು",
"stats_last_30": "ಕಳೆದ 30 ದಿನಗಳು",
"stats_last_90": "ಕಳೆದ 90 ದಿನಗಳು",
"stats_last_year": "ಕಳೆದ 12 ತಿಂಗಳು",
"stats_consistency_title": "ನಿಮ್ಮ ನಿರಂತರತೆ",
"stats_consistency_a11y": "ನಿರಂತರತೆ ಶೇಕಡಾ %1$d: %3$d ದಿನಗಳಲ್ಲಿ %2$d ದಿನ ಸಕ್ರಿಯ",
"stats_active_of": "%2$d ದಿನಗಳಲ್ಲಿ %1$d ಸಕ್ರಿಯ ದಿನಗಳು",
"stats_change_up": "↑ ಹಿಂದಿನ ಅವಧಿಗಿಂತ %1$d%%",
"stats_change_down": "↓ ಹಿಂದಿನ ಅವಧಿಗಿಂತ %1$d%%",
"stats_change_same": "ಹಿಂದಿನ ಅವಧಿಯಷ್ಟೇ",
"stats_active_day_explain": "ಸಕ್ರಿಯ ದಿನ ಎಂದರೆ ನೀವು ಕನಿಷ್ಠ ಒಂದನ್ನು ಮುಗಿಸಿದ ದಿನ: ಒಂದು ಕಾರ್ಯ, ಟ್ರ್ಯಾಕರ್ ದಾಖಲೆ, ಅಧ್ಯಯನ ವಿಷಯ, ಓದಿನ ಅವಧಿ ಅಥವಾ ಚಿಂತನೆ.",
"stats_activity": "ಚಟುವಟಿಕೆ",
"stats_less": "ಕಡಿಮೆ",
"stats_more": "ಹೆಚ್ಚು",
"stats_day_a11y": "%1$s, %2$d ಕೆಲಸಗಳು ಮುಗಿದಿವೆ",
"stats_map_a11y": "ಚಟುವಟಿಕೆ ನಕ್ಷೆ: %2$d ದಿನಗಳಲ್ಲಿ %1$d ದಿನ ಸಕ್ರಿಯ. ಜೀವನ ಕ್ಯಾಲೆಂಡರ್‌ನಲ್ಲಿ ತೆರೆಯಲು ಒಂದು ದಿನವನ್ನು ಟ್ಯಾಪ್ ಮಾಡಿ.",
"stats_your_areas": "ನಿಮ್ಮ ಕ್ಷೇತ್ರಗಳು",
"stats_area_tasks": "ಕಾರ್ಯಗಳು",
"stats_area_reading": "ಓದು",
"stats_area_journal": "ಚಿಂತನೆ",
"stats_completed": "ನೀವು ಮುಗಿಸಿದ್ದು",
"stats_tile_tasks": "ಮುಗಿದ ಕಾರ್ಯಗಳು",
"stats_tile_study": "ಅಧ್ಯಯನ ಅವಧಿಗಳು",
"stats_tile_topics": "ಕಲಿತ ವಿಷಯಗಳು",
"stats_tile_pages": "ಓದಿದ ಪುಟಗಳು",
"stats_tile_active_minutes": "ಸಕ್ರಿಯ ನಿಮಿಷಗಳು",
"stats_tile_workouts": "ವ್ಯಾಯಾಮಗಳು",
"stats_tile_reflections": "ಚಿಂತನೆಗಳು",
"stats_momentum": "ನಿಮ್ಮ ವೇಗ",
"momentum_rising": "ಹಿಂದಿನ ವಾರಕ್ಕಿಂತ ನೀವು ಹೆಚ್ಚು ನಿರಂತರವಾಗಿ ಬರುತ್ತಿದ್ದೀರಿ: ಕಳೆದ 7 ದಿನಗಳಲ್ಲಿ %1$d ದಿನ ಏನಾದರೂ ಮುಗಿಸಿದ್ದೀರಿ.",
"momentum_steady": "ಈ ವಾರ ನಿಮ್ಮ ಚಟುವಟಿಕೆ ಸ್ಥಿರವಾಗಿದೆ: ಕಳೆದ 7 ದಿನಗಳಲ್ಲಿ %1$d ದಿನ ಏನಾದರೂ ಮುಗಿಸಿದ್ದೀರಿ.",
"momentum_easing": "ಕಳೆದ 7 ದಿನಗಳಲ್ಲಿ %1$d ದಿನ ನೀವು ಏನಾದರೂ ಮುಗಿಸಿದ್ದೀರಿ. ಇಂದು ಒಂದು ಸಣ್ಣ ಹೆಜ್ಜೆ ಎಳೆಯನ್ನು ಮುಂದುವರಿಸುತ್ತದೆ.",
"momentum_started": "ನಿಮ್ಮ ಮೊದಲ %2$d ದಿನಗಳಲ್ಲಿ %1$d ದಿನ ಸಕ್ರಿಯರಾಗಿದ್ದೀರಿ. ನೀವು ಬರುವ ಪ್ರತಿ ದಿನ ನಿಮ್ಮ ಕಥೆಗೆ ಸೇರುತ್ತದೆ.",
"momentum_quiet": "ಶಾಂತ ಅವಧಿ. ಇಂದಿಗೆ ಒಂದು ಸಣ್ಣ ವಿಷಯ ಆರಿಸಿ, ನಿಮ್ಮ ಕಥೆ ಮುಂದುವರಿಯುತ್ತದೆ.",
"stats_milestones": "ವೈಯಕ್ತಿಕ ಮೈಲಿಗಲ್ಲುಗಳು",
"stats_milestones_note": "ಈ ಅವಧಿಯಲ್ಲಿ ನಿಮ್ಮದೇ ಅತ್ಯುತ್ತಮಗಳು. ಬೇರೆ ಯಾರೊಂದಿಗೂ ಹೋಲಿಕೆ ಇಲ್ಲ.",
"record_streak": "ಅತಿ ದೀರ್ಘ ಸಕ್ರಿಯ ಸರಣಿ",
"record_tasks": "ಒಂದೇ ದಿನದಲ್ಲಿ ಹೆಚ್ಚು ಕಾರ್ಯಗಳು",
"record_pages": "ಒಂದು ವಾರದಲ್ಲಿ ಹೆಚ್ಚು ಪುಟಗಳು",
"record_session": "ಅತಿ ದೀರ್ಘ ಅಧ್ಯಯನ ಅಥವಾ ಓದಿನ ಅವಧಿ",
"stats_private": "ನಿಮ್ಮ ಡೇಟಾ ಈ ಸಾಧನದಲ್ಲೇ ಇರುತ್ತದೆ. ಖಾತೆ ಇಲ್ಲ, ಕ್ಲೌಡ್ ಇಲ್ಲ, ಟ್ರ್ಯಾಕಿಂಗ್ ಇಲ್ಲ.",
"stats_empty_title": "ನಿಮ್ಮ ಕಥೆ ಇಲ್ಲಿಂದ ಶುರು",
"stats_empty_body": "ನಿಮ್ಮ ಮೊದಲ ಕಾರ್ಯ ಮುಗಿಸಿ, ಒಂದು ಅಧ್ಯಯನ ಅವಧಿ ಪೂರೈಸಿ, ಕೆಲವು ಪುಟ ಓದಿ ಅಥವಾ ಮೊದಲ ಟ್ರ್ಯಾಕರ್ ರಚಿಸಿ. ಕೈರೋಸ್ ಎರಾ ನಿಮ್ಮ ಪ್ರಗತಿಯ ಇತಿಹಾಸವನ್ನು ಕಟ್ಟಲು ಶುರುಮಾಡುತ್ತದೆ.",
"stats_empty_action": "ಏನನ್ನಾದರೂ ರಚಿಸಿ",
"duration_hm": "%1$dಗಂ %2$dನಿ",
"duration_m": "%1$d ನಿಮಿಷ",

"previous_month": "ಹಿಂದಿನ ತಿಂಗಳು",
"next_month": "ಮುಂದಿನ ತಿಂಗಳು",
"previous_year": "ಹಿಂದಿನ ವರ್ಷ",
"next_year": "ಮುಂದಿನ ವರ್ಷ",
"calendar_view_year": "ವರ್ಷ ನೋಡಿ",
"calendar_view_month": "ತಿಂಗಳು ನೋಡಿ",
"calendar_has_reflection": "ಚಿಂತನೆ ಬರೆಯಲಾಗಿದೆ",
"calendar_so_far": "%1$s ಇಲ್ಲಿಯವರೆಗೆ",
"calendar_future_month": "ಈ ತಿಂಗಳು ಇನ್ನೂ ಬಂದಿಲ್ಲ. ಅದು ಬಂದಾಗ ಅದರ ಕಥೆ ಶುರುವಾಗುತ್ತದೆ.",
"calendar_quiet_month": "ಈ ತಿಂಗಳು ಇನ್ನೂ ಏನೂ ದಾಖಲಾಗಿಲ್ಲ.",
"calendar_todays_story": "ಇಂದಿನ ಕಥೆ",
"calendar_days_story": "ಆ ದಿನದ ಕಥೆ",
"calendar_planned": "ಯೋಜಿತ",
"calendar_nothing_planned": "ಈ ದಿನಕ್ಕೆ ಇನ್ನೂ ಏನೂ ಯೋಜಿಸಿಲ್ಲ.",
"calendar_quiet_day": "ಶಾಂತ ದಿನ. ಏನೂ ದಾಖಲಾಗಿಲ್ಲ.",
"calendar_of_planned": "%2$d ಯೋಜಿತದಲ್ಲಿ %1$s",
"calendar_reflection": "ಚಿಂತನೆ",
"calendar_view_full_day": "ಪೂರ್ಣ ದಿನ ನೋಡಿ",
"calendar_read_journal": "ಜರ್ನಲ್ ಓದಿ",
"calendar_write": "ಚಿಂತನೆ ಬರೆಯಿರಿ",
"calendar_open_day": "ಇಂದು ಪುಟದಲ್ಲಿ ತೆರೆಯಿರಿ",
"previous_activity": "ಹಿಂದಿನ ಚಟುವಟಿಕೆ",
"activity_task_done": "ಕಾರ್ಯ ಮುಗಿದಿದೆ",
"activity_topic_done": "ಅಧ್ಯಯನ ವಿಷಯ ಮುಗಿದಿದೆ",
"activity_reflection": "ಚಿಂತನೆ ಬರೆಯಲಾಗಿದೆ",
"day_plan": "ಯೋಜನೆ",
"day_timeline": "ಸಮಯರೇಖೆ",
"day_during": "ದಿನದಲ್ಲಿ",
})

PLURALS_EN.update({
"active_days": {"one": "%1$d active day", "other": "%1$d active days"},
"active_days_in_year": {"one": "%1$d active day in %2$d", "other": "%1$d active days in %2$d"},
"day_count": {"one": "%1$d day", "other": "%1$d days"},
"days_in_a_row": {"one": "%1$d day in a row", "other": "%1$d days in a row"},
"pages_count": {"one": "%1$d page", "other": "%1$d pages"},
"reading_days": {"one": "%1$d reading day", "other": "%1$d reading days"},
"reading_sessions": {"one": "%1$d reading session", "other": "%1$d reading sessions"},
"reflections": {"one": "%1$d reflection", "other": "%1$d reflections"},
"study_sessions": {"one": "%1$d study session", "other": "%1$d study sessions"},
"study_topics": {"one": "%1$d study topic done", "other": "%1$d study topics done"},
"task_count": {"one": "%1$d task", "other": "%1$d tasks"},
"tasks_completed": {"one": "%1$d task completed", "other": "%1$d tasks completed"},
"tasks_planned": {"one": "%1$d task planned", "other": "%1$d tasks planned"},
"workouts": {"one": "%1$d workout", "other": "%1$d workouts"},
})

PLURALS_KN.update({
"active_days": {"one": "%1$d ಸಕ್ರಿಯ ದಿನ", "other": "%1$d ಸಕ್ರಿಯ ದಿನಗಳು"},
"active_days_in_year": {"one": "%1$d ಸಕ್ರಿಯ ದಿನ (%2$d)", "other": "%1$d ಸಕ್ರಿಯ ದಿನಗಳು (%2$d)"},
"day_count": {"one": "%1$d ದಿನ", "other": "%1$d ದಿನಗಳು"},
"days_in_a_row": {"one": "ಸತತ %1$d ದಿನ", "other": "ಸತತ %1$d ದಿನಗಳು"},
"pages_count": {"one": "%1$d ಪುಟ", "other": "%1$d ಪುಟಗಳು"},
"reading_days": {"one": "%1$d ಓದಿನ ದಿನ", "other": "%1$d ಓದಿನ ದಿನಗಳು"},
"reading_sessions": {"one": "%1$d ಓದಿನ ಅವಧಿ", "other": "%1$d ಓದಿನ ಅವಧಿಗಳು"},
"reflections": {"one": "%1$d ಚಿಂತನೆ", "other": "%1$d ಚಿಂತನೆಗಳು"},
"study_sessions": {"one": "%1$d ಅಧ್ಯಯನ ಅವಧಿ", "other": "%1$d ಅಧ್ಯಯನ ಅವಧಿಗಳು"},
"study_topics": {"one": "%1$d ಅಧ್ಯಯನ ವಿಷಯ ಮುಗಿದಿದೆ", "other": "%1$d ಅಧ್ಯಯನ ವಿಷಯಗಳು ಮುಗಿದಿವೆ"},
"task_count": {"one": "%1$d ಕಾರ್ಯ", "other": "%1$d ಕಾರ್ಯಗಳು"},
"tasks_completed": {"one": "%1$d ಕಾರ್ಯ ಮುಗಿದಿದೆ", "other": "%1$d ಕಾರ್ಯಗಳು ಮುಗಿದಿವೆ"},
"tasks_planned": {"one": "%1$d ಕಾರ್ಯ ಯೋಜಿತ", "other": "%1$d ಕಾರ್ಯಗಳು ಯೋಜಿತ"},
"workouts": {"one": "%1$d ವ್ಯಾಯಾಮ", "other": "%1$d ವ್ಯಾಯಾಮಗಳು"},
})

# ---- 0.5.1 Privacy policy (also rendered to docs/privacy-policy.html by tools/gen_privacy_html.py) ----
# Each section is pp_h_<key> (heading) + pp_b_<key> (body). Body lines starting with "• " are list items.
PRIVACY_SECTIONS = ["summary", "stored", "where", "network", "permissions", "visible", "sharing", "backup", "logs", "control", "children", "changes"]
PRIVACY_CONTACT = "wondersparksmedia@gmail.com"
PRIVACY_UPDATED = {"en": "25 September 2026", "kn": "25 ಸೆಪ್ಟೆಂಬರ್ 2026"}  # keep in step with PolicyUpdated in PrivacyPolicyScreen.kt

EN.update({
"privacy_policy": "Privacy policy",
"privacy_policy_summary": "What the app stores, where, and what it never does",
"pp_updated": "Last updated %1$s",
"pp_intro": "Kairos Era is a planner, tracker, reading log and journal that works entirely on your phone. This policy explains what the app stores, where it is kept and what it never does. In short: your data stays on this device.",
"pp_h_summary": "At a glance",
"pp_b_summary": "• No account and no sign-in.\n• No internet permission, so the app cannot send your data anywhere.\n• No ads, analytics, tracking or crash-reporting services.\n• Nothing is sold or shared with anyone.\n• You can delete your data at any time.",
"pp_h_stored": "What the app stores",
"pp_b_stored": "Only what you enter, plus a few settings the app needs to run:\n• Tasks, subtasks, categories, tags, dates and reminder times.\n• Trackers and their entries, including any study, fitness or health values you choose to log (for example steps, weight, sleep or water).\n• Study plans, topics and daily targets.\n• Books, reading sessions, notes, highlights and insights.\n• Journal reflections and the mood you pick, if you pick one.\n• Settings such as your name (optional), language, theme, Home layout, reminder preferences and favourite quotes.\nThe app also reads the date it was installed on your phone, so Statistics never count days before you started.",
"pp_h_where": "Where it is kept",
"pp_b_where": "Everything is stored in the app's private storage on your phone. Android keeps this storage separate, so other apps cannot read it. On phones with a screen lock, Android also encrypts this storage. Kairos Era does not add a separate layer of encryption on top of Android's.",
"pp_h_network": "No internet, no servers",
"pp_b_network": "Kairos Era does not request the internet permission. There is no account, server, cloud sync, advertising, analytics or crash-reporting service. The developer never receives your data, and the app works the same in airplane mode.",
"pp_h_permissions": "Permissions and why",
"pp_b_permissions": "• Notifications: to show the reminders you set. Asked only when you choose to turn reminders on.\n• Alarms and reminders: so reminders arrive at the exact time you set. Without it, they may arrive a few minutes late.\n• Run at startup: to set your reminders again after the phone restarts.\nThe app does not ask for location, contacts, camera, microphone, photos, files, phone or SMS access. You can change these permissions at any time in Android settings.",
"pp_h_visible": "What others may see on your phone",
"pp_b_visible": "Reminders and widgets show task titles and progress on your home screen and, depending on your Android lock-screen settings, on the lock screen. You can hide sensitive notification content in Android settings, or remove a widget at any time. An optional app lock is planned for a future update.",
"pp_h_sharing": "Sharing",
"pp_b_sharing": "The app shares something only when you tap Share, for example on a quote. Android then shows its share sheet and you choose where it goes. Only the text shown to you is shared.\nIf a future version offers to send a crash report, it will open your email app with the report for you to read first. Nothing is sent unless you send it, and reports will contain technical details only, never your entries.",
"pp_h_backup": "Backups",
"pp_b_backup": "Android's automatic cloud backup and device-to-device transfer are turned off for Kairos Era, so your entries are not copied to Google or to a new phone. This also means that if you uninstall the app, clear its storage or lose your phone, your data cannot be recovered. A backup file that you create and keep yourself is planned for a future update.",
"pp_h_logs": "Technical logs",
"pp_b_logs": "To help fix problems, the app writes short technical messages, such as an event name or an error type, to Android's system log on your phone. These messages never include your tasks, notes, journal text, health values or any other personal text, and other apps cannot read them.",
"pp_h_control": "Your control",
"pp_b_control": "• Edit or delete any item. Deleted items go to Trash, where you can restore them or delete them permanently.\n• Remove the example content from Settings without touching your own data.\n• Delete everything from Android Settings › Apps › Kairos Era › Storage › Clear storage, or by uninstalling the app. Both are permanent.",
"pp_h_children": "Children",
"pp_b_children": "Kairos Era does not collect personal information from anyone, including children, because nothing you enter leaves your phone.",
"pp_h_changes": "Changes to this policy",
"pp_b_changes": "If a future version changes how data is handled, this policy will be updated and the date at the top will change. The policy inside the app always matches the version you have installed.",
"pp_h_contact": "Contact",
"pp_b_contact": "Questions about privacy? Write to %1$s.",
"pp_email_subject": "Kairos Era privacy question",
})

KN.update({
"privacy_policy": "ಗೌಪ್ಯತಾ ನೀತಿ",
"privacy_policy_summary": "ಆ್ಯಪ್ ಏನನ್ನು ಉಳಿಸುತ್ತದೆ, ಎಲ್ಲಿ, ಮತ್ತು ಏನನ್ನು ಎಂದಿಗೂ ಮಾಡುವುದಿಲ್ಲ",
"pp_updated": "ಕೊನೆಯ ಪರಿಷ್ಕರಣೆ %1$s",
"pp_intro": "ಕೈರೋಸ್ ಎರಾ ಸಂಪೂರ್ಣವಾಗಿ ನಿಮ್ಮ ಫೋನ್‌ನಲ್ಲೇ ಕೆಲಸ ಮಾಡುವ ಯೋಜಕ, ಟ್ರ್ಯಾಕರ್, ಓದಿನ ದಾಖಲೆ ಮತ್ತು ದಿನಚರಿ. ಆ್ಯಪ್ ಏನನ್ನು ಉಳಿಸುತ್ತದೆ, ಅದು ಎಲ್ಲಿರುತ್ತದೆ ಮತ್ತು ಏನನ್ನು ಎಂದಿಗೂ ಮಾಡುವುದಿಲ್ಲ ಎಂಬುದನ್ನು ಈ ನೀತಿ ವಿವರಿಸುತ್ತದೆ. ಸಂಕ್ಷಿಪ್ತವಾಗಿ: ನಿಮ್ಮ ಮಾಹಿತಿ ಈ ಸಾಧನದಲ್ಲೇ ಇರುತ್ತದೆ.",
"pp_h_summary": "ಒಂದು ನೋಟದಲ್ಲಿ",
"pp_b_summary": "• ಯಾವುದೇ ಖಾತೆ ಅಥವಾ ಸೈನ್-ಇನ್ ಇಲ್ಲ.\n• ಇಂಟರ್ನೆಟ್ ಅನುಮತಿ ಇಲ್ಲ, ಆದ್ದರಿಂದ ಆ್ಯಪ್ ನಿಮ್ಮ ಮಾಹಿತಿಯನ್ನು ಎಲ್ಲಿಗೂ ಕಳುಹಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ.\n• ಜಾಹೀರಾತು, ವಿಶ್ಲೇಷಣೆ, ಟ್ರ್ಯಾಕಿಂಗ್ ಅಥವಾ ಕ್ರ್ಯಾಶ್-ವರದಿ ಸೇವೆಗಳಿಲ್ಲ.\n• ಯಾವುದನ್ನೂ ಮಾರಾಟ ಮಾಡುವುದಿಲ್ಲ ಅಥವಾ ಯಾರೊಂದಿಗೂ ಹಂಚುವುದಿಲ್ಲ.\n• ನಿಮ್ಮ ಮಾಹಿತಿಯನ್ನು ಯಾವಾಗ ಬೇಕಾದರೂ ಅಳಿಸಬಹುದು.",
"pp_h_stored": "ಆ್ಯಪ್ ಏನನ್ನು ಉಳಿಸುತ್ತದೆ",
"pp_b_stored": "ನೀವು ನಮೂದಿಸುವುದನ್ನು ಮಾತ್ರ, ಜೊತೆಗೆ ಆ್ಯಪ್ ನಡೆಯಲು ಬೇಕಾದ ಕೆಲವು ಸೆಟ್ಟಿಂಗ್‌ಗಳು:\n• ಕಾರ್ಯಗಳು, ಉಪಕಾರ್ಯಗಳು, ವರ್ಗಗಳು, ಟ್ಯಾಗ್‌ಗಳು, ದಿನಾಂಕಗಳು ಮತ್ತು ಜ್ಞಾಪನೆಯ ಸಮಯಗಳು.\n• ಟ್ರ್ಯಾಕರ್‌ಗಳು ಮತ್ತು ಅವುಗಳ ನಮೂದುಗಳು, ನೀವು ದಾಖಲಿಸಲು ಆಯ್ಕೆ ಮಾಡುವ ಅಧ್ಯಯನ, ಫಿಟ್‌ನೆಸ್ ಅಥವಾ ಆರೋಗ್ಯ ಮೌಲ್ಯಗಳೂ ಸೇರಿ (ಉದಾಹರಣೆಗೆ ಹೆಜ್ಜೆಗಳು, ತೂಕ, ನಿದ್ರೆ ಅಥವಾ ನೀರು).\n• ಅಧ್ಯಯನ ಯೋಜನೆಗಳು, ವಿಷಯಗಳು ಮತ್ತು ದೈನಂದಿನ ಗುರಿಗಳು.\n• ಪುಸ್ತಕಗಳು, ಓದಿನ ಅವಧಿಗಳು, ಟಿಪ್ಪಣಿಗಳು, ಮುಖ್ಯಾಂಶಗಳು ಮತ್ತು ಒಳನೋಟಗಳು.\n• ದಿನಚರಿಯ ಚಿಂತನೆಗಳು ಮತ್ತು ನೀವು ಆರಿಸಿದರೆ ನಿಮ್ಮ ಮನಸ್ಥಿತಿ.\n• ನಿಮ್ಮ ಹೆಸರು (ಐಚ್ಛಿಕ), ಭಾಷೆ, ಥೀಮ್, ಮುಖಪುಟದ ವಿನ್ಯಾಸ, ಜ್ಞಾಪನೆಯ ಆದ್ಯತೆಗಳು ಮತ್ತು ಮೆಚ್ಚಿನ ಉಲ್ಲೇಖಗಳಂತಹ ಸೆಟ್ಟಿಂಗ್‌ಗಳು.\nನೀವು ಪ್ರಾರಂಭಿಸುವ ಮೊದಲಿನ ದಿನಗಳನ್ನು ಅಂಕಿಅಂಶಗಳು ಎಣಿಸದಿರಲು, ಆ್ಯಪ್ ನಿಮ್ಮ ಫೋನ್‌ನಲ್ಲಿ ಸ್ಥಾಪಿಸಿದ ದಿನಾಂಕವನ್ನೂ ಓದುತ್ತದೆ.",
"pp_h_where": "ಅದು ಎಲ್ಲಿರುತ್ತದೆ",
"pp_b_where": "ಎಲ್ಲವೂ ನಿಮ್ಮ ಫೋನ್‌ನಲ್ಲಿ ಆ್ಯಪ್‌ನ ಖಾಸಗಿ ಸಂಗ್ರಹದಲ್ಲಿ ಉಳಿಯುತ್ತದೆ. Android ಈ ಸಂಗ್ರಹವನ್ನು ಪ್ರತ್ಯೇಕವಾಗಿಡುತ್ತದೆ, ಆದ್ದರಿಂದ ಇತರ ಆ್ಯಪ್‌ಗಳು ಇದನ್ನು ಓದಲು ಸಾಧ್ಯವಿಲ್ಲ. ಸ್ಕ್ರೀನ್ ಲಾಕ್ ಇರುವ ಫೋನ್‌ಗಳಲ್ಲಿ Android ಈ ಸಂಗ್ರಹವನ್ನು ಎನ್‌ಕ್ರಿಪ್ಟ್ ಕೂಡ ಮಾಡುತ್ತದೆ. ಕೈರೋಸ್ ಎರಾ Android ನ ಎನ್‌ಕ್ರಿಪ್ಶನ್ ಮೇಲೆ ಪ್ರತ್ಯೇಕ ಎನ್‌ಕ್ರಿಪ್ಶನ್ ಪದರವನ್ನು ಸೇರಿಸುವುದಿಲ್ಲ.",
"pp_h_network": "ಇಂಟರ್ನೆಟ್ ಇಲ್ಲ, ಸರ್ವರ್ ಇಲ್ಲ",
"pp_b_network": "ಕೈರೋಸ್ ಎರಾ ಇಂಟರ್ನೆಟ್ ಅನುಮತಿಯನ್ನು ಕೇಳುವುದಿಲ್ಲ. ಯಾವುದೇ ಖಾತೆ, ಸರ್ವರ್, ಕ್ಲೌಡ್ ಸಿಂಕ್, ಜಾಹೀರಾತು, ವಿಶ್ಲೇಷಣೆ ಅಥವಾ ಕ್ರ್ಯಾಶ್-ವರದಿ ಸೇವೆ ಇಲ್ಲ. ಡೆವಲಪರ್‌ಗೆ ನಿಮ್ಮ ಮಾಹಿತಿ ಎಂದಿಗೂ ತಲುಪುವುದಿಲ್ಲ, ಮತ್ತು ಏರ್‌ಪ್ಲೇನ್ ಮೋಡ್‌ನಲ್ಲೂ ಆ್ಯಪ್ ಹಾಗೆಯೇ ಕೆಲಸ ಮಾಡುತ್ತದೆ.",
"pp_h_permissions": "ಅನುಮತಿಗಳು ಮತ್ತು ಕಾರಣಗಳು",
"pp_b_permissions": "• ಅಧಿಸೂಚನೆಗಳು: ನೀವು ಹೊಂದಿಸಿದ ಜ್ಞಾಪನೆಗಳನ್ನು ತೋರಿಸಲು. ನೀವು ಜ್ಞಾಪನೆಗಳನ್ನು ಆನ್ ಮಾಡಲು ಆರಿಸಿದಾಗ ಮಾತ್ರ ಕೇಳಲಾಗುತ್ತದೆ.\n• ಅಲಾರಾಂಗಳು ಮತ್ತು ಜ್ಞಾಪನೆಗಳು: ನೀವು ಹೊಂದಿಸಿದ ನಿಖರ ಸಮಯಕ್ಕೆ ಜ್ಞಾಪನೆಗಳು ಬರಲು. ಇದಿಲ್ಲದಿದ್ದರೆ ಕೆಲವು ನಿಮಿಷ ತಡವಾಗಿ ಬರಬಹುದು.\n• ಆರಂಭದಲ್ಲಿ ಚಲಾಯಿಸುವಿಕೆ: ಫೋನ್ ಮರುಪ್ರಾರಂಭವಾದ ನಂತರ ನಿಮ್ಮ ಜ್ಞಾಪನೆಗಳನ್ನು ಮತ್ತೆ ಹೊಂದಿಸಲು.\nಆ್ಯಪ್ ಸ್ಥಳ, ಸಂಪರ್ಕಗಳು, ಕ್ಯಾಮೆರಾ, ಮೈಕ್ರೊಫೋನ್, ಫೋಟೋಗಳು, ಫೈಲ್‌ಗಳು, ಫೋನ್ ಅಥವಾ SMS ಪ್ರವೇಶವನ್ನು ಕೇಳುವುದಿಲ್ಲ. ಈ ಅನುಮತಿಗಳನ್ನು Android ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಯಾವಾಗ ಬೇಕಾದರೂ ಬದಲಿಸಬಹುದು.",
"pp_h_visible": "ನಿಮ್ಮ ಫೋನ್‌ನಲ್ಲಿ ಇತರರಿಗೆ ಏನು ಕಾಣಬಹುದು",
"pp_b_visible": "ಜ್ಞಾಪನೆಗಳು ಮತ್ತು ವಿಜೆಟ್‌ಗಳು ಕಾರ್ಯಗಳ ಶೀರ್ಷಿಕೆ ಮತ್ತು ಪ್ರಗತಿಯನ್ನು ನಿಮ್ಮ ಹೋಮ್ ಸ್ಕ್ರೀನ್‌ನಲ್ಲಿ ಹಾಗೂ ನಿಮ್ಮ Android ಲಾಕ್-ಸ್ಕ್ರೀನ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಅವಲಂಬಿಸಿ ಲಾಕ್ ಸ್ಕ್ರೀನ್‌ನಲ್ಲಿ ತೋರಿಸುತ್ತವೆ. ಸೂಕ್ಷ್ಮ ಅಧಿಸೂಚನೆ ವಿಷಯವನ್ನು Android ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಮರೆಮಾಡಬಹುದು ಅಥವಾ ವಿಜೆಟ್ ಅನ್ನು ಯಾವಾಗ ಬೇಕಾದರೂ ತೆಗೆಯಬಹುದು. ಐಚ್ಛಿಕ ಆ್ಯಪ್ ಲಾಕ್ ಮುಂದಿನ ಅಪ್‌ಡೇಟ್‌ನಲ್ಲಿ ಬರಲಿದೆ.",
"pp_h_sharing": "ಹಂಚಿಕೆ",
"pp_b_sharing": "ನೀವು ಹಂಚಿಕೊಳ್ಳಿ ಒತ್ತಿದಾಗ ಮಾತ್ರ ಆ್ಯಪ್ ಏನನ್ನಾದರೂ ಹಂಚುತ್ತದೆ, ಉದಾಹರಣೆಗೆ ಒಂದು ಉಲ್ಲೇಖ. ಆಗ Android ತನ್ನ ಹಂಚಿಕೆ ಪಟ್ಟಿಯನ್ನು ತೋರಿಸುತ್ತದೆ ಮತ್ತು ಅದು ಎಲ್ಲಿಗೆ ಹೋಗಬೇಕು ಎಂದು ನೀವೇ ಆರಿಸುತ್ತೀರಿ. ನಿಮಗೆ ಕಾಣುವ ಪಠ್ಯ ಮಾತ್ರ ಹಂಚಲಾಗುತ್ತದೆ.\nಮುಂದಿನ ಆವೃತ್ತಿಯೊಂದು ಕ್ರ್ಯಾಶ್ ವರದಿ ಕಳುಹಿಸಲು ಕೇಳಿದರೆ, ಅದು ವರದಿಯೊಂದಿಗೆ ನಿಮ್ಮ ಇಮೇಲ್ ಆ್ಯಪ್ ಅನ್ನು ತೆರೆಯುತ್ತದೆ, ಮೊದಲು ನೀವೇ ಓದಬಹುದು. ನೀವು ಕಳುಹಿಸದ ಹೊರತು ಏನೂ ಹೋಗುವುದಿಲ್ಲ, ಮತ್ತು ವರದಿಗಳಲ್ಲಿ ತಾಂತ್ರಿಕ ವಿವರಗಳು ಮಾತ್ರ ಇರುತ್ತವೆ, ನಿಮ್ಮ ನಮೂದುಗಳು ಎಂದಿಗೂ ಇರುವುದಿಲ್ಲ.",
"pp_h_backup": "ಬ್ಯಾಕಪ್‌ಗಳು",
"pp_b_backup": "ಕೈರೋಸ್ ಎರಾಗೆ Android ನ ಸ್ವಯಂ ಕ್ಲೌಡ್ ಬ್ಯಾಕಪ್ ಮತ್ತು ಸಾಧನದಿಂದ ಸಾಧನಕ್ಕೆ ವರ್ಗಾವಣೆ ಆಫ್ ಆಗಿದೆ, ಆದ್ದರಿಂದ ನಿಮ್ಮ ನಮೂದುಗಳು Google ಗೆ ಅಥವಾ ಹೊಸ ಫೋನ್‌ಗೆ ನಕಲಾಗುವುದಿಲ್ಲ. ಇದರರ್ಥ, ನೀವು ಆ್ಯಪ್ ಅನ್ನು ಅನ್‌ಇನ್‌ಸ್ಟಾಲ್ ಮಾಡಿದರೆ, ಅದರ ಸಂಗ್ರಹವನ್ನು ತೆರವುಗೊಳಿಸಿದರೆ ಅಥವಾ ಫೋನ್ ಕಳೆದುಕೊಂಡರೆ, ನಿಮ್ಮ ಮಾಹಿತಿಯನ್ನು ಮರಳಿ ಪಡೆಯಲು ಸಾಧ್ಯವಿಲ್ಲ. ನೀವೇ ರಚಿಸಿ ಇಟ್ಟುಕೊಳ್ಳುವ ಬ್ಯಾಕಪ್ ಫೈಲ್ ಮುಂದಿನ ಅಪ್‌ಡೇಟ್‌ನಲ್ಲಿ ಬರಲಿದೆ.",
"pp_h_logs": "ತಾಂತ್ರಿಕ ಲಾಗ್‌ಗಳು",
"pp_b_logs": "ಸಮಸ್ಯೆಗಳನ್ನು ಸರಿಪಡಿಸಲು, ಆ್ಯಪ್ ಘಟನೆಯ ಹೆಸರು ಅಥವಾ ದೋಷದ ಪ್ರಕಾರದಂತಹ ಚಿಕ್ಕ ತಾಂತ್ರಿಕ ಸಂದೇಶಗಳನ್ನು ನಿಮ್ಮ ಫೋನ್‌ನ Android ಸಿಸ್ಟಮ್ ಲಾಗ್‌ಗೆ ಬರೆಯುತ್ತದೆ. ಈ ಸಂದೇಶಗಳಲ್ಲಿ ನಿಮ್ಮ ಕಾರ್ಯಗಳು, ಟಿಪ್ಪಣಿಗಳು, ದಿನಚರಿಯ ಪಠ್ಯ, ಆರೋಗ್ಯ ಮೌಲ್ಯಗಳು ಅಥವಾ ಇತರ ಯಾವುದೇ ವೈಯಕ್ತಿಕ ಪಠ್ಯ ಎಂದಿಗೂ ಇರುವುದಿಲ್ಲ, ಮತ್ತು ಇತರ ಆ್ಯಪ್‌ಗಳು ಅವುಗಳನ್ನು ಓದಲು ಸಾಧ್ಯವಿಲ್ಲ.",
"pp_h_control": "ನಿಮ್ಮ ನಿಯಂತ್ರಣ",
"pp_b_control": "• ಯಾವುದೇ ಅಂಶವನ್ನು ಸಂಪಾದಿಸಿ ಅಥವಾ ಅಳಿಸಿ. ಅಳಿಸಿದವು ಕಸದ ಬುಟ್ಟಿಗೆ ಹೋಗುತ್ತವೆ, ಅಲ್ಲಿಂದ ಮರಳಿ ಪಡೆಯಬಹುದು ಅಥವಾ ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಬಹುದು.\n• ನಿಮ್ಮ ಸ್ವಂತ ಮಾಹಿತಿಗೆ ತೊಂದರೆಯಾಗದಂತೆ ಉದಾಹರಣೆ ವಿಷಯವನ್ನು ಸೆಟ್ಟಿಂಗ್‌ಗಳಿಂದ ತೆಗೆಯಿರಿ.\n• Android ಸೆಟ್ಟಿಂಗ್‌ಗಳು › ಆ್ಯಪ್‌ಗಳು › ಕೈರೋಸ್ ಎರಾ › ಸಂಗ್ರಹ › ಸಂಗ್ರಹ ತೆರವುಗೊಳಿಸಿ ಮೂಲಕ ಅಥವಾ ಆ್ಯಪ್ ಅನ್‌ಇನ್‌ಸ್ಟಾಲ್ ಮಾಡುವ ಮೂಲಕ ಎಲ್ಲವನ್ನೂ ಅಳಿಸಿ. ಎರಡೂ ಶಾಶ್ವತ.",
"pp_h_children": "ಮಕ್ಕಳು",
"pp_b_children": "ನೀವು ನಮೂದಿಸುವ ಯಾವುದೂ ನಿಮ್ಮ ಫೋನ್ ಬಿಟ್ಟು ಹೋಗದ ಕಾರಣ, ಕೈರೋಸ್ ಎರಾ ಮಕ್ಕಳೂ ಸೇರಿದಂತೆ ಯಾರಿಂದಲೂ ವೈಯಕ್ತಿಕ ಮಾಹಿತಿಯನ್ನು ಸಂಗ್ರಹಿಸುವುದಿಲ್ಲ.",
"pp_h_changes": "ಈ ನೀತಿಯಲ್ಲಿ ಬದಲಾವಣೆಗಳು",
"pp_b_changes": "ಮುಂದಿನ ಆವೃತ್ತಿಯೊಂದು ಮಾಹಿತಿಯನ್ನು ನಿರ್ವಹಿಸುವ ರೀತಿಯನ್ನು ಬದಲಿಸಿದರೆ, ಈ ನೀತಿಯನ್ನು ಪರಿಷ್ಕರಿಸಲಾಗುತ್ತದೆ ಮತ್ತು ಮೇಲಿನ ದಿನಾಂಕ ಬದಲಾಗುತ್ತದೆ. ಆ್ಯಪ್‌ನೊಳಗಿನ ನೀತಿ ಯಾವಾಗಲೂ ನೀವು ಸ್ಥಾಪಿಸಿರುವ ಆವೃತ್ತಿಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ.",
"pp_h_contact": "ಸಂಪರ್ಕ",
"pp_b_contact": "ಗೌಪ್ಯತೆಯ ಬಗ್ಗೆ ಪ್ರಶ್ನೆಗಳಿವೆಯೇ? %1$s ಗೆ ಬರೆಯಿರಿ.",
"pp_email_subject": "ಕೈರೋಸ್ ಎರಾ ಗೌಪ್ಯತೆ ಪ್ರಶ್ನೆ",
})
