# Source of truth for UI text in English (en) and Kannada (kn).
# Run `python3 tools/gen_strings.py` to regenerate app/src/main/res/values*/strings.xml.
EN = {
"app_name": "Kairos Era",
"app_name_display": "KAIROS ERA",
"tagline": "RIGHT TIME. A BETTER YOU.",
"nav_home": "Home", "nav_today": "Today", "nav_track": "Track", "nav_read": "Read", "nav_more": "More",
"greeting_morning": "Good morning", "greeting_afternoon": "Good afternoon", "greeting_evening": "Good evening", "greeting_night": "Good night",
"home_subtitle": "Let's make today count.",
"home_customize": "Customize Home", "home_customize_summary": "Choose which cards appear on Home and in what order.",
"home_today_progress": "Today's progress", "home_tasks": "Tasks", "home_tasks_done": "%1$d / %2$d completed",
"home_progress_a11y": "Today's progress: %1$d of %2$d tasks completed",
"home_nothing_planned": "Nothing planned yet.", "home_all_done": "Everything planned is done.", "home_remaining": "%1$d left today",
"home_next_up": "Next up", "home_next_empty": "Your day is open. Add one useful thing.", "home_next_clear": "Nothing left for now. Well done.",
"home_daily_motivation": "Daily motivation", "home_trackers": "Trackers",
"home_trackers_soon": "Custom trackers for study, fitness, habits and anything else arrive in the next update.",
"home_open_today": "Open today's plan",
"quote_action": "Today: %1$s", "quote_favorite": "Save quote to favorites", "quote_unfavorite": "Remove quote from favorites",
"all_day": "All day", "all_day_short": "Any time",
"quick_add_title": "What do you want to add?", "quick_add_soon_note": "Trackers, books, journal and study arrive in the next updates.",
"quick_add_task": "Task", "quick_add_tracker": "Tracker", "quick_add_book": "Book", "quick_add_journal": "Journal", "quick_add_study": "Study",
"yesterday": "Yesterday", "today": "Today", "tomorrow": "Tomorrow",
"mode_day": "Day", "mode_week": "Week", "mode_month": "Month",
"previous": "Previous", "next": "Next", "pick_date": "Pick a date",
"day_empty_title": "A clear day", "day_empty_body": "Nothing is planned for this day. Tap + to add a task.",
"week_day_free": "Free", "month_legend": "A filled green dot means everything planned was done. An orange dot means tasks are planned; it gets stronger as more are done.",
"month_cell_a11y": "Day %1$d, %2$d of %3$d done",
"subtasks_count": "%1$d/%2$d steps", "skipped": "Moved", "example_badge": "Example", "repeats": "Repeats", "has_reminder": "Has a reminder",
"edit": "Edit", "move_to_trash": "Move to Trash", "task_moved_to_trash": "Moved to Trash", "undo": "Undo",
"priority_none": "None", "priority_low": "Low", "priority_medium": "Medium", "priority_high": "High",
"new_task": "New task", "edit_task": "Edit task", "save": "Save", "close": "Close", "cancel": "Cancel", "ok": "OK", "back": "Back", "clear": "Clear",
"retry": "Try again", "optional": "Optional",
"field_title": "Title", "field_description": "Description", "field_notes": "Notes", "field_tags": "Tags", "field_tags_hint": "Separate with commas",
"section_when": "When", "section_repeat": "Repeat", "section_reminders": "Reminders", "section_priority": "Priority", "section_category": "Category", "section_subtasks": "Steps",
"starts_at": "Starts %1$s", "ends_at": "Ends %1$s", "add_end_time": "Add end time", "remove_end_time": "Remove end time",
"repeat_none": "Once", "repeat_daily": "Daily", "repeat_weekdays": "Weekdays", "repeat_weekly": "Weekly", "repeat_monthly": "Monthly", "repeat_yearly": "Yearly",
"repeat_every": "Every %1$d", "repeat_until": "Until %1$s", "repeat_forever": "No end date",
"add_reminder": "Add reminder", "remove_reminder": "Remove reminder", "reminder_at_start": "At start time", "reminder_before": "%1$d min before",
"reminder_custom_time": "At a specific time…", "reminder_at": "At %1$s", "reminder_persistent": "Keep until I act",
"add_subtask": "Add a step", "remove_subtask": "Remove step",
"example_note": "This is an example task. You can edit it or remove all examples in Settings.",
"error_title_empty": "Give the task a title.", "error_title_long": "Keep the title under %1$d characters.",
"error_end_before_start": "The end time is before the start time.", "error_reminder_needs_time": "\"Before start\" reminders need a start time.",
"error_too_many_reminders": "Up to %1$d reminders per task.",
"error_title": "Something went wrong", "error_body": "Your data is safe. Please try again.", "error_save_body": "The task could not be saved. Nothing was lost; please try again.",
"error_action_failed": "That didn't work. Please try again.",
"task_missing": "This task no longer exists", "task_missing_body": "It may have been deleted or moved to Trash.",
"trash_confirm_body": "The task moves to Trash. You can restore it from More > Trash.",
"reschedule_title": "Reschedule", "reschedule_recurring_note": "Only this occurrence moves. The repeating plan stays as it is.",
"action_done": "Done", "action_snooze": "Snooze", "action_reschedule": "Reschedule",
"reminder_label": "Task", "reminder_all_day": "Today", "reminder_public_title": "Kairos Era reminder",
"channel_group_reminders": "Task reminders", "channel_default": "Reminders (default sound)", "channel_general": "General",
"channel_reminders_description": "Reminders for tasks you scheduled.",
"sound_default": "Default", "sound_kairos_bell": "Kairos Bell", "sound_soft_chime": "Soft Chime", "sound_focus": "Focus", "sound_silent": "Silent",
"track_soon_title": "Trackers are coming next", "track_soon_body": "Build any tracker you like: study topics, workouts, sleep, water, habits or projects, all on one engine. This arrives in the next update.",
"read_soon_title": "Reading is coming next", "read_soon_body": "Track books and pages, and capture why you started, what you learned and what you applied. This arrives in the next update.",
"settings": "Settings", "settings_summary": "Language, appearance, notifications, sounds", "calendar": "Calendar", "calendar_summary": "Month view of your plan",
"trash": "Trash", "trash_summary": "Restore recently deleted tasks", "privacy": "Privacy", "privacy_summary": "Your data stays on this device",
"about": "About", "about_summary": "Kairos Era and what it stands for", "coming_next": "Coming next", "soon": "In a coming update",
"journal": "Journal", "statistics": "Statistics", "backup": "Backup", "diagnostics": "Diagnostics",
"settings_general": "General", "settings_language": "Language", "language_system": "Phone language", "language_english": "English", "language_kannada": "ಕನ್ನಡ",
"settings_appearance": "Appearance", "theme_system": "System", "theme_light": "Light", "theme_dark": "Dark",
"dynamic_color": "Wallpaper colors", "dynamic_color_summary": "Use colors from your wallpaper instead of the Kairos palette.",
"settings_notifications": "Notifications", "notif_permission": "Notifications", "status_allowed": "Allowed", "status_off": "Off", "allow": "Allow",
"notif_permission_off_body": "Reminders can't appear until notifications are allowed. Everything else works normally.",
"exact_alarms": "On-time reminders", "exact_alarms_off_body": "Without this, Android may deliver reminders a few minutes late to save battery.",
"open_settings": "Open settings", "battery_title": "Battery optimization",
"battery_body": "Some phones stop apps in the background. If reminders arrive late, allow Kairos Era to run without restrictions.",
"test_notification": "Send a test notification", "test_notification_summary": "Check sound and appearance.",
"test_notification_title": "Kairos Era", "test_notification_text": "Notifications are working.",
"settings_sounds": "Sounds", "default_sound": "Default sound for new reminders",
"sound_channel_note": "Android lets you change each sound's volume, vibration and importance in system settings. Your choices there are respected.",
"open_sound_settings": "Open notification settings",
"default_persistent": "Keep reminders until I act", "default_persistent_summary": "New reminders stay in the notification shade until you tap Done, Snooze or Reschedule.",
"snooze_length": "Snooze length", "minutes_short": "%1$d min",
"settings_data": "Data", "add_examples": "Add example content", "add_examples_summary": "A few sample tasks so you can see how things look.",
"remove_examples": "Remove examples", "remove_examples_summary": "Moves all example tasks to Trash.", "remove_examples_confirm": "Move all example tasks to Trash? You can restore them later.",
"settings_footer": "Kairos Era works fully offline. It has no account, no cloud sync, no analytics and no ads.",
"move_up": "Move up", "move_down": "Move down",
"trash_empty_title": "Trash is empty", "trash_empty_body": "Deleted tasks wait here until you restore them or delete them forever.",
"trash_explainer": "Items stay in Trash until you choose. Nothing is removed automatically.",
"restore": "Restore", "delete_forever": "Delete forever", "delete_forever_title": "Delete forever?",
"delete_forever_body": "\"%1$s\" will be permanently deleted. This can't be undone.", "deleted_on": "Deleted %1$s",
"privacy_headline": "Your data stays on this device.",
"privacy_point_device": "Everything you write (tasks, notes, reminders) is stored only in this app's private storage on your phone.",
"privacy_point_account": "There is no account and no sign-in.",
"privacy_point_cloud": "There is no cloud sync and no server. Kairos Era never uploads your data.",
"privacy_point_network": "The app does not even request internet access, so it works the same in airplane mode.",
"privacy_point_storage": "Other apps cannot read this app's private storage.",
"privacy_point_logs": "Diagnostic logs never contain your task titles, notes or other personal text.",
"privacy_point_lock": "An optional app lock using your phone's fingerprint, face or screen lock is coming in a future update.",
"privacy_point_backup": "Local backup files you control are coming in a future update. Android's automatic cloud backup is turned off for this app.",
"privacy_point_diagnostics": "If the app ever crashes, you will be asked before any report is shared, and it will contain no personal data.",
"about_philosophy": "Plan your day. Learn something. Move your body. Read something meaningful. Reflect. Repeat.",
"about_meaning": "Kairos is the Greek idea of the right, opportune moment. The emblem is a path moving toward a rising sun: a new day, steady progress, and growth.",
"about_version": "Version %1$s",
"onboarding_welcome": "Your time is yours.", "onboarding_private": "Private: only you can see your plans.", "onboarding_local": "Local: everything is stored on this phone.",
"onboarding_no_account": "No account, no sign-in.", "onboarding_no_cloud": "No cloud sync, no tracking, no ads.",
"onboarding_begin": "Begin", "onboarding_about_you": "A little about you", "onboarding_name_label": "Name or nickname",
"onboarding_focus": "What do you want to focus on?", "focus_learning": "Learning", "focus_health": "Health", "focus_reading": "Reading", "focus_work": "Work",
"focus_personal": "Personal", "focus_custom": "Something else",
"onboarding_first_task": "One thing to do today", "onboarding_first_task_hint": "Optional. You can add more later.",
"onboarding_examples": "Show example tasks (you can remove them anytime)",
"onboarding_reminders_title": "Reminders", "onboarding_reminders_body": "Kairos Era can remind you when a task is due. Notifications are the only permission it asks for, and you can change this anytime.",
"onboarding_allow_reminders": "Allow reminders", "onboarding_not_now": "Not now",
"sample_java": "Java: Collections", "sample_java_1": "List and ArrayList", "sample_java_2": "HashMap internals", "sample_java_3": "Solve 3 problems",
"sample_walk": "Morning walk", "sample_project": "Project work", "sample_workout": "Workout", "sample_read": "Read 20 pages", "sample_reflection": "Daily reflection",
}

KN = {
"app_name": "ಕೈರೋಸ್ ಎರಾ",
"app_name_display": "KAIROS ERA",
"tagline": "ಸರಿಯಾದ ಸಮಯ. ಉತ್ತಮ ನೀವು.",
"nav_home": "ಮುಖಪುಟ", "nav_today": "ಇಂದು", "nav_track": "ಟ್ರ್ಯಾಕ್", "nav_read": "ಓದು", "nav_more": "ಇನ್ನಷ್ಟು",
"greeting_morning": "ಶುಭೋದಯ", "greeting_afternoon": "ಶುಭ ಮಧ್ಯಾಹ್ನ", "greeting_evening": "ಶುಭ ಸಂಜೆ", "greeting_night": "ಶುಭ ರಾತ್ರಿ",
"home_subtitle": "ಇಂದಿನ ದಿನವನ್ನು ಅರ್ಥಪೂರ್ಣವಾಗಿಸೋಣ.",
"home_customize": "ಮುಖಪುಟ ಹೊಂದಿಸಿ", "home_customize_summary": "ಮುಖಪುಟದಲ್ಲಿ ಯಾವ ಕಾರ್ಡ್‌ಗಳು ಯಾವ ಕ್ರಮದಲ್ಲಿ ಕಾಣಬೇಕು ಎಂದು ಆಯ್ಕೆಮಾಡಿ.",
"home_today_progress": "ಇಂದಿನ ಪ್ರಗತಿ", "home_tasks": "ಕಾರ್ಯಗಳು", "home_tasks_done": "%1$d / %2$d ಪೂರ್ಣಗೊಂಡಿವೆ",
"home_progress_a11y": "ಇಂದಿನ ಪ್ರಗತಿ: %2$d ಕಾರ್ಯಗಳಲ್ಲಿ %1$d ಪೂರ್ಣಗೊಂಡಿವೆ",
"home_nothing_planned": "ಇನ್ನೂ ಏನೂ ಯೋಜಿಸಿಲ್ಲ.", "home_all_done": "ಯೋಜಿಸಿದ್ದೆಲ್ಲವೂ ಪೂರ್ಣಗೊಂಡಿದೆ.", "home_remaining": "ಇಂದು ಇನ್ನೂ %1$d ಬಾಕಿ",
"home_next_up": "ಮುಂದಿನದು", "home_next_empty": "ನಿಮ್ಮ ದಿನ ಖಾಲಿಯಿದೆ. ಒಂದು ಉಪಯುಕ್ತ ಕೆಲಸ ಸೇರಿಸಿ.", "home_next_clear": "ಸದ್ಯಕ್ಕೆ ಏನೂ ಬಾಕಿ ಇಲ್ಲ. ಚೆನ್ನಾಗಿದೆ.",
"home_daily_motivation": "ದಿನದ ಪ್ರೇರಣೆ", "home_trackers": "ಟ್ರ್ಯಾಕರ್‌ಗಳು",
"home_trackers_soon": "ಅಧ್ಯಯನ, ವ್ಯಾಯಾಮ, ಅಭ್ಯಾಸಗಳು ಮತ್ತು ಇನ್ನಾವುದಕ್ಕೂ ನಿಮ್ಮದೇ ಟ್ರ್ಯಾಕರ್‌ಗಳು ಮುಂದಿನ ಅಪ್‌ಡೇಟ್‌ನಲ್ಲಿ ಬರಲಿವೆ.",
"home_open_today": "ಇಂದಿನ ಯೋಜನೆ ತೆರೆಯಿರಿ",
"quote_action": "ಇಂದು: %1$s", "quote_favorite": "ಉಲ್ಲೇಖವನ್ನು ಮೆಚ್ಚಿನವುಗಳಿಗೆ ಸೇರಿಸಿ", "quote_unfavorite": "ಉಲ್ಲೇಖವನ್ನು ಮೆಚ್ಚಿನವುಗಳಿಂದ ತೆಗೆಯಿರಿ",
"all_day": "ಇಡೀ ದಿನ", "all_day_short": "ಯಾವಾಗ ಬೇಕಾದರೂ",
"quick_add_title": "ಏನನ್ನು ಸೇರಿಸಲು ಬಯಸುವಿರಿ?", "quick_add_soon_note": "ಟ್ರ್ಯಾಕರ್, ಪುಸ್ತಕ, ದಿನಚರಿ ಮತ್ತು ಅಧ್ಯಯನ ಮುಂದಿನ ಅಪ್‌ಡೇಟ್‌ಗಳಲ್ಲಿ ಬರಲಿವೆ.",
"quick_add_task": "ಕಾರ್ಯ", "quick_add_tracker": "ಟ್ರ್ಯಾಕರ್", "quick_add_book": "ಪುಸ್ತಕ", "quick_add_journal": "ದಿನಚರಿ", "quick_add_study": "ಅಧ್ಯಯನ",
"yesterday": "ನಿನ್ನೆ", "today": "ಇಂದು", "tomorrow": "ನಾಳೆ",
"mode_day": "ದಿನ", "mode_week": "ವಾರ", "mode_month": "ತಿಂಗಳು",
"previous": "ಹಿಂದಿನದು", "next": "ಮುಂದೆ", "pick_date": "ದಿನಾಂಕ ಆರಿಸಿ",
"day_empty_title": "ಖಾಲಿ ದಿನ", "day_empty_body": "ಈ ದಿನಕ್ಕೆ ಏನೂ ಯೋಜಿಸಿಲ್ಲ. ಕಾರ್ಯ ಸೇರಿಸಲು + ಒತ್ತಿ.",
"week_day_free": "ಖಾಲಿ", "month_legend": "ತುಂಬಿದ ಹಸಿರು ಚುಕ್ಕೆ ಎಂದರೆ ಯೋಜಿಸಿದ್ದೆಲ್ಲವೂ ಮುಗಿದಿದೆ. ಕಿತ್ತಳೆ ಚುಕ್ಕೆ ಎಂದರೆ ಕಾರ್ಯಗಳಿವೆ; ಹೆಚ್ಚು ಮುಗಿದಂತೆ ಅದು ಗಾಢವಾಗುತ್ತದೆ.",
"month_cell_a11y": "ದಿನ %1$d, %3$d ರಲ್ಲಿ %2$d ಮುಗಿದಿವೆ",
"subtasks_count": "%1$d/%2$d ಹಂತಗಳು", "skipped": "ಸ್ಥಳಾಂತರಿಸಲಾಗಿದೆ", "example_badge": "ಉದಾಹರಣೆ", "repeats": "ಪುನರಾವರ್ತನೆ", "has_reminder": "ಜ್ಞಾಪನೆ ಇದೆ",
"edit": "ತಿದ್ದಿ", "move_to_trash": "ಕಸದ ಬುಟ್ಟಿಗೆ ಸರಿಸಿ", "task_moved_to_trash": "ಕಸದ ಬುಟ್ಟಿಗೆ ಸರಿಸಲಾಗಿದೆ", "undo": "ರದ್ದುಮಾಡಿ",
"priority_none": "ಯಾವುದೂ ಇಲ್ಲ", "priority_low": "ಕಡಿಮೆ", "priority_medium": "ಮಧ್ಯಮ", "priority_high": "ಹೆಚ್ಚು",
"new_task": "ಹೊಸ ಕಾರ್ಯ", "edit_task": "ಕಾರ್ಯ ತಿದ್ದಿ", "save": "ಉಳಿಸಿ", "close": "ಮುಚ್ಚಿ", "cancel": "ರದ್ದು", "ok": "ಸರಿ", "back": "ಹಿಂದೆ", "clear": "ತೆರವುಗೊಳಿಸಿ",
"retry": "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ", "optional": "ಐಚ್ಛಿಕ",
"field_title": "ಶೀರ್ಷಿಕೆ", "field_description": "ವಿವರಣೆ", "field_notes": "ಟಿಪ್ಪಣಿಗಳು", "field_tags": "ಟ್ಯಾಗ್‌ಗಳು", "field_tags_hint": "ಅಲ್ಪವಿರಾಮದಿಂದ ಬೇರ್ಪಡಿಸಿ",
"section_when": "ಯಾವಾಗ", "section_repeat": "ಪುನರಾವರ್ತನೆ", "section_reminders": "ಜ್ಞಾಪನೆಗಳು", "section_priority": "ಆದ್ಯತೆ", "section_category": "ವರ್ಗ", "section_subtasks": "ಹಂತಗಳು",
"starts_at": "ಆರಂಭ %1$s", "ends_at": "ಮುಕ್ತಾಯ %1$s", "add_end_time": "ಮುಕ್ತಾಯ ಸಮಯ ಸೇರಿಸಿ", "remove_end_time": "ಮುಕ್ತಾಯ ಸಮಯ ತೆಗೆಯಿರಿ",
"repeat_none": "ಒಮ್ಮೆ", "repeat_daily": "ಪ್ರತಿದಿನ", "repeat_weekdays": "ವಾರದ ದಿನಗಳು", "repeat_weekly": "ಪ್ರತಿವಾರ", "repeat_monthly": "ಪ್ರತಿ ತಿಂಗಳು", "repeat_yearly": "ಪ್ರತಿ ವರ್ಷ",
"repeat_every": "ಪ್ರತಿ %1$d", "repeat_until": "%1$s ರವರೆಗೆ", "repeat_forever": "ಕೊನೆಯ ದಿನಾಂಕವಿಲ್ಲ",
"add_reminder": "ಜ್ಞಾಪನೆ ಸೇರಿಸಿ", "remove_reminder": "ಜ್ಞಾಪನೆ ತೆಗೆಯಿರಿ", "reminder_at_start": "ಆರಂಭದ ಸಮಯದಲ್ಲಿ", "reminder_before": "%1$d ನಿಮಿಷ ಮೊದಲು",
"reminder_custom_time": "ನಿರ್ದಿಷ್ಟ ಸಮಯಕ್ಕೆ…", "reminder_at": "%1$s ಕ್ಕೆ", "reminder_persistent": "ನಾನು ಕ್ರಮ ಕೈಗೊಳ್ಳುವವರೆಗೆ ಇರಲಿ",
"add_subtask": "ಹಂತ ಸೇರಿಸಿ", "remove_subtask": "ಹಂತ ತೆಗೆಯಿರಿ",
"example_note": "ಇದು ಉದಾಹರಣೆ ಕಾರ್ಯ. ಇದನ್ನು ತಿದ್ದಬಹುದು ಅಥವಾ ಸೆಟ್ಟಿಂಗ್ಸ್‌ನಲ್ಲಿ ಎಲ್ಲಾ ಉದಾಹರಣೆಗಳನ್ನು ತೆಗೆಯಬಹುದು.",
"error_title_empty": "ಕಾರ್ಯಕ್ಕೆ ಶೀರ್ಷಿಕೆ ನೀಡಿ.", "error_title_long": "ಶೀರ್ಷಿಕೆ %1$d ಅಕ್ಷರಗಳಿಗಿಂತ ಕಡಿಮೆ ಇರಲಿ.",
"error_end_before_start": "ಮುಕ್ತಾಯ ಸಮಯ ಆರಂಭಕ್ಕಿಂತ ಮೊದಲಿದೆ.", "error_reminder_needs_time": "\"ಆರಂಭಕ್ಕೆ ಮೊದಲು\" ಜ್ಞಾಪನೆಗಳಿಗೆ ಆರಂಭ ಸಮಯ ಬೇಕು.",
"error_too_many_reminders": "ಒಂದು ಕಾರ್ಯಕ್ಕೆ ಗರಿಷ್ಠ %1$d ಜ್ಞಾಪನೆಗಳು.",
"error_title": "ಏನೋ ತಪ್ಪಾಗಿದೆ", "error_body": "ನಿಮ್ಮ ಮಾಹಿತಿ ಸುರಕ್ಷಿತವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.", "error_save_body": "ಕಾರ್ಯವನ್ನು ಉಳಿಸಲಾಗಲಿಲ್ಲ. ಏನೂ ಕಳೆದುಹೋಗಿಲ್ಲ; ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
"error_action_failed": "ಅದು ಆಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
"task_missing": "ಈ ಕಾರ್ಯ ಈಗ ಇಲ್ಲ", "task_missing_body": "ಇದನ್ನು ಅಳಿಸಿರಬಹುದು ಅಥವಾ ಕಸದ ಬುಟ್ಟಿಗೆ ಸರಿಸಿರಬಹುದು.",
"trash_confirm_body": "ಕಾರ್ಯ ಕಸದ ಬುಟ್ಟಿಗೆ ಹೋಗುತ್ತದೆ. ಇನ್ನಷ್ಟು > ಕಸದ ಬುಟ್ಟಿ ಇಂದ ಮರಳಿ ಪಡೆಯಬಹುದು.",
"reschedule_title": "ಮರುನಿಗದಿ", "reschedule_recurring_note": "ಈ ಒಂದು ಬಾರಿ ಮಾತ್ರ ಸರಿಯುತ್ತದೆ. ಪುನರಾವರ್ತಿತ ಯೋಜನೆ ಹಾಗೆಯೇ ಇರುತ್ತದೆ.",
"action_done": "ಮುಗಿದಿದೆ", "action_snooze": "ಮುಂದೂಡಿ", "action_reschedule": "ಮರುನಿಗದಿ",
"reminder_label": "ಕಾರ್ಯ", "reminder_all_day": "ಇಂದು", "reminder_public_title": "ಕೈರೋಸ್ ಎರಾ ಜ್ಞಾಪನೆ",
"channel_group_reminders": "ಕಾರ್ಯ ಜ್ಞಾಪನೆಗಳು", "channel_default": "ಜ್ಞಾಪನೆಗಳು (ಡೀಫಾಲ್ಟ್ ಧ್ವನಿ)", "channel_general": "ಸಾಮಾನ್ಯ",
"channel_reminders_description": "ನೀವು ನಿಗದಿಪಡಿಸಿದ ಕಾರ್ಯಗಳ ಜ್ಞಾಪನೆಗಳು.",
"sound_default": "ಡೀಫಾಲ್ಟ್", "sound_kairos_bell": "ಕೈರೋಸ್ ಗಂಟೆ", "sound_soft_chime": "ಮೃದು ನಾದ", "sound_focus": "ಏಕಾಗ್ರತೆ", "sound_silent": "ನಿಶ್ಶಬ್ದ",
"track_soon_title": "ಟ್ರ್ಯಾಕರ್‌ಗಳು ಮುಂದೆ ಬರಲಿವೆ", "track_soon_body": "ಅಧ್ಯಯನ ವಿಷಯಗಳು, ವ್ಯಾಯಾಮ, ನಿದ್ರೆ, ನೀರು, ಅಭ್ಯಾಸಗಳು ಅಥವಾ ಯೋಜನೆಗಳು: ಯಾವುದಕ್ಕೂ ನಿಮ್ಮದೇ ಟ್ರ್ಯಾಕರ್ ರಚಿಸಿ. ಇದು ಮುಂದಿನ ಅಪ್‌ಡೇಟ್‌ನಲ್ಲಿ ಬರುತ್ತದೆ.",
"read_soon_title": "ಓದುವಿಕೆ ಮುಂದೆ ಬರಲಿದೆ", "read_soon_body": "ಪುಸ್ತಕಗಳು ಮತ್ತು ಪುಟಗಳನ್ನು ದಾಖಲಿಸಿ; ಏಕೆ ಆರಂಭಿಸಿದಿರಿ, ಏನು ಕಲಿತಿರಿ, ಏನು ಅಳವಡಿಸಿಕೊಂಡಿರಿ ಎಂದು ಬರೆದಿಡಿ. ಇದು ಮುಂದಿನ ಅಪ್‌ಡೇಟ್‌ನಲ್ಲಿ ಬರುತ್ತದೆ.",
"settings": "ಸೆಟ್ಟಿಂಗ್ಸ್", "settings_summary": "ಭಾಷೆ, ನೋಟ, ಅಧಿಸೂಚನೆಗಳು, ಧ್ವನಿಗಳು", "calendar": "ಕ್ಯಾಲೆಂಡರ್", "calendar_summary": "ನಿಮ್ಮ ಯೋಜನೆಯ ತಿಂಗಳ ನೋಟ",
"trash": "ಕಸದ ಬುಟ್ಟಿ", "trash_summary": "ಇತ್ತೀಚೆಗೆ ಅಳಿಸಿದ ಕಾರ್ಯಗಳನ್ನು ಮರಳಿ ಪಡೆಯಿರಿ", "privacy": "ಗೌಪ್ಯತೆ", "privacy_summary": "ನಿಮ್ಮ ಮಾಹಿತಿ ಈ ಸಾಧನದಲ್ಲೇ ಇರುತ್ತದೆ",
"about": "ಕುರಿತು", "about_summary": "ಕೈರೋಸ್ ಎರಾ ಮತ್ತು ಅದರ ಅರ್ಥ", "coming_next": "ಮುಂದೆ ಬರಲಿರುವುದು", "soon": "ಮುಂಬರುವ ಅಪ್‌ಡೇಟ್‌ನಲ್ಲಿ",
"journal": "ದಿನಚರಿ", "statistics": "ಅಂಕಿಅಂಶಗಳು", "backup": "ಬ್ಯಾಕಪ್", "diagnostics": "ರೋಗನಿರ್ಣಯ",
"settings_general": "ಸಾಮಾನ್ಯ", "settings_language": "ಭಾಷೆ", "language_system": "ಫೋನ್ ಭಾಷೆ", "language_english": "English", "language_kannada": "ಕನ್ನಡ",
"settings_appearance": "ನೋಟ", "theme_system": "ಸಿಸ್ಟಮ್", "theme_light": "ತಿಳಿ", "theme_dark": "ಗಾಢ",
"dynamic_color": "ವಾಲ್‌ಪೇಪರ್ ಬಣ್ಣಗಳು", "dynamic_color_summary": "ಕೈರೋಸ್ ಬಣ್ಣಗಳ ಬದಲು ನಿಮ್ಮ ವಾಲ್‌ಪೇಪರ್‌ನ ಬಣ್ಣಗಳನ್ನು ಬಳಸಿ.",
"settings_notifications": "ಅಧಿಸೂಚನೆಗಳು", "notif_permission": "ಅಧಿಸೂಚನೆಗಳು", "status_allowed": "ಅನುಮತಿ ಇದೆ", "status_off": "ಆಫ್", "allow": "ಅನುಮತಿಸಿ",
"notif_permission_off_body": "ಅಧಿಸೂಚನೆಗಳಿಗೆ ಅನುಮತಿ ನೀಡುವವರೆಗೆ ಜ್ಞಾಪನೆಗಳು ಕಾಣುವುದಿಲ್ಲ. ಉಳಿದೆಲ್ಲವೂ ಸಾಮಾನ್ಯವಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ.",
"exact_alarms": "ಸಮಯಕ್ಕೆ ಸರಿಯಾದ ಜ್ಞಾಪನೆಗಳು", "exact_alarms_off_body": "ಇದಿಲ್ಲದಿದ್ದರೆ, ಬ್ಯಾಟರಿ ಉಳಿಸಲು Android ಜ್ಞಾಪನೆಗಳನ್ನು ಕೆಲವು ನಿಮಿಷ ತಡವಾಗಿ ನೀಡಬಹುದು.",
"open_settings": "ಸೆಟ್ಟಿಂಗ್ಸ್ ತೆರೆಯಿರಿ", "battery_title": "ಬ್ಯಾಟರಿ ಆಪ್ಟಿಮೈಸೇಶನ್",
"battery_body": "ಕೆಲವು ಫೋನ್‌ಗಳು ಹಿನ್ನೆಲೆಯಲ್ಲಿ ಆ್ಯಪ್‌ಗಳನ್ನು ನಿಲ್ಲಿಸುತ್ತವೆ. ಜ್ಞಾಪನೆಗಳು ತಡವಾದರೆ, ಕೈರೋಸ್ ಎರಾಗೆ ನಿರ್ಬಂಧವಿಲ್ಲದೆ ಓಡಲು ಅನುಮತಿಸಿ.",
"test_notification": "ಪರೀಕ್ಷಾ ಅಧಿಸೂಚನೆ ಕಳುಹಿಸಿ", "test_notification_summary": "ಧ್ವನಿ ಮತ್ತು ನೋಟವನ್ನು ಪರಿಶೀಲಿಸಿ.",
"test_notification_title": "ಕೈರೋಸ್ ಎರಾ", "test_notification_text": "ಅಧಿಸೂಚನೆಗಳು ಕೆಲಸ ಮಾಡುತ್ತಿವೆ.",
"settings_sounds": "ಧ್ವನಿಗಳು", "default_sound": "ಹೊಸ ಜ್ಞಾಪನೆಗಳ ಡೀಫಾಲ್ಟ್ ಧ್ವನಿ",
"sound_channel_note": "ಪ್ರತಿ ಧ್ವನಿಯ ವಾಲ್ಯೂಮ್, ಕಂಪನ ಮತ್ತು ಪ್ರಾಮುಖ್ಯತೆಯನ್ನು Android ಸಿಸ್ಟಮ್ ಸೆಟ್ಟಿಂಗ್ಸ್‌ನಲ್ಲಿ ಬದಲಾಯಿಸಬಹುದು. ಅಲ್ಲಿನ ನಿಮ್ಮ ಆಯ್ಕೆಗಳನ್ನು ಗೌರವಿಸಲಾಗುತ್ತದೆ.",
"open_sound_settings": "ಅಧಿಸೂಚನೆ ಸೆಟ್ಟಿಂಗ್ಸ್ ತೆರೆಯಿರಿ",
"default_persistent": "ನಾನು ಕ್ರಮ ಕೈಗೊಳ್ಳುವವರೆಗೆ ಜ್ಞಾಪನೆ ಇರಲಿ", "default_persistent_summary": "ಮುಗಿದಿದೆ, ಮುಂದೂಡಿ ಅಥವಾ ಮರುನಿಗದಿ ಒತ್ತುವವರೆಗೆ ಹೊಸ ಜ್ಞಾಪನೆಗಳು ಅಧಿಸೂಚನೆ ಪಟ್ಟಿಯಲ್ಲಿ ಇರುತ್ತವೆ.",
"snooze_length": "ಮುಂದೂಡುವ ಅವಧಿ", "minutes_short": "%1$d ನಿಮಿಷ",
"settings_data": "ಮಾಹಿತಿ", "add_examples": "ಉದಾಹರಣೆಗಳನ್ನು ಸೇರಿಸಿ", "add_examples_summary": "ಆ್ಯಪ್ ಹೇಗೆ ಕಾಣುತ್ತದೆ ಎಂದು ನೋಡಲು ಕೆಲವು ಮಾದರಿ ಕಾರ್ಯಗಳು.",
"remove_examples": "ಉದಾಹರಣೆಗಳನ್ನು ತೆಗೆಯಿರಿ", "remove_examples_summary": "ಎಲ್ಲಾ ಉದಾಹರಣೆ ಕಾರ್ಯಗಳನ್ನು ಕಸದ ಬುಟ್ಟಿಗೆ ಸರಿಸುತ್ತದೆ.", "remove_examples_confirm": "ಎಲ್ಲಾ ಉದಾಹರಣೆ ಕಾರ್ಯಗಳನ್ನು ಕಸದ ಬುಟ್ಟಿಗೆ ಸರಿಸಬೇಕೆ? ನಂತರ ಮರಳಿ ಪಡೆಯಬಹುದು.",
"settings_footer": "ಕೈರೋಸ್ ಎರಾ ಸಂಪೂರ್ಣವಾಗಿ ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ. ಖಾತೆ, ಕ್ಲೌಡ್ ಸಿಂಕ್, ವಿಶ್ಲೇಷಣೆ ಅಥವಾ ಜಾಹೀರಾತುಗಳು ಇಲ್ಲ.",
"move_up": "ಮೇಲೆ ಸರಿಸಿ", "move_down": "ಕೆಳಗೆ ಸರಿಸಿ",
"trash_empty_title": "ಕಸದ ಬುಟ್ಟಿ ಖಾಲಿಯಿದೆ", "trash_empty_body": "ಅಳಿಸಿದ ಕಾರ್ಯಗಳು, ನೀವು ಮರಳಿ ಪಡೆಯುವವರೆಗೆ ಅಥವಾ ಶಾಶ್ವತವಾಗಿ ಅಳಿಸುವವರೆಗೆ ಇಲ್ಲಿರುತ್ತವೆ.",
"trash_explainer": "ನೀವು ನಿರ್ಧರಿಸುವವರೆಗೆ ಐಟಂಗಳು ಇಲ್ಲೇ ಇರುತ್ತವೆ. ಯಾವುದನ್ನೂ ತಾನಾಗಿಯೇ ತೆಗೆಯಲಾಗುವುದಿಲ್ಲ.",
"restore": "ಮರಳಿ ಪಡೆಯಿರಿ", "delete_forever": "ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಿ", "delete_forever_title": "ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಬೇಕೆ?",
"delete_forever_body": "\"%1$s\" ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಲ್ಪಡುತ್ತದೆ. ಇದನ್ನು ಹಿಂಪಡೆಯಲು ಸಾಧ್ಯವಿಲ್ಲ.", "deleted_on": "%1$s ರಂದು ಅಳಿಸಲಾಗಿದೆ",
"privacy_headline": "ನಿಮ್ಮ ಮಾಹಿತಿ ಈ ಸಾಧನದಲ್ಲೇ ಇರುತ್ತದೆ.",
"privacy_point_device": "ನೀವು ಬರೆಯುವುದೆಲ್ಲವೂ (ಕಾರ್ಯಗಳು, ಟಿಪ್ಪಣಿಗಳು, ಜ್ಞಾಪನೆಗಳು) ನಿಮ್ಮ ಫೋನ್‌ನಲ್ಲಿ ಈ ಆ್ಯಪ್‌ನ ಖಾಸಗಿ ಸಂಗ್ರಹದಲ್ಲಿ ಮಾತ್ರ ಉಳಿಯುತ್ತದೆ.",
"privacy_point_account": "ಯಾವುದೇ ಖಾತೆ ಅಥವಾ ಸೈನ್-ಇನ್ ಇಲ್ಲ.",
"privacy_point_cloud": "ಕ್ಲೌಡ್ ಸಿಂಕ್ ಅಥವಾ ಸರ್ವರ್ ಇಲ್ಲ. ಕೈರೋಸ್ ಎರಾ ನಿಮ್ಮ ಮಾಹಿತಿಯನ್ನು ಎಂದಿಗೂ ಅಪ್‌ಲೋಡ್ ಮಾಡುವುದಿಲ್ಲ.",
"privacy_point_network": "ಈ ಆ್ಯಪ್ ಇಂಟರ್ನೆಟ್ ಅನುಮತಿಯನ್ನೇ ಕೇಳುವುದಿಲ್ಲ, ಆದ್ದರಿಂದ ಏರ್‌ಪ್ಲೇನ್ ಮೋಡ್‌ನಲ್ಲೂ ಹಾಗೆಯೇ ಕೆಲಸ ಮಾಡುತ್ತದೆ.",
"privacy_point_storage": "ಇತರ ಆ್ಯಪ್‌ಗಳು ಈ ಆ್ಯಪ್‌ನ ಖಾಸಗಿ ಸಂಗ್ರಹವನ್ನು ಓದಲು ಸಾಧ್ಯವಿಲ್ಲ.",
"privacy_point_logs": "ರೋಗನಿರ್ಣಯ ಲಾಗ್‌ಗಳಲ್ಲಿ ನಿಮ್ಮ ಕಾರ್ಯಗಳ ಶೀರ್ಷಿಕೆ, ಟಿಪ್ಪಣಿ ಅಥವಾ ಇತರ ವೈಯಕ್ತಿಕ ಪಠ್ಯ ಎಂದಿಗೂ ಇರುವುದಿಲ್ಲ.",
"privacy_point_lock": "ಫೋನ್‌ನ ಬೆರಳಚ್ಚು, ಮುಖ ಅಥವಾ ಸ್ಕ್ರೀನ್ ಲಾಕ್ ಬಳಸುವ ಐಚ್ಛಿಕ ಆ್ಯಪ್ ಲಾಕ್ ಮುಂದಿನ ಅಪ್‌ಡೇಟ್‌ನಲ್ಲಿ ಬರಲಿದೆ.",
"privacy_point_backup": "ನಿಮ್ಮ ನಿಯಂತ್ರಣದಲ್ಲಿರುವ ಸ್ಥಳೀಯ ಬ್ಯಾಕಪ್ ಫೈಲ್‌ಗಳು ಮುಂದಿನ ಅಪ್‌ಡೇಟ್‌ನಲ್ಲಿ ಬರಲಿವೆ. ಈ ಆ್ಯಪ್‌ಗೆ Android ನ ಸ್ವಯಂ ಕ್ಲೌಡ್ ಬ್ಯಾಕಪ್ ಆಫ್ ಆಗಿದೆ.",
"privacy_point_diagnostics": "ಆ್ಯಪ್ ಎಂದಾದರೂ ಕ್ರ್ಯಾಶ್ ಆದರೆ, ಯಾವುದೇ ವರದಿ ಹಂಚುವ ಮೊದಲು ನಿಮ್ಮನ್ನು ಕೇಳಲಾಗುತ್ತದೆ; ಅದರಲ್ಲಿ ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ ಇರುವುದಿಲ್ಲ.",
"about_philosophy": "ದಿನವನ್ನು ಯೋಜಿಸಿ. ಏನಾದರೂ ಕಲಿಯಿರಿ. ದೇಹವನ್ನು ಚಲಿಸಿ. ಅರ್ಥಪೂರ್ಣವಾದುದನ್ನು ಓದಿ. ಚಿಂತಿಸಿ. ಪುನರಾವರ್ತಿಸಿ.",
"about_meaning": "ಕೈರೋಸ್ ಎಂದರೆ ಗ್ರೀಕ್ ಭಾಷೆಯಲ್ಲಿ ಸರಿಯಾದ, ಸೂಕ್ತ ಕ್ಷಣ. ಲಾಂಛನವು ಉದಯಿಸುವ ಸೂರ್ಯನತ್ತ ಸಾಗುವ ದಾರಿ: ಹೊಸ ದಿನ, ನಿರಂತರ ಪ್ರಗತಿ ಮತ್ತು ಬೆಳವಣಿಗೆ.",
"about_version": "ಆವೃತ್ತಿ %1$s",
"onboarding_welcome": "ನಿಮ್ಮ ಸಮಯ ನಿಮ್ಮದು.", "onboarding_private": "ಖಾಸಗಿ: ನಿಮ್ಮ ಯೋಜನೆಗಳು ನಿಮಗೆ ಮಾತ್ರ ಕಾಣುತ್ತವೆ.", "onboarding_local": "ಸ್ಥಳೀಯ: ಎಲ್ಲವೂ ಈ ಫೋನ್‌ನಲ್ಲೇ ಉಳಿಯುತ್ತದೆ.",
"onboarding_no_account": "ಖಾತೆ ಇಲ್ಲ, ಸೈನ್-ಇನ್ ಇಲ್ಲ.", "onboarding_no_cloud": "ಕ್ಲೌಡ್ ಸಿಂಕ್ ಇಲ್ಲ, ಟ್ರ್ಯಾಕಿಂಗ್ ಇಲ್ಲ, ಜಾಹೀರಾತು ಇಲ್ಲ.",
"onboarding_begin": "ಆರಂಭಿಸಿ", "onboarding_about_you": "ನಿಮ್ಮ ಬಗ್ಗೆ ಸ್ವಲ್ಪ", "onboarding_name_label": "ಹೆಸರು ಅಥವಾ ಅಡ್ಡಹೆಸರು",
"onboarding_focus": "ಯಾವುದರ ಮೇಲೆ ಗಮನ ಹರಿಸಲು ಬಯಸುವಿರಿ?", "focus_learning": "ಕಲಿಕೆ", "focus_health": "ಆರೋಗ್ಯ", "focus_reading": "ಓದು", "focus_work": "ಕೆಲಸ",
"focus_personal": "ವೈಯಕ್ತಿಕ", "focus_custom": "ಬೇರೆ ಏನಾದರೂ",
"onboarding_first_task": "ಇಂದು ಮಾಡಬೇಕಾದ ಒಂದು ಕೆಲಸ", "onboarding_first_task_hint": "ಐಚ್ಛಿಕ. ನಂತರ ಇನ್ನಷ್ಟು ಸೇರಿಸಬಹುದು.",
"onboarding_examples": "ಉದಾಹರಣೆ ಕಾರ್ಯಗಳನ್ನು ತೋರಿಸಿ (ಯಾವಾಗ ಬೇಕಾದರೂ ತೆಗೆಯಬಹುದು)",
"onboarding_reminders_title": "ಜ್ಞಾಪನೆಗಳು", "onboarding_reminders_body": "ಕಾರ್ಯದ ಸಮಯ ಬಂದಾಗ ಕೈರೋಸ್ ಎರಾ ನಿಮಗೆ ನೆನಪಿಸಬಹುದು. ಅದು ಕೇಳುವ ಏಕೈಕ ಅನುಮತಿ ಅಧಿಸೂಚನೆಗಳು; ಇದನ್ನು ಯಾವಾಗ ಬೇಕಾದರೂ ಬದಲಾಯಿಸಬಹುದು.",
"onboarding_allow_reminders": "ಜ್ಞಾಪನೆಗಳಿಗೆ ಅನುಮತಿಸಿ", "onboarding_not_now": "ಈಗ ಬೇಡ",
"sample_java": "ಜಾವಾ: ಕಲೆಕ್ಷನ್ಸ್", "sample_java_1": "List ಮತ್ತು ArrayList", "sample_java_2": "HashMap ಒಳರಚನೆ", "sample_java_3": "3 ಸಮಸ್ಯೆಗಳನ್ನು ಬಿಡಿಸಿ",
"sample_walk": "ಬೆಳಗಿನ ನಡಿಗೆ", "sample_project": "ಪ್ರಾಜೆಕ್ಟ್ ಕೆಲಸ", "sample_workout": "ವ್ಯಾಯಾಮ", "sample_read": "20 ಪುಟ ಓದಿ", "sample_reflection": "ದಿನದ ಚಿಂತನೆ",
}
