# Speaking coach (on-device Gemma) UI text, English and Kannada. Merged into EN/KN by strings_source.py.
# Also updates the privacy policy for the microphone and the coach's reports.
SC_EN = {
"sc_title": "1 Minute Speech",
"sc_subtitle": "Speak for 60 seconds and get AI feedback.",
"sc_speak_now": "SPEAK NOW",
"sc_recording": "Recording",
"sc_discard": "Discard",
"sc_analyzing": "ANALYZING SPEECH",
"sc_processing": "Processing locally…",
"sc_step_loading": "Loading Gemma on your phone…",
"sc_step_listening": "Listening to part %1$d of %2$d…",
"sc_step_writing": "Writing your feedback…",
"sc_never_leaves": "Your recording never leaves your device.",
"sc_cancel": "Cancel",
"sc_coach_ready": "AI feedback is on. Gemma runs on this phone, offline.",
"sc_coach_off_title": "Get AI feedback",
"sc_coach_off_body": "Add the Gemma model once and Kairos can coach every speech, offline. Until then, Start runs the timer only.",
"sc_coach_setup": "Set up",
"sc_coach_settings": "Coach settings",
"sc_view_progress": "View my progress",
"sc_retry_analysis": "Try analysis again",
"sc_record_again": "Record again",
"sc_mic_rationale": "Kairos needs the microphone to record your speech. The recording stays on this phone.",
"sc_open_settings": "Open settings",
"sc_timer_instead": "Use the timer only",
"sc_last_report": "Latest report",

"sc_err_mic_permission": "Microphone permission was not given. Allow it to record your speech, or use the timer only.",
"sc_err_mic_unavailable": "The microphone is not available. Another app may be using it.",
"sc_err_recording_failed": "Recording failed. Please try again.",
"sc_err_interrupted": "Recording stopped because of a call, another app, or leaving Kairos. Please try again.",
"sc_err_too_short": "That was under 10 seconds. Speak a little longer to get feedback.",
"sc_err_no_speech": "Gemma couldn't hear any speech. Check the microphone and speak a little closer.",
"sc_err_model_missing": "The Gemma model isn't installed yet. Add it in Coach settings.",
"sc_err_model_extension": "That file isn't a .litertlm model. Choose gemma-4-E2B-it.litertlm.",
"sc_err_model_malformed": "The model file is damaged or incomplete. Import it again.",
"sc_err_low_storage": "Not enough free storage. The model needs about 2.9 GB free.",
"sc_err_low_memory": "This phone doesn't have enough free memory for Gemma. Close other apps and try again, or use a phone with 8 GB of RAM.",
"sc_err_unsupported": "Gemma is not available on this device. Try CPU mode or use a supported device.",
"sc_err_inference": "Gemma stopped with an error while analysing. Try again, or switch to CPU mode in Coach settings.",
"sc_err_bad_response": "Gemma's answer couldn't be read this time. Try the analysis again.",
"sc_err_timeout": "The analysis took too long. Try again, or switch processor in Coach settings.",
"sc_err_import": "The model could not be copied. Please try again.",

"sc_setup_title": "AI Speaking Coach",
"sc_setup_intro": "The coach runs Google's Gemma-4-E2B-it model on this phone with LiteRT-LM. Your speech is analysed on the device and never uploaded; Kairos has no internet permission.",
"sc_model_section": "Model",
"sc_model_installed": "Installed: %1$s",
"sc_model_size": "%1$s GB",
"sc_model_none": "Not installed yet.",
"sc_model_bad": "A model file is there, but it can't be used.",
"sc_model_import": "Import model file",
"sc_model_replace": "Replace model file",
"sc_model_import_hint": "Choose gemma-4-E2B-it.litertlm (about 2.6 GB). AI Edge Gallery keeps its copy in its own storage, which Kairos cannot open, so put the file in Downloads first: download it from Hugging Face (litert-community/gemma-4-E2B-it-litert-lm) or copy it from your computer.",
"sc_model_adb": "Developer: or copy it with adb to %1$s",
"sc_model_copying": "Copying… %1$s of %2$s GB",
"sc_model_copying_unknown": "Copying… %1$s GB",
"sc_model_ready": "Model ready.",
"sc_model_remove": "Remove model",
"sc_model_test": "Test the model",
"sc_model_loading": "Loading Gemma on %1$s…",
"sc_model_test_ok": "Gemma loaded on %1$s in %2$s s.",
"sc_model_fell_back": "GPU did not work on this phone, so Gemma is using CPU.",
"sc_backend_section": "Processor",
"sc_backend_gpu": "GPU",
"sc_backend_gpu_summary": "Faster. Falls back to CPU by itself if the GPU fails.",
"sc_backend_cpu": "CPU",
"sc_backend_cpu_summary": "Slower, but works on more phones.",
"sc_device_section": "This phone",
"sc_device_ram": "Memory: %1$s GB",
"sc_device_ok": "Meets the 8 GB that Gemma-4-E2B-it needs.",
"sc_device_low": "Below the 8 GB Gemma-4-E2B-it is listed for. It may be slow or fail to load.",
"sc_device_too_small": "Too little memory for Gemma-4-E2B-it, so the coach stays off on this phone.",
"sc_keep_recordings": "Keep my recordings",
"sc_keep_recordings_summary": "Off: each recording is deleted as soon as it is analysed. On: kept in Kairos's private storage.",

"sc_report_title": "Speech Report",
"sc_tab_overview": "Overview",
"sc_tab_well": "Did Well",
"sc_tab_improve": "Improve",
"sc_tab_next": "Next",
"sc_out_of_ten": "/ 10",
"sc_score_a11y": "Score %1$s out of 10",
"sc_headline_high": "Excellent — keep it up.",
"sc_headline_mid": "Good progress — here's how to improve.",
"sc_headline_low": "A good start — here's what to work on.",
"sc_detailed": "Detailed Scores",
"sc_view_details": "View details",
"sc_clarity": "Clarity",
"sc_structure": "Structure",
"sc_vocabulary": "Vocabulary",
"sc_grammar": "Grammar",
"sc_conciseness": "Conciseness",
"sc_na": "N/A",
"sc_na_hint": "N/A means Gemma could not judge this reliably from your speech.",
"sc_stats": "Speech Stats",
"sc_duration": "Duration",
"sc_seconds": "%1$d sec",
"sc_pace": "Estimated pace",
"sc_pace_slow": "Slow",
"sc_pace_normal": "Normal",
"sc_pace_fast": "Fast",
"sc_wpm": "%1$d words/min",
"sc_fillers": "Filler sounds",
"sc_fillers_info": "Hesitations like \"um\" and \"uh\" found in Gemma's transcript. Speech recognition can miss some, so the real number may be higher.",
"sc_pauses": "Long pauses: %1$d",
"sc_transcript": "What Gemma heard",
"sc_show": "Show",
"sc_hide": "Hide",
"sc_done": "Done",
"sc_well_title": "What You Did Well",
"sc_well_sub": "Your strengths from this speech.",
"sc_none_listed": "Gemma didn't list anything here this time.",
"sc_improve_title": "How To Improve",
"sc_improve_sub": "Actionable feedback for your next minute.",
"sc_fillers_heard": "Filler words Gemma noticed",
"sc_try_pause": "Try a short pause instead.",
"sc_try_next": "Try this next time",
"sc_next_title": "Your Next 1-Minute Challenge",
"sc_next_sub": "Practise consistently to see real improvement.",
"sc_next_exercise": "Exercise",
"sc_rules": "Rules",
"sc_rule1": "No notes",
"sc_rule1_sub": "Speak without looking at your phone or notes.",
"sc_rule2": "Use a clear structure",
"sc_rule2_sub": "Point, example, conclusion.",
"sc_rule3": "Finish within 60 seconds",
"sc_rule3_sub": "Be concise and focused.",
"sc_practise_again": "Practise again",
"sc_ran_on": "Analysed on this phone (%1$s).",
"sc_delete_report": "Delete this report",
"sc_delete_report_q": "Delete this speech report? This cannot be undone.",
"sc_delete": "Delete",
"sc_not_found": "This report is no longer here.",

"sc_progress_title": "Speech Progress",
"sc_progress_empty": "Your scores appear here after your first analysed speech.",
"sc_avg": "Average",
"sc_best": "Best",
"sc_speeches": "Speeches",
"sc_since_first": "Since first",
"sc_history": "History",
"sc_chart_a11y": "Score chart: %1$d speeches, latest %2$s out of 10",
"sc_stats_card_summary": "%1$d speeches · average %2$s",
}

SC_KN = {
"sc_title": "1 ನಿಮಿಷದ ಭಾಷಣ",
"sc_subtitle": "60 ಸೆಕೆಂಡ್ ಮಾತನಾಡಿ, AI ಪ್ರತಿಕ್ರಿಯೆ ಪಡೆಯಿರಿ.",
"sc_speak_now": "ಈಗ ಮಾತನಾಡಿ",
"sc_recording": "ರೆಕಾರ್ಡ್ ಆಗುತ್ತಿದೆ",
"sc_discard": "ತಿರಸ್ಕರಿಸಿ",
"sc_analyzing": "ಭಾಷಣ ವಿಶ್ಲೇಷಣೆ",
"sc_processing": "ಫೋನ್‌ನಲ್ಲೇ ಸಂಸ್ಕರಿಸಲಾಗುತ್ತಿದೆ…",
"sc_step_loading": "ನಿಮ್ಮ ಫೋನ್‌ನಲ್ಲಿ Gemma ಲೋಡ್ ಆಗುತ್ತಿದೆ…",
"sc_step_listening": "%2$d ರಲ್ಲಿ %1$d ನೇ ಭಾಗವನ್ನು ಕೇಳುತ್ತಿದೆ…",
"sc_step_writing": "ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆ ಬರೆಯುತ್ತಿದೆ…",
"sc_never_leaves": "ನಿಮ್ಮ ರೆಕಾರ್ಡಿಂಗ್ ನಿಮ್ಮ ಸಾಧನವನ್ನು ಎಂದಿಗೂ ಬಿಡುವುದಿಲ್ಲ.",
"sc_cancel": "ರದ್ದುಮಾಡಿ",
"sc_coach_ready": "AI ಪ್ರತಿಕ್ರಿಯೆ ಆನ್ ಆಗಿದೆ. Gemma ಈ ಫೋನ್‌ನಲ್ಲೇ, ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿ ಚಲಿಸುತ್ತದೆ.",
"sc_coach_off_title": "AI ಪ್ರತಿಕ್ರಿಯೆ ಪಡೆಯಿರಿ",
"sc_coach_off_body": "Gemma ಮಾದರಿಯನ್ನು ಒಮ್ಮೆ ಸೇರಿಸಿದರೆ, ಕೈರೋಸ್ ಪ್ರತಿ ಭಾಷಣಕ್ಕೂ ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿ ತರಬೇತಿ ನೀಡುತ್ತದೆ. ಅಲ್ಲಿಯವರೆಗೆ, ಆರಂಭಿಸಿ ಒತ್ತಿದರೆ ಟೈಮರ್ ಮಾತ್ರ ಚಲಿಸುತ್ತದೆ.",
"sc_coach_setup": "ಹೊಂದಿಸಿ",
"sc_coach_settings": "ತರಬೇತುದಾರರ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
"sc_view_progress": "ನನ್ನ ಪ್ರಗತಿ ನೋಡಿ",
"sc_retry_analysis": "ವಿಶ್ಲೇಷಣೆ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
"sc_record_again": "ಮತ್ತೆ ರೆಕಾರ್ಡ್ ಮಾಡಿ",
"sc_mic_rationale": "ನಿಮ್ಮ ಭಾಷಣವನ್ನು ರೆಕಾರ್ಡ್ ಮಾಡಲು ಕೈರೋಸ್‌ಗೆ ಮೈಕ್ರೊಫೋನ್ ಬೇಕು. ರೆಕಾರ್ಡಿಂಗ್ ಈ ಫೋನ್‌ನಲ್ಲೇ ಇರುತ್ತದೆ.",
"sc_open_settings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ತೆರೆಯಿರಿ",
"sc_timer_instead": "ಟೈಮರ್ ಮಾತ್ರ ಬಳಸಿ",
"sc_last_report": "ಇತ್ತೀಚಿನ ವರದಿ",

"sc_err_mic_permission": "ಮೈಕ್ರೊಫೋನ್ ಅನುಮತಿ ನೀಡಿಲ್ಲ. ಭಾಷಣ ರೆಕಾರ್ಡ್ ಮಾಡಲು ಅನುಮತಿಸಿ, ಅಥವಾ ಟೈಮರ್ ಮಾತ್ರ ಬಳಸಿ.",
"sc_err_mic_unavailable": "ಮೈಕ್ರೊಫೋನ್ ಲಭ್ಯವಿಲ್ಲ. ಬೇರೆ ಆ್ಯಪ್ ಅದನ್ನು ಬಳಸುತ್ತಿರಬಹುದು.",
"sc_err_recording_failed": "ರೆಕಾರ್ಡಿಂಗ್ ವಿಫಲವಾಯಿತು. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
"sc_err_interrupted": "ಕರೆ, ಬೇರೆ ಆ್ಯಪ್ ಅಥವಾ ಕೈರೋಸ್‌ನಿಂದ ಹೊರಹೋದ ಕಾರಣ ರೆಕಾರ್ಡಿಂಗ್ ನಿಂತಿತು. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
"sc_err_too_short": "ಅದು 10 ಸೆಕೆಂಡಿಗಿಂತ ಕಡಿಮೆ ಇತ್ತು. ಪ್ರತಿಕ್ರಿಯೆ ಪಡೆಯಲು ಸ್ವಲ್ಪ ಹೆಚ್ಚು ಮಾತನಾಡಿ.",
"sc_err_no_speech": "Gemma ಗೆ ಯಾವುದೇ ಮಾತು ಕೇಳಿಸಲಿಲ್ಲ. ಮೈಕ್ರೊಫೋನ್ ಪರಿಶೀಲಿಸಿ, ಸ್ವಲ್ಪ ಹತ್ತಿರದಿಂದ ಮಾತನಾಡಿ.",
"sc_err_model_missing": "Gemma ಮಾದರಿ ಇನ್ನೂ ಸ್ಥಾಪನೆಯಾಗಿಲ್ಲ. ತರಬೇತುದಾರರ ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಸೇರಿಸಿ.",
"sc_err_model_extension": "ಆ ಫೈಲ್ .litertlm ಮಾದರಿ ಅಲ್ಲ. gemma-4-E2B-it.litertlm ಆರಿಸಿ.",
"sc_err_model_malformed": "ಮಾದರಿ ಫೈಲ್ ಹಾಳಾಗಿದೆ ಅಥವಾ ಅಪೂರ್ಣವಾಗಿದೆ. ಮತ್ತೆ ಆಮದು ಮಾಡಿ.",
"sc_err_low_storage": "ಸಾಕಷ್ಟು ಖಾಲಿ ಸಂಗ್ರಹ ಇಲ್ಲ. ಮಾದರಿಗೆ ಸುಮಾರು 2.9 GB ಖಾಲಿ ಜಾಗ ಬೇಕು.",
"sc_err_low_memory": "Gemma ಗಾಗಿ ಈ ಫೋನ್‌ನಲ್ಲಿ ಸಾಕಷ್ಟು ಮೆಮೊರಿ ಇಲ್ಲ. ಬೇರೆ ಆ್ಯಪ್‌ಗಳನ್ನು ಮುಚ್ಚಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ, ಅಥವಾ 8 GB RAM ಇರುವ ಫೋನ್ ಬಳಸಿ.",
"sc_err_unsupported": "ಈ ಸಾಧನದಲ್ಲಿ Gemma ಲಭ್ಯವಿಲ್ಲ. CPU ಮೋಡ್ ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ಬೆಂಬಲಿತ ಸಾಧನ ಬಳಸಿ.",
"sc_err_inference": "ವಿಶ್ಲೇಷಿಸುವಾಗ Gemma ದೋಷದಿಂದ ನಿಂತಿತು. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ, ಅಥವಾ ತರಬೇತುದಾರರ ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ CPU ಮೋಡ್‌ಗೆ ಬದಲಿಸಿ.",
"sc_err_bad_response": "ಈ ಬಾರಿ Gemma ಉತ್ತರವನ್ನು ಓದಲಾಗಲಿಲ್ಲ. ವಿಶ್ಲೇಷಣೆ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
"sc_err_timeout": "ವಿಶ್ಲೇಷಣೆಗೆ ತುಂಬಾ ಸಮಯ ಹಿಡಿಯಿತು. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ, ಅಥವಾ ತರಬೇತುದಾರರ ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಪ್ರೊಸೆಸರ್ ಬದಲಿಸಿ.",
"sc_err_import": "ಮಾದರಿಯನ್ನು ನಕಲಿಸಲಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",

"sc_setup_title": "AI ಮಾತಿನ ತರಬೇತುದಾರ",
"sc_setup_intro": "ತರಬೇತುದಾರ Google ನ Gemma-4-E2B-it ಮಾದರಿಯನ್ನು LiteRT-LM ಮೂಲಕ ಈ ಫೋನ್‌ನಲ್ಲೇ ಚಲಾಯಿಸುತ್ತದೆ. ನಿಮ್ಮ ಭಾಷಣವನ್ನು ಸಾಧನದಲ್ಲೇ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತದೆ, ಎಂದಿಗೂ ಅಪ್‌ಲೋಡ್ ಆಗುವುದಿಲ್ಲ; ಕೈರೋಸ್‌ಗೆ ಇಂಟರ್ನೆಟ್ ಅನುಮತಿ ಇಲ್ಲ.",
"sc_model_section": "ಮಾದರಿ",
"sc_model_installed": "ಸ್ಥಾಪಿಸಲಾಗಿದೆ: %1$s",
"sc_model_size": "%1$s GB",
"sc_model_none": "ಇನ್ನೂ ಸ್ಥಾಪಿಸಿಲ್ಲ.",
"sc_model_bad": "ಮಾದರಿ ಫೈಲ್ ಇದೆ, ಆದರೆ ಅದನ್ನು ಬಳಸಲಾಗುವುದಿಲ್ಲ.",
"sc_model_import": "ಮಾದರಿ ಫೈಲ್ ಆಮದು ಮಾಡಿ",
"sc_model_replace": "ಮಾದರಿ ಫೈಲ್ ಬದಲಿಸಿ",
"sc_model_import_hint": "gemma-4-E2B-it.litertlm (ಸುಮಾರು 2.6 GB) ಆರಿಸಿ. AI Edge Gallery ತನ್ನ ಪ್ರತಿಯನ್ನು ತನ್ನದೇ ಸಂಗ್ರಹದಲ್ಲಿ ಇಡುತ್ತದೆ, ಅದನ್ನು ಕೈರೋಸ್ ತೆರೆಯಲಾಗದು. ಆದ್ದರಿಂದ ಮೊದಲು ಫೈಲ್ ಅನ್ನು Downloads ಗೆ ಹಾಕಿ: Hugging Face ನಿಂದ (litert-community/gemma-4-E2B-it-litert-lm) ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ ಅಥವಾ ಕಂಪ್ಯೂಟರ್‌ನಿಂದ ನಕಲಿಸಿ.",
"sc_model_adb": "ಡೆವಲಪರ್: ಅಥವಾ adb ಮೂಲಕ %1$s ಗೆ ನಕಲಿಸಿ",
"sc_model_copying": "ನಕಲಿಸುತ್ತಿದೆ… %2$s GB ರಲ್ಲಿ %1$s",
"sc_model_copying_unknown": "ನಕಲಿಸುತ್ತಿದೆ… %1$s GB",
"sc_model_ready": "ಮಾದರಿ ಸಿದ್ಧವಾಗಿದೆ.",
"sc_model_remove": "ಮಾದರಿ ತೆಗೆಯಿರಿ",
"sc_model_test": "ಮಾದರಿಯನ್ನು ಪರೀಕ್ಷಿಸಿ",
"sc_model_loading": "%1$s ನಲ್ಲಿ Gemma ಲೋಡ್ ಆಗುತ್ತಿದೆ…",
"sc_model_test_ok": "Gemma %1$s ನಲ್ಲಿ %2$s ಸೆಕೆಂಡಿನಲ್ಲಿ ಲೋಡ್ ಆಯಿತು.",
"sc_model_fell_back": "ಈ ಫೋನ್‌ನಲ್ಲಿ GPU ಕೆಲಸ ಮಾಡಲಿಲ್ಲ, ಆದ್ದರಿಂದ Gemma CPU ಬಳಸುತ್ತಿದೆ.",
"sc_backend_section": "ಪ್ರೊಸೆಸರ್",
"sc_backend_gpu": "GPU",
"sc_backend_gpu_summary": "ವೇಗವಾಗಿದೆ. GPU ವಿಫಲವಾದರೆ ತಾನಾಗಿಯೇ CPU ಗೆ ಬದಲಾಗುತ್ತದೆ.",
"sc_backend_cpu": "CPU",
"sc_backend_cpu_summary": "ನಿಧಾನ, ಆದರೆ ಹೆಚ್ಚು ಫೋನ್‌ಗಳಲ್ಲಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ.",
"sc_device_section": "ಈ ಫೋನ್",
"sc_device_ram": "ಮೆಮೊರಿ: %1$s GB",
"sc_device_ok": "Gemma-4-E2B-it ಗೆ ಬೇಕಾದ 8 GB ಇದೆ.",
"sc_device_low": "Gemma-4-E2B-it ಗೆ ಸೂಚಿಸಿದ 8 GB ಗಿಂತ ಕಡಿಮೆ. ನಿಧಾನವಾಗಬಹುದು ಅಥವಾ ಲೋಡ್ ಆಗದಿರಬಹುದು.",
"sc_device_too_small": "Gemma-4-E2B-it ಗೆ ಮೆಮೊರಿ ತುಂಬಾ ಕಡಿಮೆ, ಆದ್ದರಿಂದ ಈ ಫೋನ್‌ನಲ್ಲಿ ತರಬೇತುದಾರ ಆಫ್ ಆಗಿರುತ್ತದೆ.",
"sc_keep_recordings": "ನನ್ನ ರೆಕಾರ್ಡಿಂಗ್‌ಗಳನ್ನು ಉಳಿಸಿ",
"sc_keep_recordings_summary": "ಆಫ್: ವಿಶ್ಲೇಷಣೆಯಾದ ತಕ್ಷಣ ರೆಕಾರ್ಡಿಂಗ್ ಅಳಿಸಲಾಗುತ್ತದೆ. ಆನ್: ಕೈರೋಸ್‌ನ ಖಾಸಗಿ ಸಂಗ್ರಹದಲ್ಲಿ ಉಳಿಯುತ್ತದೆ.",

"sc_report_title": "ಭಾಷಣ ವರದಿ",
"sc_tab_overview": "ಸಾರಾಂಶ",
"sc_tab_well": "ಉತ್ತಮ",
"sc_tab_improve": "ಸುಧಾರಣೆ",
"sc_tab_next": "ಮುಂದೆ",
"sc_out_of_ten": "/ 10",
"sc_score_a11y": "10 ರಲ್ಲಿ %1$s ಅಂಕ",
"sc_headline_high": "ಅತ್ಯುತ್ತಮ — ಹೀಗೆಯೇ ಮುಂದುವರಿಸಿ.",
"sc_headline_mid": "ಉತ್ತಮ ಪ್ರಗತಿ — ಸುಧಾರಿಸುವುದು ಹೀಗೆ.",
"sc_headline_low": "ಒಳ್ಳೆಯ ಆರಂಭ — ಇವುಗಳ ಮೇಲೆ ಕೆಲಸ ಮಾಡಿ.",
"sc_detailed": "ವಿವರವಾದ ಅಂಕಗಳು",
"sc_view_details": "ವಿವರ ನೋಡಿ",
"sc_clarity": "ಸ್ಪಷ್ಟತೆ",
"sc_structure": "ರಚನೆ",
"sc_vocabulary": "ಶಬ್ದಸಂಪತ್ತು",
"sc_grammar": "ವ್ಯಾಕರಣ",
"sc_conciseness": "ಸಂಕ್ಷಿಪ್ತತೆ",
"sc_na": "ಲಭ್ಯವಿಲ್ಲ",
"sc_na_hint": "ಲಭ್ಯವಿಲ್ಲ ಎಂದರೆ ನಿಮ್ಮ ಭಾಷಣದಿಂದ Gemma ಇದನ್ನು ವಿಶ್ವಾಸಾರ್ಹವಾಗಿ ನಿರ್ಣಯಿಸಲಾಗಲಿಲ್ಲ.",
"sc_stats": "ಭಾಷಣದ ಅಂಕಿಅಂಶಗಳು",
"sc_duration": "ಅವಧಿ",
"sc_seconds": "%1$d ಸೆ",
"sc_pace": "ಅಂದಾಜು ವೇಗ",
"sc_pace_slow": "ನಿಧಾನ",
"sc_pace_normal": "ಸಾಮಾನ್ಯ",
"sc_pace_fast": "ವೇಗ",
"sc_wpm": "ನಿಮಿಷಕ್ಕೆ %1$d ಪದಗಳು",
"sc_fillers": "ತಡೆಯ ಶಬ್ದಗಳು",
"sc_fillers_info": "Gemma ಬರೆದ ಪಠ್ಯದಲ್ಲಿ ಕಂಡ \"um\", \"uh\" ನಂತಹ ತಡೆಗಳು. ಮಾತು ಗುರುತಿಸುವಿಕೆ ಕೆಲವನ್ನು ತಪ್ಪಿಸಬಹುದು, ಆದ್ದರಿಂದ ನಿಜವಾದ ಸಂಖ್ಯೆ ಹೆಚ್ಚಿರಬಹುದು.",
"sc_pauses": "ದೀರ್ಘ ವಿರಾಮಗಳು: %1$d",
"sc_transcript": "Gemma ಕೇಳಿದ್ದು",
"sc_show": "ತೋರಿಸಿ",
"sc_hide": "ಮರೆಮಾಡಿ",
"sc_done": "ಮುಗಿಯಿತು",
"sc_well_title": "ನೀವು ಚೆನ್ನಾಗಿ ಮಾಡಿದ್ದು",
"sc_well_sub": "ಈ ಭಾಷಣದಲ್ಲಿನ ನಿಮ್ಮ ಸಾಮರ್ಥ್ಯಗಳು.",
"sc_none_listed": "ಈ ಬಾರಿ Gemma ಇಲ್ಲಿ ಏನನ್ನೂ ಪಟ್ಟಿ ಮಾಡಲಿಲ್ಲ.",
"sc_improve_title": "ಸುಧಾರಿಸುವುದು ಹೇಗೆ",
"sc_improve_sub": "ನಿಮ್ಮ ಮುಂದಿನ ನಿಮಿಷಕ್ಕೆ ಉಪಯುಕ್ತ ಸಲಹೆಗಳು.",
"sc_fillers_heard": "Gemma ಗಮನಿಸಿದ ತುಂಬು ಪದಗಳು",
"sc_try_pause": "ಬದಲಿಗೆ ಚಿಕ್ಕ ವಿರಾಮ ಕೊಡಿ.",
"sc_try_next": "ಮುಂದಿನ ಬಾರಿ ಇದನ್ನು ಪ್ರಯತ್ನಿಸಿ",
"sc_next_title": "ನಿಮ್ಮ ಮುಂದಿನ 1 ನಿಮಿಷದ ಸವಾಲು",
"sc_next_sub": "ನಿಜವಾದ ಸುಧಾರಣೆಗೆ ನಿರಂತರವಾಗಿ ಅಭ್ಯಾಸ ಮಾಡಿ.",
"sc_next_exercise": "ಅಭ್ಯಾಸ",
"sc_rules": "ನಿಯಮಗಳು",
"sc_rule1": "ಟಿಪ್ಪಣಿ ಇಲ್ಲ",
"sc_rule1_sub": "ಫೋನ್ ಅಥವಾ ಟಿಪ್ಪಣಿ ನೋಡದೆ ಮಾತನಾಡಿ.",
"sc_rule2": "ಸ್ಪಷ್ಟ ರಚನೆ ಬಳಸಿ",
"sc_rule2_sub": "ಮುಖ್ಯ ಅಂಶ, ಉದಾಹರಣೆ, ಮುಕ್ತಾಯ.",
"sc_rule3": "60 ಸೆಕೆಂಡಿನೊಳಗೆ ಮುಗಿಸಿ",
"sc_rule3_sub": "ಸಂಕ್ಷಿಪ್ತವಾಗಿ, ಕೇಂದ್ರೀಕೃತವಾಗಿ ಇರಿ.",
"sc_practise_again": "ಮತ್ತೆ ಅಭ್ಯಾಸ ಮಾಡಿ",
"sc_ran_on": "ಈ ಫೋನ್‌ನಲ್ಲೇ ವಿಶ್ಲೇಷಿಸಲಾಗಿದೆ (%1$s).",
"sc_delete_report": "ಈ ವರದಿ ಅಳಿಸಿ",
"sc_delete_report_q": "ಈ ಭಾಷಣ ವರದಿಯನ್ನು ಅಳಿಸಬೇಕೆ? ಇದನ್ನು ರದ್ದುಮಾಡಲಾಗದು.",
"sc_delete": "ಅಳಿಸಿ",
"sc_not_found": "ಈ ವರದಿ ಈಗ ಇಲ್ಲ.",

"sc_progress_title": "ಭಾಷಣದ ಪ್ರಗತಿ",
"sc_progress_empty": "ನಿಮ್ಮ ಮೊದಲ ವಿಶ್ಲೇಷಿತ ಭಾಷಣದ ನಂತರ ಅಂಕಗಳು ಇಲ್ಲಿ ಕಾಣುತ್ತವೆ.",
"sc_avg": "ಸರಾಸರಿ",
"sc_best": "ಅತ್ಯುತ್ತಮ",
"sc_speeches": "ಭಾಷಣಗಳು",
"sc_since_first": "ಮೊದಲಿನಿಂದ",
"sc_history": "ಇತಿಹಾಸ",
"sc_chart_a11y": "ಅಂಕಗಳ ಚಾರ್ಟ್: %1$d ಭಾಷಣಗಳು, ಇತ್ತೀಚಿನದು 10 ರಲ್ಲಿ %2$s",
"sc_stats_card_summary": "%1$d ಭಾಷಣಗಳು · ಸರಾಸರಿ %2$s",
}

# Privacy policy: the microphone and the coach's reports.
SC_EN.update({
"pp_b_permissions": "• Notifications: to show the reminders you set. Asked only when you choose to turn reminders on.\n• Alarms and reminders: so reminders arrive at the exact time you set. Without it, they may arrive a few minutes late.\n• Run at startup: to set your reminders again after the phone restarts.\n• Fingerprint and face unlock: used only if you turn on the app lock. Android does the check; the app never sees your fingerprint, face or PIN.\n• Physical activity: used only if you turn on step counting in Winter Arc Mode, to read the phone's step counter while the app is open. Steps stay on your phone.\n• Microphone: used only while you record a one-minute speech for the speaking coach. The recording is analysed on your phone and is never uploaded.\nThe app does not ask for location, contacts, camera, photos, files, phone or SMS access. You can change these permissions at any time in Android settings.",
"pp_b_stored": "Only what you enter, plus a few settings the app needs to run:\n• Tasks, subtasks, categories, tags, dates and reminder times.\n• Trackers and their entries, including any study, fitness or health values you choose to log (for example steps, weight, sleep or water).\n• Study plans, topics and daily targets.\n• Books, reading sessions, notes, highlights and insights.\n• Journal reflections and the mood you pick, if you pick one.\n• Speaking coach reports: scores, feedback, simple timing figures and the transcript of your speech. The audio recording is deleted as soon as it is analysed, unless you turn on Keep my recordings.\n• Settings such as your name (optional), language, theme, Home layout, reminder preferences and favourite quotes.\nThe app also reads the date it was installed on your phone, so Statistics never count days before you started.",
"pp_b_network": "Kairos Era does not request the internet permission. There is no account, server, cloud sync, advertising, analytics or crash-reporting service. The speaking coach runs Google's Gemma model inside the app on your phone, from a model file you add yourself; your speech is never sent to Google or anyone else. The developer never receives your data, and the app works the same in airplane mode.",
})
SC_KN.update({
"pp_b_permissions": "• ಅಧಿಸೂಚನೆಗಳು: ನೀವು ಹೊಂದಿಸಿದ ಜ್ಞಾಪನೆಗಳನ್ನು ತೋರಿಸಲು. ನೀವು ಜ್ಞಾಪನೆಗಳನ್ನು ಆನ್ ಮಾಡಲು ಆರಿಸಿದಾಗ ಮಾತ್ರ ಕೇಳಲಾಗುತ್ತದೆ.\n• ಅಲಾರಾಂಗಳು ಮತ್ತು ಜ್ಞಾಪನೆಗಳು: ನೀವು ಹೊಂದಿಸಿದ ನಿಖರ ಸಮಯಕ್ಕೆ ಜ್ಞಾಪನೆಗಳು ಬರಲು. ಇದಿಲ್ಲದಿದ್ದರೆ ಕೆಲವು ನಿಮಿಷ ತಡವಾಗಿ ಬರಬಹುದು.\n• ಆರಂಭದಲ್ಲಿ ಚಲಾಯಿಸುವಿಕೆ: ಫೋನ್ ಮರುಪ್ರಾರಂಭವಾದ ನಂತರ ನಿಮ್ಮ ಜ್ಞಾಪನೆಗಳನ್ನು ಮತ್ತೆ ಹೊಂದಿಸಲು.\n• ಬೆರಳಚ್ಚು ಮತ್ತು ಮುಖ ಅನ್‌ಲಾಕ್: ನೀವು ಆ್ಯಪ್ ಲಾಕ್ ಆನ್ ಮಾಡಿದರೆ ಮಾತ್ರ ಬಳಸಲಾಗುತ್ತದೆ. ಪರಿಶೀಲನೆಯನ್ನು Android ಮಾಡುತ್ತದೆ; ಆ್ಯಪ್‌ಗೆ ನಿಮ್ಮ ಬೆರಳಚ್ಚು, ಮುಖ ಅಥವಾ PIN ಎಂದಿಗೂ ಕಾಣುವುದಿಲ್ಲ.\n• ದೈಹಿಕ ಚಟುವಟಿಕೆ: ವಿಂಟರ್ ಆರ್ಕ್ ಮೋಡ್‌ನಲ್ಲಿ ಹೆಜ್ಜೆ ಎಣಿಕೆಯನ್ನು ಆನ್ ಮಾಡಿದರೆ ಮಾತ್ರ, ಆ್ಯಪ್ ತೆರೆದಿರುವಾಗ ಫೋನ್‌ನ ಹೆಜ್ಜೆ ಎಣಿಕೆಯನ್ನು ಓದಲು. ಹೆಜ್ಜೆಗಳು ನಿಮ್ಮ ಫೋನ್‌ನಲ್ಲೇ ಇರುತ್ತವೆ.\n• ಮೈಕ್ರೊಫೋನ್: ಮಾತಿನ ತರಬೇತುದಾರರಿಗಾಗಿ ಒಂದು ನಿಮಿಷದ ಭಾಷಣ ರೆಕಾರ್ಡ್ ಮಾಡುವಾಗ ಮಾತ್ರ ಬಳಸಲಾಗುತ್ತದೆ. ರೆಕಾರ್ಡಿಂಗ್ ಅನ್ನು ನಿಮ್ಮ ಫೋನ್‌ನಲ್ಲೇ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತದೆ, ಎಂದಿಗೂ ಅಪ್‌ಲೋಡ್ ಆಗುವುದಿಲ್ಲ.\nಆ್ಯಪ್ ಸ್ಥಳ, ಸಂಪರ್ಕಗಳು, ಕ್ಯಾಮೆರಾ, ಫೋಟೋಗಳು, ಫೈಲ್‌ಗಳು, ಫೋನ್ ಅಥವಾ SMS ಪ್ರವೇಶವನ್ನು ಕೇಳುವುದಿಲ್ಲ. ಈ ಅನುಮತಿಗಳನ್ನು Android ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಯಾವಾಗ ಬೇಕಾದರೂ ಬದಲಿಸಬಹುದು.",
"pp_b_stored": "ನೀವು ನಮೂದಿಸುವುದನ್ನು ಮಾತ್ರ, ಜೊತೆಗೆ ಆ್ಯಪ್ ನಡೆಯಲು ಬೇಕಾದ ಕೆಲವು ಸೆಟ್ಟಿಂಗ್‌ಗಳು:\n• ಕಾರ್ಯಗಳು, ಉಪಕಾರ್ಯಗಳು, ವರ್ಗಗಳು, ಟ್ಯಾಗ್‌ಗಳು, ದಿನಾಂಕಗಳು ಮತ್ತು ಜ್ಞಾಪನೆಯ ಸಮಯಗಳು.\n• ಟ್ರ್ಯಾಕರ್‌ಗಳು ಮತ್ತು ಅವುಗಳ ನಮೂದುಗಳು, ನೀವು ದಾಖಲಿಸಲು ಆಯ್ಕೆ ಮಾಡುವ ಅಧ್ಯಯನ, ಫಿಟ್‌ನೆಸ್ ಅಥವಾ ಆರೋಗ್ಯ ಮೌಲ್ಯಗಳೂ ಸೇರಿ (ಉದಾಹರಣೆಗೆ ಹೆಜ್ಜೆಗಳು, ತೂಕ, ನಿದ್ರೆ ಅಥವಾ ನೀರು).\n• ಅಧ್ಯಯನ ಯೋಜನೆಗಳು, ವಿಷಯಗಳು ಮತ್ತು ದೈನಂದಿನ ಗುರಿಗಳು.\n• ಪುಸ್ತಕಗಳು, ಓದಿನ ಅವಧಿಗಳು, ಟಿಪ್ಪಣಿಗಳು, ಮುಖ್ಯಾಂಶಗಳು ಮತ್ತು ಒಳನೋಟಗಳು.\n• ದಿನಚರಿಯ ಚಿಂತನೆಗಳು ಮತ್ತು ನೀವು ಆರಿಸಿದರೆ ನಿಮ್ಮ ಮನಸ್ಥಿತಿ.\n• ಮಾತಿನ ತರಬೇತುದಾರರ ವರದಿಗಳು: ಅಂಕಗಳು, ಪ್ರತಿಕ್ರಿಯೆ, ಸರಳ ಸಮಯದ ಅಂಕಿಗಳು ಮತ್ತು ನಿಮ್ಮ ಭಾಷಣದ ಪಠ್ಯ. ನೀವು \"ನನ್ನ ರೆಕಾರ್ಡಿಂಗ್‌ಗಳನ್ನು ಉಳಿಸಿ\" ಆನ್ ಮಾಡದಿದ್ದರೆ, ವಿಶ್ಲೇಷಣೆಯಾದ ತಕ್ಷಣ ಧ್ವನಿ ರೆಕಾರ್ಡಿಂಗ್ ಅಳಿಸಲಾಗುತ್ತದೆ.\n• ನಿಮ್ಮ ಹೆಸರು (ಐಚ್ಛಿಕ), ಭಾಷೆ, ಥೀಮ್, ಮುಖಪುಟದ ವಿನ್ಯಾಸ, ಜ್ಞಾಪನೆಯ ಆದ್ಯತೆಗಳು ಮತ್ತು ಮೆಚ್ಚಿನ ಉಲ್ಲೇಖಗಳಂತಹ ಸೆಟ್ಟಿಂಗ್‌ಗಳು.\nನೀವು ಪ್ರಾರಂಭಿಸುವ ಮೊದಲಿನ ದಿನಗಳನ್ನು ಅಂಕಿಅಂಶಗಳು ಎಣಿಸದಿರಲು, ಆ್ಯಪ್ ನಿಮ್ಮ ಫೋನ್‌ನಲ್ಲಿ ಸ್ಥಾಪಿಸಿದ ದಿನಾಂಕವನ್ನೂ ಓದುತ್ತದೆ.",
"pp_b_network": "ಕೈರೋಸ್ ಎರಾ ಇಂಟರ್ನೆಟ್ ಅನುಮತಿಯನ್ನು ಕೇಳುವುದಿಲ್ಲ. ಯಾವುದೇ ಖಾತೆ, ಸರ್ವರ್, ಕ್ಲೌಡ್ ಸಿಂಕ್, ಜಾಹೀರಾತು, ವಿಶ್ಲೇಷಣೆ ಅಥವಾ ಕ್ರ್ಯಾಶ್-ವರದಿ ಸೇವೆ ಇಲ್ಲ. ಮಾತಿನ ತರಬೇತುದಾರ ನೀವೇ ಸೇರಿಸುವ ಮಾದರಿ ಫೈಲ್‌ನಿಂದ Google ನ Gemma ಮಾದರಿಯನ್ನು ನಿಮ್ಮ ಫೋನ್‌ನಲ್ಲಿ ಆ್ಯಪ್‌ನೊಳಗೇ ಚಲಾಯಿಸುತ್ತದೆ; ನಿಮ್ಮ ಮಾತು Google ಅಥವಾ ಬೇರೆ ಯಾರಿಗೂ ಕಳುಹಿಸಲಾಗುವುದಿಲ್ಲ. ಡೆವಲಪರ್‌ಗೆ ನಿಮ್ಮ ಮಾಹಿತಿ ಎಂದಿಗೂ ತಲುಪುವುದಿಲ್ಲ, ಮತ್ತು ಏರ್‌ಪ್ಲೇನ್ ಮೋಡ್‌ನಲ್ಲೂ ಆ್ಯಪ್ ಹಾಗೆಯೇ ಕೆಲಸ ಮಾಡುತ್ತದೆ.",
})
