# Source of truth for UI text in English (en) and Kannada (kn).
# Run `python3 tools/gen_strings.py` to regenerate app/src/main/res/values*/strings.xml.
EN = {
"app_name": "Kairos Era",
"app_name_display": "KAIROS ERA",
"tagline": "RIGHT TIME. A BETTER YOU.",
"nav_home": "Home", "nav_today": "Today", "nav_track": "Track", "nav_read": "Read", "nav_more": "More",
"greeting_morning": "Good morning", "greeting_afternoon": "Good afternoon", "greeting_evening": "Good evening", "greeting_night": "Good night",
"home_subtitle": "Let's make today count.",
"home_customize": "Customize Home", "home_customize_summary": "Choose which cards appear on Home and in what order.",
"home_today_progress": "Today's progress", "home_tasks": "Tasks", "home_tasks_done": "%1$d / %2$d completed",
"home_progress_a11y": "Today's progress: %1$d of %2$d tasks completed",
"home_nothing_planned": "Nothing planned yet.", "home_all_done": "Everything planned is done.", "home_remaining": "%1$d left today",
"home_next_up": "Next up", "home_next_empty": "Your day is open. Add one useful thing.", "home_next_clear": "Nothing left for now. Well done.",
"home_daily_motivation": "Daily motivation", "home_trackers": "Trackers",
"home_open_today": "Open today's plan",
"quote_action": "Today: %1$s", "quote_favorite": "Save quote to favorites", "quote_unfavorite": "Remove quote from favorites",
"all_day": "All day", "all_day_short": "Any time",
"quick_add_title": "What do you want to add?", "quick_add_soon_note": "Journal arrives in the next update.",
"quick_add_task": "Task", "quick_add_tracker": "Tracker", "quick_add_book": "Book", "quick_add_journal": "Journal", "quick_add_study": "Study",
"yesterday": "Yesterday", "today": "Today", "tomorrow": "Tomorrow",
"mode_day": "Day", "mode_week": "Week", "mode_month": "Month",
"previous": "Previous", "next": "Next", "pick_date": "Pick a date",
"day_empty_title": "A clear day", "day_empty_body": "Nothing is planned for this day. Tap + to add a task.",
"week_day_free": "Free", "month_legend": "A filled green dot means everything planned was done. An orange dot means tasks are planned; it gets stronger as more are done.",
"month_cell_a11y": "Day %1$d, %2$d of %3$d done",
"subtasks_count": "%1$d/%2$d steps", "skipped": "Moved", "example_badge": "Example", "repeats": "Repeats", "has_reminder": "Has a reminder",
"edit": "Edit", "move_to_trash": "Move to Trash", "task_moved_to_trash": "Moved to Trash", "undo": "Undo",
"priority_none": "None", "priority_low": "Low", "priority_medium": "Medium", "priority_high": "High",
"new_task": "New task", "edit_task": "Edit task", "save": "Save", "close": "Close", "cancel": "Cancel", "ok": "OK", "back": "Back", "clear": "Clear",
"retry": "Try again", "optional": "Optional",
"field_title": "Title", "field_description": "Description", "field_notes": "Notes", "field_tags": "Tags", "field_tags_hint": "Separate with commas",
"section_when": "When", "section_repeat": "Repeat", "section_reminders": "Reminders", "section_priority": "Priority", "section_category": "Category", "section_subtasks": "Steps",
"starts_at": "Starts %1$s", "ends_at": "Ends %1$s", "add_end_time": "Add end time", "remove_end_time": "Remove end time",
"repeat_none": "Once", "repeat_daily": "Daily", "repeat_weekdays": "Weekdays", "repeat_weekly": "Weekly", "repeat_monthly": "Monthly", "repeat_yearly": "Yearly",
"repeat_every": "Every %1$d", "repeat_until": "Until %1$s", "repeat_forever": "No end date",
"add_reminder": "Add reminder", "remove_reminder": "Remove reminder", "reminder_at_start": "At start time", "reminder_before": "%1$d min before",
"reminder_custom_time": "At a specific time…", "reminder_at": "At %1$s", "reminder_persistent": "Keep until I act",
"add_subtask": "Add a step", "remove_subtask": "Remove step",
"example_note": "This is an example task. You can edit it or remove all examples in Settings.",
"error_title_empty": "Give the task a title.", "error_title_long": "Keep the title under %1$d characters.",
"error_end_before_start": "The end time is before the start time.", "error_reminder_needs_time": "\"Before start\" reminders need a start time.",
"error_too_many_reminders": "Up to %1$d reminders per task.",
"error_title": "Something went wrong", "error_body": "Your data is safe. Please try again.", "error_save_body": "The task could not be saved. Nothing was lost; please try again.",
"error_action_failed": "That didn't work. Please try again.",
"task_missing": "This task no longer exists", "task_missing_body": "It may have been deleted or moved to Trash.",
"trash_confirm_body": "The task moves to Trash. You can restore it from More > Trash.",
"reschedule_title": "Reschedule", "reschedule_recurring_note": "Only this occurrence moves. The repeating plan stays as it is.",
"action_done": "Done", "action_snooze": "Snooze", "action_reschedule": "Reschedule",
"reminder_label": "Task", "reminder_all_day": "Today", "reminder_public_title": "Kairos Era reminder",
"channel_group_reminders": "Task reminders", "channel_default": "Reminders (default sound)", "channel_general": "General",
"channel_reminders_description": "Reminders for tasks you scheduled.",
"sound_default": "Default", "sound_kairos_bell": "Kairos Bell", "sound_soft_chime": "Soft Chime", "sound_focus": "Focus", "sound_silent": "Silent",
"settings": "Settings", "settings_summary": "Language, appearance, notifications, sounds", "calendar": "Calendar", "calendar_summary": "Month view of your plan",
"trash": "Trash", "trash_summary": "Restore deleted tasks, trackers and books", "privacy": "Privacy", "privacy_summary": "Your data stays on this device",
"about": "About", "about_summary": "Kairos Era and what it stands for", "coming_next": "Coming next", "soon": "In a coming update",
"journal": "Journal", "statistics": "Statistics", "backup": "Backup", "diagnostics": "Diagnostics",
"settings_general": "General", "settings_language": "Language", "language_system": "Phone language", "language_english": "English", "language_kannada": "ಕನ್ನಡ",
"settings_appearance": "Appearance", "theme_system": "System", "theme_light": "Light", "theme_dark": "Dark",
"dynamic_color": "Wallpaper colors", "dynamic_color_summary": "Use colors from your wallpaper instead of the Kairos palette.",
"settings_notifications": "Notifications", "notif_permission": "Notifications", "status_allowed": "Allowed", "status_off": "Off", "allow": "Allow",
"notif_permission_off_body": "Reminders can't appear until notifications are allowed. Everything else works normally.",
"exact_alarms": "On-time reminders", "exact_alarms_off_body": "Without this, Android may deliver reminders a few minutes late to save battery.",
"open_settings": "Open settings", "battery_title": "Battery optimization",
"battery_body": "Some phones stop apps in the background. If reminders arrive late, allow Kairos Era to run without restrictions.",
"test_notification": "Send a test notification", "test_notification_summary": "Check sound and appearance.",
"test_notification_title": "Kairos Era", "test_notification_text": "Notifications are working.",
"settings_sounds": "Sounds", "default_sound": "Default sound for new reminders",
"sound_channel_note": "Android lets you change each sound's volume, vibration and importance in system settings. Your choices there are respected.",
"open_sound_settings": "Open notification settings",
"default_persistent": "Keep reminders until I act", "default_persistent_summary": "New reminders stay in the notification shade until you tap Done, Snooze or Reschedule.",
"snooze_length": "Snooze length", "minutes_short": "%1$d min",
"settings_data": "Data", "add_examples": "Add example content", "add_examples_summary": "A few sample tasks so you can see how things look.",
"remove_examples": "Remove examples", "remove_examples_summary": "Moves all example tasks to Trash.", "remove_examples_confirm": "Move all example tasks to Trash? You can restore them later.",
"settings_footer": "Kairos Era works fully offline. It has no account, no cloud sync, no analytics and no ads.",
"move_up": "Move up", "move_down": "Move down",
"trash_empty_title": "Trash is empty", "trash_empty_body": "Deleted tasks, trackers and books wait here until you restore them or delete them forever.",
"trash_explainer": "Items stay in Trash until you choose. Nothing is removed automatically.",
"restore": "Restore", "delete_forever": "Delete forever", "delete_forever_title": "Delete forever?",
"delete_forever_body": "\"%1$s\" will be permanently deleted. This can't be undone.", "deleted_on": "Deleted %1$s",
"privacy_headline": "Your data stays on this device.",
"privacy_point_device": "Everything you write (tasks, notes, reminders) is stored only in this app's private storage on your phone.",
"privacy_point_account": "There is no account and no sign-in.",
"privacy_point_cloud": "There is no cloud sync and no server. Kairos Era never uploads your data.",
"privacy_point_network": "The app does not even request internet access, so it works the same in airplane mode.",
"privacy_point_storage": "Other apps cannot read this app's private storage.",
"privacy_point_logs": "Diagnostic logs never contain your task titles, notes or other personal text.",
"privacy_point_lock": "An optional app lock using your phone's fingerprint, face or screen lock is coming in a future update.",
"privacy_point_backup": "Local backup files you control are coming in a future update. Android's automatic cloud backup is turned off for this app.",
"privacy_point_diagnostics": "If the app ever crashes, you will be asked before any report is shared, and it will contain no personal data.",
"about_philosophy": "Plan your day. Learn something. Move your body. Read something meaningful. Reflect. Repeat.",
"about_meaning": "Kairos is the Greek idea of the right, opportune moment. The emblem is a path moving toward a rising sun: a new day, steady progress, and growth.",
"about_version": "Version %1$s",
"onboarding_welcome": "Your time is yours.", "onboarding_private": "Private: only you can see your plans.", "onboarding_local": "Local: everything is stored on this phone.",
"onboarding_no_account": "No account, no sign-in.", "onboarding_no_cloud": "No cloud sync, no tracking, no ads.",
"onboarding_begin": "Begin", "onboarding_about_you": "A little about you", "onboarding_name_label": "Name or nickname",
"onboarding_focus": "What do you want to focus on?", "focus_learning": "Learning", "focus_health": "Health", "focus_reading": "Reading", "focus_work": "Work",
"focus_personal": "Personal", "focus_custom": "Something else",
"onboarding_first_task": "One thing to do today", "onboarding_first_task_hint": "Optional. You can add more later.",
"onboarding_examples": "Show example tasks (you can remove them anytime)",
"onboarding_reminders_title": "Reminders", "onboarding_reminders_body": "Kairos Era can remind you when a task is due. Notifications are the only permission it asks for, and you can change this anytime.",
"onboarding_allow_reminders": "Allow reminders", "onboarding_not_now": "Not now",
"sample_java": "Java: Collections", "sample_java_1": "List and ArrayList", "sample_java_2": "HashMap internals", "sample_java_3": "Solve 3 problems",
"sample_walk": "Morning walk", "sample_project": "Project work", "sample_workout": "Workout", "sample_read": "Read 20 pages", "sample_reflection": "Daily reflection",
# Phase 2: trackers, study, reading
"add": "Add", "yes": "Yes", "no": "No", "see_all": "See all", "color_option": "Colour %1$d",
"new_tracker": "New tracker", "edit_tracker": "Edit tracker",
"track_empty_title": "Track what matters to you", "track_empty_body": "Study, workouts, sleep, water, habits, projects or anything else. Pick a template or build your own.",
"track_today_summary": "Today: %1$d of %2$d done",
"tracker_card_a11y": "%1$s, %2$d%% today, streak %3$d",
"tracker_rest_day": "Not planned for today", "tracker_done_today": "Done", "tracker_percent_today": "%1$d%% today",
"template_pick_title": "Start a tracker", "template_pick_body": "Templates are only a starting point. You can rename, add or switch off any field.",
"template_study": "Study", "template_study_summary": "Study time, practice and a topic plan with daily targets",
"template_fitness": "Fitness", "template_fitness_summary": "Workout, steps, sleep, water, energy and mood",
"template_reading": "Reading goal", "template_reading_summary": "Pages and minutes read each day",
"template_habit": "Habit", "template_habit_summary": "One simple yes or no each day",
"template_project": "Project", "template_project_summary": "Time spent, progress and the next step",
"template_finance": "Money", "template_finance_summary": "Track spending and no-spend days",
"template_learning": "Learning a skill", "template_learning_summary": "Practice time and what you learned",
"template_health": "Health", "template_health_summary": "Water, sleep, medicine and energy",
"template_personal": "Personal growth", "template_personal_summary": "Meditation, screen-free time and gratitude",
"template_custom": "Custom", "template_custom_summary": "Start from a blank tracker",
"tf_study_time": "Study time", "tf_practice": "Practice problems", "tf_revision": "Revision done", "tf_notes": "Notes",
"tf_workout": "Workout done", "tf_steps": "Steps", "tf_workout_minutes": "Workout time", "tf_sleep": "Sleep", "tf_water": "Water",
"tf_walk": "Walk", "tf_stretching": "Stretching", "tf_energy": "Energy", "tf_mood": "Mood", "tf_weight": "Weight",
"tf_pages": "Pages read", "tf_reading_minutes": "Reading time", "tf_done": "Done",
"tf_worked_on_it": "Worked on it", "tf_time_spent": "Time spent", "tf_progress": "Progress", "tf_next_step": "Next step",
"tf_tracked_spending": "Wrote down spending", "tf_no_spend": "No-spend day",
"tf_practice_time": "Practice time", "tf_learned_count": "New things learned",
"tf_medicine": "Medicine taken", "tf_meditation": "Meditation", "tf_screen_free": "Screen-free hour", "tf_gratitude": "Grateful for",
"unit_steps": "steps", "unit_hours": "h", "unit_litres": "L", "unit_kg": "kg", "unit_pages": "pages", "unit_minutes": "min",
"tracker_missing": "This tracker no longer exists", "tracker_missing_body": "It may have been moved to Trash.",
"tracker_trash_body": "The tracker and its history move to Trash. You can restore them from More > Trash.",
"tracker_why_line": "Why: %1$s", "tracker_gain_line": "What I gain: %1$s",
"tracker_log": "Log", "tracker_no_fields": "This tracker has no active fields. Edit it to add one.",
"field_target_line": "Target %1$s %2$s",
"tracker_stats": "Progress", "stat_current_streak": "Current streak", "stat_best_streak": "Best streak",
"stat_completion_30": "Done in the last 30 days", "stat_active_days": "Days with any progress",
"tracker_missed_yesterday": "Yesterday was missed. That's fine: every day is a fresh start.",
"tracker_history": "Last 5 weeks", "history_cell_a11y": "%1$s, %2$d%%",
"tracker_name": "Name", "error_tracker_name": "Give the tracker a name.",
"tracker_icon": "Icon", "tracker_color": "Colour",
"tracker_why": "Why this matters", "tracker_why_hint": "e.g. I want to switch to a backend role",
"tracker_gain": "What I will gain", "tracker_gain_hint": "e.g. Confidence in interviews",
"tracker_frequency": "How often", "freq_daily": "Every day", "freq_selected_days": "Some days", "freq_per_week": "Times a week", "freq_per_month": "Times a month",
"freq_times_week": "%1$d times a week", "freq_times_month": "%1$d times a month",
"tracker_fields": "What to track", "tracker_fields_note": "The first field is the main goal: completing it completes the day. Removed fields keep their history.",
"error_tracker_fields": "Switch on at least one field.", "error_checklist_empty": "A checklist needs at least one item.",
"add_field": "Add field", "edit_field": "Edit field", "field_label": "Label", "field_type": "Type",
"field_target": "Daily target", "field_target_hint": "Optional. Leave empty if any amount counts.", "field_unit": "Unit",
"checklist_options": "Items, one per line", "checklist_items": "%1$d items", "field_off": "Off",
"remove_field": "Remove field", "remove_field_note": "Past values are kept; the field is only hidden.",
"type_checkbox": "Yes / no", "type_number": "Number", "type_decimal": "Decimal", "type_duration": "Minutes", "type_pages": "Pages",
"type_percentage": "Percent", "type_rating": "Rating 1-5", "type_text": "Text", "type_checklist": "Checklist",
"study_plan_for_day": "Study plan", "study_plan_note": "Ticking a target records practice on its topic. You decide when a topic is done.",
"add_study_target": "Add target", "remove_target": "Remove target", "study_target_hint": "What will you study?", "study_target_topic": "Topic: %1$s",
"study_topics": "Topics", "study_topics_done": "%1$d of %2$d done", "study_topics_empty": "Break your subject into topics, e.g. Java Core > Collections.",
"add_topic": "Add topic", "edit_topic": "Edit topic", "delete_topic": "Delete topic",
"delete_topic_body": "The topic is deleted. Its sub-topics move up one level and targets keep their text.",
"topic_status": "Status", "topic_not_started": "Not started", "topic_learning": "Learning", "topic_reviewing": "Reviewing", "topic_done": "Done",
"topic_confidence": "Confidence", "topic_resources": "Resources", "topic_questions": "Questions to answer",
"topic_parent": "Inside: %1$s", "topic_no_parent": "None", "topic_practice_count": "%1$d practice",
"add_book": "Add book", "edit_book": "Edit book",
"read_empty_title": "Read, understand, remember, apply", "read_empty_body": "Add a book to track pages and capture why you started, what you learned and what you applied.",
"reading_this_week": "This week", "pages_today": "Pages today", "pages_week": "Pages this week", "minutes_week": "Minutes this week",
"reading_days_line": "Read on %1$d days this week · %2$d books finished this year",
"shelf_reading": "Reading now", "shelf_paused": "Paused", "shelf_want": "Want to read", "shelf_finished": "Finished",
"status_want": "Want to read", "status_reading": "Reading", "status_paused": "Paused", "status_finished": "Finished",
"book_page_of": "Page %1$d of %2$d", "book_page_of_percent": "Page %1$d of %2$d (%3$d%%)", "book_page_only": "Page %1$d",
"book_pages_per_day": "%1$d pages a day to finish on time",
"book_progress": "Progress", "book_target_line": "Target: %1$s", "book_finished_on": "Finished %1$s",
"log_reading": "Log reading", "pages_read": "Pages read", "minutes_read": "Minutes (optional)",
"book_insights": "What this book gives you", "book_insights_note": "Saved automatically as you type.",
"insight_why": "Why I started", "insight_expected": "What I expected", "insight_learned": "What I learned",
"insight_key_ideas": "Key ideas", "insight_applied": "What I applied", "insight_changed": "What changed in me",
"insight_skills": "Skills I improved", "insight_takeaway": "Final takeaway", "insight_recommend": "Would I read it again?",
"book_notes": "Notes and highlights", "book_notes_empty": "Capture a highlight, a note or a lesson while you read.",
"add_note": "Add", "delete_note": "Delete note", "note_kind_note": "Note", "note_kind_highlight": "Highlight", "note_kind_lesson": "Lesson",
"note_text": "Text", "note_page": "Page (optional)", "page_short": "p. %1$d",
"book_sessions": "Reading sessions", "book_sessions_empty": "No sessions yet.", "session_line": "%1$d pages · %2$d min",
"delete_session": "Delete session", "delete_session_body": "Delete this session? Its pages are taken off your bookmark.",
"book_missing": "This book no longer exists", "book_missing_body": "It may have been moved to Trash.",
"book_trash_body": "The book, its notes and sessions move to Trash. You can restore them from More > Trash.",
"book_title": "Title", "book_author": "Author", "book_total_pages": "Total pages", "book_current_page": "Current page",
"book_status": "Status", "book_target_date": "Finish by", "book_no_target": "No target date",
"error_book_title": "Give the book a title.", "error_page_beyond": "The current page is past the last page.",
"home_trackers_line": "Trackers: %1$d of %2$d done", "home_reading_line": "Reading: %1$d pages today · %2$s",
"home_trackers_empty": "No trackers yet. Tap to create one for study, fitness or a habit.",
"home_trackers_rest": "Nothing is planned for today. Enjoy the rest.",
"trash_kind_task": "Task", "trash_kind_tracker": "Tracker", "trash_kind_book": "Book",
"delete_forever_body_history": "\"%1$s\" and all its history will be permanently deleted. This can't be undone.",
"sample_fitness_why": "More energy for everything else", "sample_study_name": "Java backend",
"sample_study_why": "To become confident in backend interviews",
"sample_topic_core": "Java Core", "sample_topic_collections": "Collections", "sample_topic_oop": "OOP basics",
"sample_topic_streams": "Streams and lambdas", "sample_topic_spring": "Spring Boot",
"sample_target_1": "Read about HashMap internals", "sample_target_2": "Solve 2 collection problems",
"sample_book_title": "Atomic Habits", "sample_book_author": "James Clear", "sample_book_why": "To build habits that last",
}

KN = {
"app_name": "ಕೈರೋಸ್ ಎರಾ",
"app_name_display": "KAIROS ERA",
"tagline": "ಸರಿಯಾದ ಸಮಯ. ಉತ್ತಮ ನೀವು.",
"nav_home": "ಮುಖಪುಟ", "nav_today": "ಇಂದು", "nav_track": "ಟ್ರ್ಯಾಕ್", "nav_read": "ಓದು", "nav_more": "ಇನ್ನಷ್ಟು",
"greeting_morning": "ಶುಭೋದಯ", "greeting_afternoon": "ಶುಭ ಮಧ್ಯಾಹ್ನ", "greeting_evening": "ಶುಭ ಸಂಜೆ", "greeting_night": "ಶುಭ ರಾತ್ರಿ",
"home_subtitle": "ಇಂದಿನ ದಿನವನ್ನು ಅರ್ಥಪೂರ್ಣವಾಗಿಸೋಣ.",
"home_customize": "ಮುಖಪುಟ ಹೊಂದಿಸಿ", "home_customize_summary": "ಮುಖಪುಟದಲ್ಲಿ ಯಾವ ಕಾರ್ಡ್‌ಗಳು ಯಾವ ಕ್ರಮದಲ್ಲಿ ಕಾಣಬೇಕು ಎಂದು ಆಯ್ಕೆಮಾಡಿ.",
"home_today_progress": "ಇಂದಿನ ಪ್ರಗತಿ", "home_tasks": "ಕಾರ್ಯಗಳು", "home_tasks_done": "%1$d / %2$d ಪೂರ್ಣಗೊಂಡಿವೆ",
"home_progress_a11y": "ಇಂದಿನ ಪ್ರಗತಿ: %2$d ಕಾರ್ಯಗಳಲ್ಲಿ %1$d ಪೂರ್ಣಗೊಂಡಿವೆ",
"home_nothing_planned": "ಇನ್ನೂ ಏನೂ ಯೋಜಿಸಿಲ್ಲ.", "home_all_done": "ಯೋಜಿಸಿದ್ದೆಲ್ಲವೂ ಪೂರ್ಣಗೊಂಡಿದೆ.", "home_remaining": "ಇಂದು ಇನ್ನೂ %1$d ಬಾಕಿ",
"home_next_up": "ಮುಂದಿನದು", "home_next_empty": "ನಿಮ್ಮ ದಿನ ಖಾಲಿಯಿದೆ. ಒಂದು ಉಪಯುಕ್ತ ಕೆಲಸ ಸೇರಿಸಿ.", "home_next_clear": "ಸದ್ಯಕ್ಕೆ ಏನೂ ಬಾಕಿ ಇಲ್ಲ. ಚೆನ್ನಾಗಿದೆ.",
"home_daily_motivation": "ದಿನದ ಪ್ರೇರಣೆ", "home_trackers": "ಟ್ರ್ಯಾಕರ್‌ಗಳು",
"home_open_today": "ಇಂದಿನ ಯೋಜನೆ ತೆರೆಯಿರಿ",
"quote_action": "ಇಂದು: %1$s", "quote_favorite": "ಉಲ್ಲೇಖವನ್ನು ಮೆಚ್ಚಿನವುಗಳಿಗೆ ಸೇರಿಸಿ", "quote_unfavorite": "ಉಲ್ಲೇಖವನ್ನು ಮೆಚ್ಚಿನವುಗಳಿಂದ ತೆಗೆಯಿರಿ",
"all_day": "ಇಡೀ ದಿನ", "all_day_short": "ಯಾವಾಗ ಬೇಕಾದರೂ",
"quick_add_title": "ಏನನ್ನು ಸೇರಿಸಲು ಬಯಸುವಿರಿ?", "quick_add_soon_note": "ದಿನಚರಿ ಮುಂದಿನ ಅಪ್‌ಡೇಟ್‌ನಲ್ಲಿ ಬರಲಿದೆ.",
"quick_add_task": "ಕಾರ್ಯ", "quick_add_tracker": "ಟ್ರ್ಯಾಕರ್", "quick_add_book": "ಪುಸ್ತಕ", "quick_add_journal": "ದಿನಚರಿ", "quick_add_study": "ಅಧ್ಯಯನ",
"yesterday": "ನಿನ್ನೆ", "today": "ಇಂದು", "tomorrow": "ನಾಳೆ",
"mode_day": "ದಿನ", "mode_week": "ವಾರ", "mode_month": "ತಿಂಗಳು",
"previous": "ಹಿಂದಿನದು", "next": "ಮುಂದೆ", "pick_date": "ದಿನಾಂಕ ಆರಿಸಿ",
"day_empty_title": "ಖಾಲಿ ದಿನ", "day_empty_body": "ಈ ದಿನಕ್ಕೆ ಏನೂ ಯೋಜಿಸಿಲ್ಲ. ಕಾರ್ಯ ಸೇರಿಸಲು + ಒತ್ತಿ.",
"week_day_free": "ಖಾಲಿ", "month_legend": "ತುಂಬಿದ ಹಸಿರು ಚುಕ್ಕೆ ಎಂದರೆ ಯೋಜಿಸಿದ್ದೆಲ್ಲವೂ ಮುಗಿದಿದೆ. ಕಿತ್ತಳೆ ಚುಕ್ಕೆ ಎಂದರೆ ಕಾರ್ಯಗಳಿವೆ; ಹೆಚ್ಚು ಮುಗಿದಂತೆ ಅದು ಗಾಢವಾಗುತ್ತದೆ.",
"month_cell_a11y": "ದಿನ %1$d, %3$d ರಲ್ಲಿ %2$d ಮುಗಿದಿವೆ",
"subtasks_count": "%1$d/%2$d ಹಂತಗಳು", "skipped": "ಸ್ಥಳಾಂತರಿಸಲಾಗಿದೆ", "example_badge": "ಉದಾಹರಣೆ", "repeats": "ಪುನರಾವರ್ತನೆ", "has_reminder": "ಜ್ಞಾಪನೆ ಇದೆ",
"edit": "ತಿದ್ದಿ", "move_to_trash": "ಕಸದ ಬುಟ್ಟಿಗೆ ಸರಿಸಿ", "task_moved_to_trash": "ಕಸದ ಬುಟ್ಟಿಗೆ ಸರಿಸಲಾಗಿದೆ", "undo": "ರದ್ದುಮಾಡಿ",
"priority_none": "ಯಾವುದೂ ಇಲ್ಲ", "priority_low": "ಕಡಿಮೆ", "priority_medium": "ಮಧ್ಯಮ", "priority_high": "ಹೆಚ್ಚು",
"new_task": "ಹೊಸ ಕಾರ್ಯ", "edit_task": "ಕಾರ್ಯ ತಿದ್ದಿ", "save": "ಉಳಿಸಿ", "close": "ಮುಚ್ಚಿ", "cancel": "ರದ್ದು", "ok": "ಸರಿ", "back": "ಹಿಂದೆ", "clear": "ತೆರವುಗೊಳಿಸಿ",
"retry": "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ", "optional": "ಐಚ್ಛಿಕ",
"field_title": "ಶೀರ್ಷಿಕೆ", "field_description": "ವಿವರಣೆ", "field_notes": "ಟಿಪ್ಪಣಿಗಳು", "field_tags": "ಟ್ಯಾಗ್‌ಗಳು", "field_tags_hint": "ಅಲ್ಪವಿರಾಮದಿಂದ ಬೇರ್ಪಡಿಸಿ",
"section_when": "ಯಾವಾಗ", "section_repeat": "ಪುನರಾವರ್ತನೆ", "section_reminders": "ಜ್ಞಾಪನೆಗಳು", "section_priority": "ಆದ್ಯತೆ", "section_category": "ವರ್ಗ", "section_subtasks": "ಹಂತಗಳು",
"starts_at": "ಆರಂಭ %1$s", "ends_at": "ಮುಕ್ತಾಯ %1$s", "add_end_time": "ಮುಕ್ತಾಯ ಸಮಯ ಸೇರಿಸಿ", "remove_end_time": "ಮುಕ್ತಾಯ ಸಮಯ ತೆಗೆಯಿರಿ",
"repeat_none": "ಒಮ್ಮೆ", "repeat_daily": "ಪ್ರತಿದಿನ", "repeat_weekdays": "ವಾರದ ದಿನಗಳು", "repeat_weekly": "ಪ್ರತಿವಾರ", "repeat_monthly": "ಪ್ರತಿ ತಿಂಗಳು", "repeat_yearly": "ಪ್ರತಿ ವರ್ಷ",
"repeat_every": "ಪ್ರತಿ %1$d", "repeat_until": "%1$s ರವರೆಗೆ", "repeat_forever": "ಕೊನೆಯ ದಿನಾಂಕವಿಲ್ಲ",
"add_reminder": "ಜ್ಞಾಪನೆ ಸೇರಿಸಿ", "remove_reminder": "ಜ್ಞಾಪನೆ ತೆಗೆಯಿರಿ", "reminder_at_start": "ಆರಂಭದ ಸಮಯದಲ್ಲಿ", "reminder_before": "%1$d ನಿಮಿಷ ಮೊದಲು",
"reminder_custom_time": "ನಿರ್ದಿಷ್ಟ ಸಮಯಕ್ಕೆ…", "reminder_at": "%1$s ಕ್ಕೆ", "reminder_persistent": "ನಾನು ಕ್ರಮ ಕೈಗೊಳ್ಳುವವರೆಗೆ ಇರಲಿ",
"add_subtask": "ಹಂತ ಸೇರಿಸಿ", "remove_subtask": "ಹಂತ ತೆಗೆಯಿರಿ",
"example_note": "ಇದು ಉದಾಹರಣೆ ಕಾರ್ಯ. ಇದನ್ನು ತಿದ್ದಬಹುದು ಅಥವಾ ಸೆಟ್ಟಿಂಗ್ಸ್‌ನಲ್ಲಿ ಎಲ್ಲಾ ಉದಾಹರಣೆಗಳನ್ನು ತೆಗೆಯಬಹುದು.",
"error_title_empty": "ಕಾರ್ಯಕ್ಕೆ ಶೀರ್ಷಿಕೆ ನೀಡಿ.", "error_title_long": "ಶೀರ್ಷಿಕೆ %1$d ಅಕ್ಷರಗಳಿಗಿಂತ ಕಡಿಮೆ ಇರಲಿ.",
"error_end_before_start": "ಮುಕ್ತಾಯ ಸಮಯ ಆರಂಭಕ್ಕಿಂತ ಮೊದಲಿದೆ.", "error_reminder_needs_time": "\"ಆರಂಭಕ್ಕೆ ಮೊದಲು\" ಜ್ಞಾಪನೆಗಳಿಗೆ ಆರಂಭ ಸಮಯ ಬೇಕು.",
"error_too_many_reminders": "ಒಂದು ಕಾರ್ಯಕ್ಕೆ ಗರಿಷ್ಠ %1$d ಜ್ಞಾಪನೆಗಳು.",
"error_title": "ಏನೋ ತಪ್ಪಾಗಿದೆ", "error_body": "ನಿಮ್ಮ ಮಾಹಿತಿ ಸುರಕ್ಷಿತವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.", "error_save_body": "ಕಾರ್ಯವನ್ನು ಉಳಿಸಲಾಗಲಿಲ್ಲ. ಏನೂ ಕಳೆದುಹೋಗಿಲ್ಲ; ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
"error_action_failed": "ಅದು ಆಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
"task_missing": "ಈ ಕಾರ್ಯ ಈಗ ಇಲ್ಲ", "task_missing_body": "ಇದನ್ನು ಅಳಿಸಿರಬಹುದು ಅಥವಾ ಕಸದ ಬುಟ್ಟಿಗೆ ಸರಿಸಿರಬಹುದು.",
"trash_confirm_body": "ಕಾರ್ಯ ಕಸದ ಬುಟ್ಟಿಗೆ ಹೋಗುತ್ತದೆ. ಇನ್ನಷ್ಟು > ಕಸದ ಬುಟ್ಟಿ ಇಂದ ಮರಳಿ ಪಡೆಯಬಹುದು.",
"reschedule_title": "ಮರುನಿಗದಿ", "reschedule_recurring_note": "ಈ ಒಂದು ಬಾರಿ ಮಾತ್ರ ಸರಿಯುತ್ತದೆ. ಪುನರಾವರ್ತಿತ ಯೋಜನೆ ಹಾಗೆಯೇ ಇರುತ್ತದೆ.",
"action_done": "ಮುಗಿದಿದೆ", "action_snooze": "ಮುಂದೂಡಿ", "action_reschedule": "ಮರುನಿಗದಿ",
"reminder_label": "ಕಾರ್ಯ", "reminder_all_day": "ಇಂದು", "reminder_public_title": "ಕೈರೋಸ್ ಎರಾ ಜ್ಞಾಪನೆ",
"channel_group_reminders": "ಕಾರ್ಯ ಜ್ಞಾಪನೆಗಳು", "channel_default": "ಜ್ಞಾಪನೆಗಳು (ಡೀಫಾಲ್ಟ್ ಧ್ವನಿ)", "channel_general": "ಸಾಮಾನ್ಯ",
"channel_reminders_description": "ನೀವು ನಿಗದಿಪಡಿಸಿದ ಕಾರ್ಯಗಳ ಜ್ಞಾಪನೆಗಳು.",
"sound_default": "ಡೀಫಾಲ್ಟ್", "sound_kairos_bell": "ಕೈರೋಸ್ ಗಂಟೆ", "sound_soft_chime": "ಮೃದು ನಾದ", "sound_focus": "ಏಕಾಗ್ರತೆ", "sound_silent": "ನಿಶ್ಶಬ್ದ",
"settings": "ಸೆಟ್ಟಿಂಗ್ಸ್", "settings_summary": "ಭಾಷೆ, ನೋಟ, ಅಧಿಸೂಚನೆಗಳು, ಧ್ವನಿಗಳು", "calendar": "ಕ್ಯಾಲೆಂಡರ್", "calendar_summary": "ನಿಮ್ಮ ಯೋಜನೆಯ ತಿಂಗಳ ನೋಟ",
"trash": "ಕಸದ ಬುಟ್ಟಿ", "trash_summary": "ಅಳಿಸಿದ ಕಾರ್ಯಗಳು, ಟ್ರ್ಯಾಕರ್‌ಗಳು ಮತ್ತು ಪುಸ್ತಕಗಳನ್ನು ಮರಳಿ ಪಡೆಯಿರಿ", "privacy": "ಗೌಪ್ಯತೆ", "privacy_summary": "ನಿಮ್ಮ ಮಾಹಿತಿ ಈ ಸಾಧನದಲ್ಲೇ ಇರುತ್ತದೆ",
"about": "ಕುರಿತು", "about_summary": "ಕೈರೋಸ್ ಎರಾ ಮತ್ತು ಅದರ ಅರ್ಥ", "coming_next": "ಮುಂದೆ ಬರಲಿರುವುದು", "soon": "ಮುಂಬರುವ ಅಪ್‌ಡೇಟ್‌ನಲ್ಲಿ",
"journal": "ದಿನಚರಿ", "statistics": "ಅಂಕಿಅಂಶಗಳು", "backup": "ಬ್ಯಾಕಪ್", "diagnostics": "ರೋಗನಿರ್ಣಯ",
"settings_general": "ಸಾಮಾನ್ಯ", "settings_language": "ಭಾಷೆ", "language_system": "ಫೋನ್ ಭಾಷೆ", "language_english": "English", "language_kannada": "ಕನ್ನಡ",
"settings_appearance": "ನೋಟ", "theme_system": "ಸಿಸ್ಟಮ್", "theme_light": "ತಿಳಿ", "theme_dark": "ಗಾಢ",
"dynamic_color": "ವಾಲ್‌ಪೇಪರ್ ಬಣ್ಣಗಳು", "dynamic_color_summary": "ಕೈರೋಸ್ ಬಣ್ಣಗಳ ಬದಲು ನಿಮ್ಮ ವಾಲ್‌ಪೇಪರ್‌ನ ಬಣ್ಣಗಳನ್ನು ಬಳಸಿ.",
"settings_notifications": "ಅಧಿಸೂಚನೆಗಳು", "notif_permission": "ಅಧಿಸೂಚನೆಗಳು", "status_allowed": "ಅನುಮತಿ ಇದೆ", "status_off": "ಆಫ್", "allow": "ಅನುಮತಿಸಿ",
"notif_permission_off_body": "ಅಧಿಸೂಚನೆಗಳಿಗೆ ಅನುಮತಿ ನೀಡುವವರೆಗೆ ಜ್ಞಾಪನೆಗಳು ಕಾಣುವುದಿಲ್ಲ. ಉಳಿದೆಲ್ಲವೂ ಸಾಮಾನ್ಯವಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ.",
"exact_alarms": "ಸಮಯಕ್ಕೆ ಸರಿಯಾದ ಜ್ಞಾಪನೆಗಳು", "exact_alarms_off_body": "ಇದಿಲ್ಲದಿದ್ದರೆ, ಬ್ಯಾಟರಿ ಉಳಿಸಲು Android ಜ್ಞಾಪನೆಗಳನ್ನು ಕೆಲವು ನಿಮಿಷ ತಡವಾಗಿ ನೀಡಬಹುದು.",
"open_settings": "ಸೆಟ್ಟಿಂಗ್ಸ್ ತೆರೆಯಿರಿ", "battery_title": "ಬ್ಯಾಟರಿ ಆಪ್ಟಿಮೈಸೇಶನ್",
"battery_body": "ಕೆಲವು ಫೋನ್‌ಗಳು ಹಿನ್ನೆಲೆಯಲ್ಲಿ ಆ್ಯಪ್‌ಗಳನ್ನು ನಿಲ್ಲಿಸುತ್ತವೆ. ಜ್ಞಾಪನೆಗಳು ತಡವಾದರೆ, ಕೈರೋಸ್ ಎರಾಗೆ ನಿರ್ಬಂಧವಿಲ್ಲದೆ ಓಡಲು ಅನುಮತಿಸಿ.",
"test_notification": "ಪರೀಕ್ಷಾ ಅಧಿಸೂಚನೆ ಕಳುಹಿಸಿ", "test_notification_summary": "ಧ್ವನಿ ಮತ್ತು ನೋಟವನ್ನು ಪರಿಶೀಲಿಸಿ.",
"test_notification_title": "ಕೈರೋಸ್ ಎರಾ", "test_notification_text": "ಅಧಿಸೂಚನೆಗಳು ಕೆಲಸ ಮಾಡುತ್ತಿವೆ.",
"settings_sounds": "ಧ್ವನಿಗಳು", "default_sound": "ಹೊಸ ಜ್ಞಾಪನೆಗಳ ಡೀಫಾಲ್ಟ್ ಧ್ವನಿ",
"sound_channel_note": "ಪ್ರತಿ ಧ್ವನಿಯ ವಾಲ್ಯೂಮ್, ಕಂಪನ ಮತ್ತು ಪ್ರಾಮುಖ್ಯತೆಯನ್ನು Android ಸಿಸ್ಟಮ್ ಸೆಟ್ಟಿಂಗ್ಸ್‌ನಲ್ಲಿ ಬದಲಾಯಿಸಬಹುದು. ಅಲ್ಲಿನ ನಿಮ್ಮ ಆಯ್ಕೆಗಳನ್ನು ಗೌರವಿಸಲಾಗುತ್ತದೆ.",
"open_sound_settings": "ಅಧಿಸೂಚನೆ ಸೆಟ್ಟಿಂಗ್ಸ್ ತೆರೆಯಿರಿ",
"default_persistent": "ನಾನು ಕ್ರಮ ಕೈಗೊಳ್ಳುವವರೆಗೆ ಜ್ಞಾಪನೆ ಇರಲಿ", "default_persistent_summary": "ಮುಗಿದಿದೆ, ಮುಂದೂಡಿ ಅಥವಾ ಮರುನಿಗದಿ ಒತ್ತುವವರೆಗೆ ಹೊಸ ಜ್ಞಾಪನೆಗಳು ಅಧಿಸೂಚನೆ ಪಟ್ಟಿಯಲ್ಲಿ ಇರುತ್ತವೆ.",
"snooze_length": "ಮುಂದೂಡುವ ಅವಧಿ", "minutes_short": "%1$d ನಿಮಿಷ",
"settings_data": "ಮಾಹಿತಿ", "add_examples": "ಉದಾಹರಣೆಗಳನ್ನು ಸೇರಿಸಿ", "add_examples_summary": "ಆ್ಯಪ್ ಹೇಗೆ ಕಾಣುತ್ತದೆ ಎಂದು ನೋಡಲು ಕೆಲವು ಮಾದರಿ ಕಾರ್ಯಗಳು.",
"remove_examples": "ಉದಾಹರಣೆಗಳನ್ನು ತೆಗೆಯಿರಿ", "remove_examples_summary": "ಎಲ್ಲಾ ಉದಾಹರಣೆ ಕಾರ್ಯಗಳನ್ನು ಕಸದ ಬುಟ್ಟಿಗೆ ಸರಿಸುತ್ತದೆ.", "remove_examples_confirm": "ಎಲ್ಲಾ ಉದಾಹರಣೆ ಕಾರ್ಯಗಳನ್ನು ಕಸದ ಬುಟ್ಟಿಗೆ ಸರಿಸಬೇಕೆ? ನಂತರ ಮರಳಿ ಪಡೆಯಬಹುದು.",
"settings_footer": "ಕೈರೋಸ್ ಎರಾ ಸಂಪೂರ್ಣವಾಗಿ ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ. ಖಾತೆ, ಕ್ಲೌಡ್ ಸಿಂಕ್, ವಿಶ್ಲೇಷಣೆ ಅಥವಾ ಜಾಹೀರಾತುಗಳು ಇಲ್ಲ.",
"move_up": "ಮೇಲೆ ಸರಿಸಿ", "move_down": "ಕೆಳಗೆ ಸರಿಸಿ",
"trash_empty_title": "ಕಸದ ಬುಟ್ಟಿ ಖಾಲಿಯಿದೆ", "trash_empty_body": "ಅಳಿಸಿದ ಕಾರ್ಯಗಳು, ಟ್ರ್ಯಾಕರ್‌ಗಳು ಮತ್ತು ಪುಸ್ತಕಗಳು, ನೀವು ಮರಳಿ ಪಡೆಯುವವರೆಗೆ ಅಥವಾ ಶಾಶ್ವತವಾಗಿ ಅಳಿಸುವವರೆಗೆ ಇಲ್ಲಿರುತ್ತವೆ.",
"trash_explainer": "ನೀವು ನಿರ್ಧರಿಸುವವರೆಗೆ ಐಟಂಗಳು ಇಲ್ಲೇ ಇರುತ್ತವೆ. ಯಾವುದನ್ನೂ ತಾನಾಗಿಯೇ ತೆಗೆಯಲಾಗುವುದಿಲ್ಲ.",
"restore": "ಮರಳಿ ಪಡೆಯಿರಿ", "delete_forever": "ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಿ", "delete_forever_title": "ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಬೇಕೆ?",
"delete_forever_body": "\"%1$s\" ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಲ್ಪಡುತ್ತದೆ. ಇದನ್ನು ಹಿಂಪಡೆಯಲು ಸಾಧ್ಯವಿಲ್ಲ.", "deleted_on": "%1$s ರಂದು ಅಳಿಸಲಾಗಿದೆ",
"privacy_headline": "ನಿಮ್ಮ ಮಾಹಿತಿ ಈ ಸಾಧನದಲ್ಲೇ ಇರುತ್ತದೆ.",
"privacy_point_device": "ನೀವು ಬರೆಯುವುದೆಲ್ಲವೂ (ಕಾರ್ಯಗಳು, ಟಿಪ್ಪಣಿಗಳು, ಜ್ಞಾಪನೆಗಳು) ನಿಮ್ಮ ಫೋನ್‌ನಲ್ಲಿ ಈ ಆ್ಯಪ್‌ನ ಖಾಸಗಿ ಸಂಗ್ರಹದಲ್ಲಿ ಮಾತ್ರ ಉಳಿಯುತ್ತದೆ.",
"privacy_point_account": "ಯಾವುದೇ ಖಾತೆ ಅಥವಾ ಸೈನ್-ಇನ್ ಇಲ್ಲ.",
"privacy_point_cloud": "ಕ್ಲೌಡ್ ಸಿಂಕ್ ಅಥವಾ ಸರ್ವರ್ ಇಲ್ಲ. ಕೈರೋಸ್ ಎರಾ ನಿಮ್ಮ ಮಾಹಿತಿಯನ್ನು ಎಂದಿಗೂ ಅಪ್‌ಲೋಡ್ ಮಾಡುವುದಿಲ್ಲ.",
"privacy_point_network": "ಈ ಆ್ಯಪ್ ಇಂಟರ್ನೆಟ್ ಅನುಮತಿಯನ್ನೇ ಕೇಳುವುದಿಲ್ಲ, ಆದ್ದರಿಂದ ಏರ್‌ಪ್ಲೇನ್ ಮೋಡ್‌ನಲ್ಲೂ ಹಾಗೆಯೇ ಕೆಲಸ ಮಾಡುತ್ತದೆ.",
"privacy_point_storage": "ಇತರ ಆ್ಯಪ್‌ಗಳು ಈ ಆ್ಯಪ್‌ನ ಖಾಸಗಿ ಸಂಗ್ರಹವನ್ನು ಓದಲು ಸಾಧ್ಯವಿಲ್ಲ.",
"privacy_point_logs": "ರೋಗನಿರ್ಣಯ ಲಾಗ್‌ಗಳಲ್ಲಿ ನಿಮ್ಮ ಕಾರ್ಯಗಳ ಶೀರ್ಷಿಕೆ, ಟಿಪ್ಪಣಿ ಅಥವಾ ಇತರ ವೈಯಕ್ತಿಕ ಪಠ್ಯ ಎಂದಿಗೂ ಇರುವುದಿಲ್ಲ.",
"privacy_point_lock": "ಫೋನ್‌ನ ಬೆರಳಚ್ಚು, ಮುಖ ಅಥವಾ ಸ್ಕ್ರೀನ್ ಲಾಕ್ ಬಳಸುವ ಐಚ್ಛಿಕ ಆ್ಯಪ್ ಲಾಕ್ ಮುಂದಿನ ಅಪ್‌ಡೇಟ್‌ನಲ್ಲಿ ಬರಲಿದೆ.",
"privacy_point_backup": "ನಿಮ್ಮ ನಿಯಂತ್ರಣದಲ್ಲಿರುವ ಸ್ಥಳೀಯ ಬ್ಯಾಕಪ್ ಫೈಲ್‌ಗಳು ಮುಂದಿನ ಅಪ್‌ಡೇಟ್‌ನಲ್ಲಿ ಬರಲಿವೆ. ಈ ಆ್ಯಪ್‌ಗೆ Android ನ ಸ್ವಯಂ ಕ್ಲೌಡ್ ಬ್ಯಾಕಪ್ ಆಫ್ ಆಗಿದೆ.",
"privacy_point_diagnostics": "ಆ್ಯಪ್ ಎಂದಾದರೂ ಕ್ರ್ಯಾಶ್ ಆದರೆ, ಯಾವುದೇ ವರದಿ ಹಂಚುವ ಮೊದಲು ನಿಮ್ಮನ್ನು ಕೇಳಲಾಗುತ್ತದೆ; ಅದರಲ್ಲಿ ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ ಇರುವುದಿಲ್ಲ.",
"about_philosophy": "ದಿನವನ್ನು ಯೋಜಿಸಿ. ಏನಾದರೂ ಕಲಿಯಿರಿ. ದೇಹವನ್ನು ಚಲಿಸಿ. ಅರ್ಥಪೂರ್ಣವಾದುದನ್ನು ಓದಿ. ಚಿಂತಿಸಿ. ಪುನರಾವರ್ತಿಸಿ.",
"about_meaning": "ಕೈರೋಸ್ ಎಂದರೆ ಗ್ರೀಕ್ ಭಾಷೆಯಲ್ಲಿ ಸರಿಯಾದ, ಸೂಕ್ತ ಕ್ಷಣ. ಲಾಂಛನವು ಉದಯಿಸುವ ಸೂರ್ಯನತ್ತ ಸಾಗುವ ದಾರಿ: ಹೊಸ ದಿನ, ನಿರಂತರ ಪ್ರಗತಿ ಮತ್ತು ಬೆಳವಣಿಗೆ.",
"about_version": "ಆವೃತ್ತಿ %1$s",
"onboarding_welcome": "ನಿಮ್ಮ ಸಮಯ ನಿಮ್ಮದು.", "onboarding_private": "ಖಾಸಗಿ: ನಿಮ್ಮ ಯೋಜನೆಗಳು ನಿಮಗೆ ಮಾತ್ರ ಕಾಣುತ್ತವೆ.", "onboarding_local": "ಸ್ಥಳೀಯ: ಎಲ್ಲವೂ ಈ ಫೋನ್‌ನಲ್ಲೇ ಉಳಿಯುತ್ತದೆ.",
"onboarding_no_account": "ಖಾತೆ ಇಲ್ಲ, ಸೈನ್-ಇನ್ ಇಲ್ಲ.", "onboarding_no_cloud": "ಕ್ಲೌಡ್ ಸಿಂಕ್ ಇಲ್ಲ, ಟ್ರ್ಯಾಕಿಂಗ್ ಇಲ್ಲ, ಜಾಹೀರಾತು ಇಲ್ಲ.",
"onboarding_begin": "ಆರಂಭಿಸಿ", "onboarding_about_you": "ನಿಮ್ಮ ಬಗ್ಗೆ ಸ್ವಲ್ಪ", "onboarding_name_label": "ಹೆಸರು ಅಥವಾ ಅಡ್ಡಹೆಸರು",
"onboarding_focus": "ಯಾವುದರ ಮೇಲೆ ಗಮನ ಹರಿಸಲು ಬಯಸುವಿರಿ?", "focus_learning": "ಕಲಿಕೆ", "focus_health": "ಆರೋಗ್ಯ", "focus_reading": "ಓದು", "focus_work": "ಕೆಲಸ",
"focus_personal": "ವೈಯಕ್ತಿಕ", "focus_custom": "ಬೇರೆ ಏನಾದರೂ",
"onboarding_first_task": "ಇಂದು ಮಾಡಬೇಕಾದ ಒಂದು ಕೆಲಸ", "onboarding_first_task_hint": "ಐಚ್ಛಿಕ. ನಂತರ ಇನ್ನಷ್ಟು ಸೇರಿಸಬಹುದು.",
"onboarding_examples": "ಉದಾಹರಣೆ ಕಾರ್ಯಗಳನ್ನು ತೋರಿಸಿ (ಯಾವಾಗ ಬೇಕಾದರೂ ತೆಗೆಯಬಹುದು)",
"onboarding_reminders_title": "ಜ್ಞಾಪನೆಗಳು", "onboarding_reminders_body": "ಕಾರ್ಯದ ಸಮಯ ಬಂದಾಗ ಕೈರೋಸ್ ಎರಾ ನಿಮಗೆ ನೆನಪಿಸಬಹುದು. ಅದು ಕೇಳುವ ಏಕೈಕ ಅನುಮತಿ ಅಧಿಸೂಚನೆಗಳು; ಇದನ್ನು ಯಾವಾಗ ಬೇಕಾದರೂ ಬದಲಾಯಿಸಬಹುದು.",
"onboarding_allow_reminders": "ಜ್ಞಾಪನೆಗಳಿಗೆ ಅನುಮತಿಸಿ", "onboarding_not_now": "ಈಗ ಬೇಡ",
"sample_java": "ಜಾವಾ: ಕಲೆಕ್ಷನ್ಸ್", "sample_java_1": "List ಮತ್ತು ArrayList", "sample_java_2": "HashMap ಒಳರಚನೆ", "sample_java_3": "3 ಸಮಸ್ಯೆಗಳನ್ನು ಬಿಡಿಸಿ",
"sample_walk": "ಬೆಳಗಿನ ನಡಿಗೆ", "sample_project": "ಪ್ರಾಜೆಕ್ಟ್ ಕೆಲಸ", "sample_workout": "ವ್ಯಾಯಾಮ", "sample_read": "20 ಪುಟ ಓದಿ", "sample_reflection": "ದಿನದ ಚಿಂತನೆ",
# ಹಂತ 2: ಟ್ರ್ಯಾಕರ್‌ಗಳು, ಅಧ್ಯಯನ, ಓದುವಿಕೆ
"add": "ಸೇರಿಸಿ", "yes": "ಹೌದು", "no": "ಇಲ್ಲ", "see_all": "ಎಲ್ಲಾ ನೋಡಿ", "color_option": "ಬಣ್ಣ %1$d",
"new_tracker": "ಹೊಸ ಟ್ರ್ಯಾಕರ್", "edit_tracker": "ಟ್ರ್ಯಾಕರ್ ತಿದ್ದಿ",
"track_empty_title": "ನಿಮಗೆ ಮುಖ್ಯವಾದುದನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ", "track_empty_body": "ಅಧ್ಯಯನ, ವ್ಯಾಯಾಮ, ನಿದ್ರೆ, ನೀರು, ಅಭ್ಯಾಸಗಳು, ಪ್ರಾಜೆಕ್ಟ್‌ಗಳು ಅಥವಾ ಇನ್ನೇನಾದರೂ. ಒಂದು ಟೆಂಪ್ಲೇಟ್ ಆರಿಸಿ ಅಥವಾ ನಿಮ್ಮದೇ ರಚಿಸಿ.",
"track_today_summary": "ಇಂದು: %2$d ರಲ್ಲಿ %1$d ಪೂರ್ಣ",
"tracker_card_a11y": "%1$s, ಇಂದು %2$d%%, ಸತತ %3$d",
"tracker_rest_day": "ಇಂದಿಗೆ ಯೋಜಿಸಿಲ್ಲ", "tracker_done_today": "ಪೂರ್ಣ", "tracker_percent_today": "ಇಂದು %1$d%%",
"template_pick_title": "ಟ್ರ್ಯಾಕರ್ ಆರಂಭಿಸಿ", "template_pick_body": "ಟೆಂಪ್ಲೇಟ್‌ಗಳು ಕೇವಲ ಆರಂಭ. ಯಾವುದೇ ಅಂಶವನ್ನು ಮರುಹೆಸರಿಸಬಹುದು, ಸೇರಿಸಬಹುದು ಅಥವಾ ಆಫ್ ಮಾಡಬಹುದು.",
"template_study": "ಅಧ್ಯಯನ", "template_study_summary": "ಅಧ್ಯಯನ ಸಮಯ, ಅಭ್ಯಾಸ ಮತ್ತು ದೈನಂದಿನ ಗುರಿಗಳೊಂದಿಗೆ ವಿಷಯ ಯೋಜನೆ",
"template_fitness": "ಫಿಟ್‌ನೆಸ್", "template_fitness_summary": "ವ್ಯಾಯಾಮ, ಹೆಜ್ಜೆಗಳು, ನಿದ್ರೆ, ನೀರು, ಶಕ್ತಿ ಮತ್ತು ಮನಸ್ಥಿತಿ",
"template_reading": "ಓದುವ ಗುರಿ", "template_reading_summary": "ಪ್ರತಿದಿನ ಓದಿದ ಪುಟಗಳು ಮತ್ತು ನಿಮಿಷಗಳು",
"template_habit": "ಅಭ್ಯಾಸ", "template_habit_summary": "ಪ್ರತಿದಿನ ಒಂದು ಸರಳ ಹೌದು ಅಥವಾ ಇಲ್ಲ",
"template_project": "ಪ್ರಾಜೆಕ್ಟ್", "template_project_summary": "ಕಳೆದ ಸಮಯ, ಪ್ರಗತಿ ಮತ್ತು ಮುಂದಿನ ಹೆಜ್ಜೆ",
"template_finance": "ಹಣ", "template_finance_summary": "ಖರ್ಚು ಮತ್ತು ಖರ್ಚಿಲ್ಲದ ದಿನಗಳನ್ನು ದಾಖಲಿಸಿ",
"template_learning": "ಕೌಶಲ್ಯ ಕಲಿಕೆ", "template_learning_summary": "ಅಭ್ಯಾಸದ ಸಮಯ ಮತ್ತು ನೀವು ಕಲಿತದ್ದು",
"template_health": "ಆರೋಗ್ಯ", "template_health_summary": "ನೀರು, ನಿದ್ರೆ, ಔಷಧ ಮತ್ತು ಶಕ್ತಿ",
"template_personal": "ವೈಯಕ್ತಿಕ ಬೆಳವಣಿಗೆ", "template_personal_summary": "ಧ್ಯಾನ, ಪರದೆರಹಿತ ಸಮಯ ಮತ್ತು ಕೃತಜ್ಞತೆ",
"template_custom": "ನಿಮ್ಮದೇ", "template_custom_summary": "ಖಾಲಿ ಟ್ರ್ಯಾಕರ್‌ನಿಂದ ಆರಂಭಿಸಿ",
"tf_study_time": "ಅಧ್ಯಯನ ಸಮಯ", "tf_practice": "ಅಭ್ಯಾಸ ಸಮಸ್ಯೆಗಳು", "tf_revision": "ಪುನರಾವರ್ತನೆ ಆಯಿತು", "tf_notes": "ಟಿಪ್ಪಣಿಗಳು",
"tf_workout": "ವ್ಯಾಯಾಮ ಆಯಿತು", "tf_steps": "ಹೆಜ್ಜೆಗಳು", "tf_workout_minutes": "ವ್ಯಾಯಾಮ ಸಮಯ", "tf_sleep": "ನಿದ್ರೆ", "tf_water": "ನೀರು",
"tf_walk": "ನಡಿಗೆ", "tf_stretching": "ಸ್ಟ್ರೆಚಿಂಗ್", "tf_energy": "ಶಕ್ತಿ", "tf_mood": "ಮನಸ್ಥಿತಿ", "tf_weight": "ತೂಕ",
"tf_pages": "ಓದಿದ ಪುಟಗಳು", "tf_reading_minutes": "ಓದಿನ ಸಮಯ", "tf_done": "ಆಯಿತು",
"tf_worked_on_it": "ಕೆಲಸ ಮಾಡಿದೆ", "tf_time_spent": "ಕಳೆದ ಸಮಯ", "tf_progress": "ಪ್ರಗತಿ", "tf_next_step": "ಮುಂದಿನ ಹೆಜ್ಜೆ",
"tf_tracked_spending": "ಖರ್ಚು ಬರೆದಿಟ್ಟೆ", "tf_no_spend": "ಖರ್ಚಿಲ್ಲದ ದಿನ",
"tf_practice_time": "ಅಭ್ಯಾಸ ಸಮಯ", "tf_learned_count": "ಕಲಿತ ಹೊಸ ವಿಷಯಗಳು",
"tf_medicine": "ಔಷಧ ತೆಗೆದುಕೊಂಡೆ", "tf_meditation": "ಧ್ಯಾನ", "tf_screen_free": "ಪರದೆರಹಿತ ಒಂದು ಗಂಟೆ", "tf_gratitude": "ಕೃತಜ್ಞತೆ",
"unit_steps": "ಹೆಜ್ಜೆ", "unit_hours": "ಗಂ", "unit_litres": "ಲೀ", "unit_kg": "ಕೆಜಿ", "unit_pages": "ಪುಟ", "unit_minutes": "ನಿಮಿ",
"tracker_missing": "ಈ ಟ್ರ್ಯಾಕರ್ ಈಗ ಇಲ್ಲ", "tracker_missing_body": "ಇದನ್ನು ಕಸದ ಬುಟ್ಟಿಗೆ ಸರಿಸಿರಬಹುದು.",
"tracker_trash_body": "ಟ್ರ್ಯಾಕರ್ ಮತ್ತು ಅದರ ಇತಿಹಾಸ ಕಸದ ಬುಟ್ಟಿಗೆ ಹೋಗುತ್ತವೆ. ಇನ್ನಷ್ಟು > ಕಸದ ಬುಟ್ಟಿ ಇಂದ ಮರಳಿ ಪಡೆಯಬಹುದು.",
"tracker_why_line": "ಏಕೆ: %1$s", "tracker_gain_line": "ನನಗೆ ಸಿಗುವುದು: %1$s",
"tracker_log": "ದಾಖಲೆ", "tracker_no_fields": "ಈ ಟ್ರ್ಯಾಕರ್‌ನಲ್ಲಿ ಸಕ್ರಿಯ ಅಂಶಗಳಿಲ್ಲ. ಒಂದನ್ನು ಸೇರಿಸಲು ತಿದ್ದಿ.",
"field_target_line": "ಗುರಿ %1$s %2$s",
"tracker_stats": "ಪ್ರಗತಿ", "stat_current_streak": "ಈಗಿನ ಸತತ ದಿನಗಳು", "stat_best_streak": "ಅತ್ಯುತ್ತಮ ಸತತ",
"stat_completion_30": "ಕಳೆದ 30 ದಿನಗಳಲ್ಲಿ ಪೂರ್ಣ", "stat_active_days": "ಪ್ರಗತಿ ಇದ್ದ ದಿನಗಳು",
"tracker_missed_yesterday": "ನಿನ್ನೆ ತಪ್ಪಿತು. ಪರವಾಗಿಲ್ಲ: ಪ್ರತಿದಿನವೂ ಹೊಸ ಆರಂಭ.",
"tracker_history": "ಕಳೆದ 5 ವಾರಗಳು", "history_cell_a11y": "%1$s, %2$d%%",
"tracker_name": "ಹೆಸರು", "error_tracker_name": "ಟ್ರ್ಯಾಕರ್‌ಗೆ ಹೆಸರು ನೀಡಿ.",
"tracker_icon": "ಚಿಹ್ನೆ", "tracker_color": "ಬಣ್ಣ",
"tracker_why": "ಇದು ಏಕೆ ಮುಖ್ಯ", "tracker_why_hint": "ಉದಾ. ಬ್ಯಾಕೆಂಡ್ ಕೆಲಸಕ್ಕೆ ಬದಲಾಗಲು ಬಯಸುತ್ತೇನೆ",
"tracker_gain": "ನನಗೆ ಏನು ಸಿಗುತ್ತದೆ", "tracker_gain_hint": "ಉದಾ. ಸಂದರ್ಶನಗಳಲ್ಲಿ ಆತ್ಮವಿಶ್ವಾಸ",
"tracker_frequency": "ಎಷ್ಟು ಬಾರಿ", "freq_daily": "ಪ್ರತಿದಿನ", "freq_selected_days": "ಕೆಲವು ದಿನಗಳು", "freq_per_week": "ವಾರಕ್ಕೆ ಇಷ್ಟು ಬಾರಿ", "freq_per_month": "ತಿಂಗಳಿಗೆ ಇಷ್ಟು ಬಾರಿ",
"freq_times_week": "ವಾರಕ್ಕೆ %1$d ಬಾರಿ", "freq_times_month": "ತಿಂಗಳಿಗೆ %1$d ಬಾರಿ",
"tracker_fields": "ಏನನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಬೇಕು", "tracker_fields_note": "ಮೊದಲ ಅಂಶವೇ ಮುಖ್ಯ ಗುರಿ: ಅದು ಪೂರ್ಣವಾದರೆ ದಿನ ಪೂರ್ಣ. ತೆಗೆದ ಅಂಶಗಳ ಇತಿಹಾಸ ಉಳಿಯುತ್ತದೆ.",
"error_tracker_fields": "ಕನಿಷ್ಠ ಒಂದು ಅಂಶವನ್ನು ಆನ್ ಮಾಡಿ.", "error_checklist_empty": "ಪರಿಶೀಲನಾಪಟ್ಟಿಗೆ ಕನಿಷ್ಠ ಒಂದು ಐಟಂ ಬೇಕು.",
"add_field": "ಅಂಶ ಸೇರಿಸಿ", "edit_field": "ಅಂಶ ತಿದ್ದಿ", "field_label": "ಹೆಸರು", "field_type": "ಬಗೆ",
"field_target": "ದೈನಂದಿನ ಗುರಿ", "field_target_hint": "ಐಚ್ಛಿಕ. ಯಾವುದೇ ಮೊತ್ತ ಸಾಕಾದರೆ ಖಾಲಿ ಬಿಡಿ.", "field_unit": "ಘಟಕ",
"checklist_options": "ಐಟಂಗಳು, ಸಾಲಿಗೆ ಒಂದು", "checklist_items": "%1$d ಐಟಂಗಳು", "field_off": "ಆಫ್",
"remove_field": "ಅಂಶ ತೆಗೆಯಿರಿ", "remove_field_note": "ಹಿಂದಿನ ಮೌಲ್ಯಗಳು ಉಳಿಯುತ್ತವೆ; ಅಂಶವನ್ನು ಮರೆಮಾಡಲಾಗುತ್ತದೆ ಅಷ್ಟೇ.",
"type_checkbox": "ಹೌದು / ಇಲ್ಲ", "type_number": "ಸಂಖ್ಯೆ", "type_decimal": "ದಶಮಾಂಶ", "type_duration": "ನಿಮಿಷಗಳು", "type_pages": "ಪುಟಗಳು",
"type_percentage": "ಶೇಕಡಾ", "type_rating": "ರೇಟಿಂಗ್ 1-5", "type_text": "ಪಠ್ಯ", "type_checklist": "ಪರಿಶೀಲನಾಪಟ್ಟಿ",
"study_plan_for_day": "ಅಧ್ಯಯನ ಯೋಜನೆ", "study_plan_note": "ಗುರಿಯನ್ನು ಗುರುತಿಸಿದರೆ ಅದರ ವಿಷಯಕ್ಕೆ ಅಭ್ಯಾಸ ದಾಖಲಾಗುತ್ತದೆ. ವಿಷಯ ಯಾವಾಗ ಪೂರ್ಣ ಎಂದು ನೀವೇ ನಿರ್ಧರಿಸಿ.",
"add_study_target": "ಗುರಿ ಸೇರಿಸಿ", "remove_target": "ಗುರಿ ತೆಗೆಯಿರಿ", "study_target_hint": "ಏನನ್ನು ಅಧ್ಯಯನ ಮಾಡುವಿರಿ?", "study_target_topic": "ವಿಷಯ: %1$s",
"study_topics": "ವಿಷಯಗಳು", "study_topics_done": "%2$d ರಲ್ಲಿ %1$d ಪೂರ್ಣ", "study_topics_empty": "ನಿಮ್ಮ ವಿಷಯವನ್ನು ಉಪವಿಷಯಗಳಾಗಿ ವಿಂಗಡಿಸಿ, ಉದಾ. Java Core > Collections.",
"add_topic": "ವಿಷಯ ಸೇರಿಸಿ", "edit_topic": "ವಿಷಯ ತಿದ್ದಿ", "delete_topic": "ವಿಷಯ ಅಳಿಸಿ",
"delete_topic_body": "ವಿಷಯ ಅಳಿಸಲಾಗುತ್ತದೆ. ಅದರ ಉಪವಿಷಯಗಳು ಒಂದು ಹಂತ ಮೇಲಕ್ಕೆ ಹೋಗುತ್ತವೆ ಮತ್ತು ಗುರಿಗಳ ಪಠ್ಯ ಉಳಿಯುತ್ತದೆ.",
"topic_status": "ಸ್ಥಿತಿ", "topic_not_started": "ಆರಂಭಿಸಿಲ್ಲ", "topic_learning": "ಕಲಿಯುತ್ತಿದ್ದೇನೆ", "topic_reviewing": "ಪುನರಾವರ್ತನೆ", "topic_done": "ಪೂರ್ಣ",
"topic_confidence": "ಆತ್ಮವಿಶ್ವಾಸ", "topic_resources": "ಸಂಪನ್ಮೂಲಗಳು", "topic_questions": "ಉತ್ತರಿಸಬೇಕಾದ ಪ್ರಶ್ನೆಗಳು",
"topic_parent": "ಒಳಗೆ: %1$s", "topic_no_parent": "ಯಾವುದೂ ಇಲ್ಲ", "topic_practice_count": "%1$d ಅಭ್ಯಾಸ",
"add_book": "ಪುಸ್ತಕ ಸೇರಿಸಿ", "edit_book": "ಪುಸ್ತಕ ತಿದ್ದಿ",
"read_empty_title": "ಓದಿ, ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ, ನೆನಪಿಡಿ, ಅಳವಡಿಸಿ", "read_empty_body": "ಪುಟಗಳನ್ನು ದಾಖಲಿಸಲು ಮತ್ತು ಏಕೆ ಆರಂಭಿಸಿದಿರಿ, ಏನು ಕಲಿತಿರಿ, ಏನು ಅಳವಡಿಸಿದಿರಿ ಎಂದು ಬರೆದಿಡಲು ಪುಸ್ತಕ ಸೇರಿಸಿ.",
"reading_this_week": "ಈ ವಾರ", "pages_today": "ಇಂದಿನ ಪುಟಗಳು", "pages_week": "ಈ ವಾರದ ಪುಟಗಳು", "minutes_week": "ಈ ವಾರದ ನಿಮಿಷಗಳು",
"reading_days_line": "ಈ ವಾರ %1$d ದಿನ ಓದಿದ್ದೀರಿ · ಈ ವರ್ಷ %2$d ಪುಸ್ತಕ ಮುಗಿಸಿದ್ದೀರಿ",
"shelf_reading": "ಈಗ ಓದುತ್ತಿರುವುದು", "shelf_paused": "ನಿಲ್ಲಿಸಿದ್ದು", "shelf_want": "ಓದಬೇಕಿರುವುದು", "shelf_finished": "ಮುಗಿದಿದ್ದು",
"status_want": "ಓದಬೇಕು", "status_reading": "ಓದುತ್ತಿದ್ದೇನೆ", "status_paused": "ನಿಲ್ಲಿಸಿದೆ", "status_finished": "ಮುಗಿಯಿತು",
"book_page_of": "%2$d ರಲ್ಲಿ %1$d ನೇ ಪುಟ", "book_page_of_percent": "%2$d ರಲ್ಲಿ %1$d ನೇ ಪುಟ (%3$d%%)", "book_page_only": "%1$d ನೇ ಪುಟ",
"book_pages_per_day": "ಸಮಯಕ್ಕೆ ಮುಗಿಸಲು ದಿನಕ್ಕೆ %1$d ಪುಟ",
"book_progress": "ಪ್ರಗತಿ", "book_target_line": "ಗುರಿ: %1$s", "book_finished_on": "%1$s ರಂದು ಮುಗಿಯಿತು",
"log_reading": "ಓದು ದಾಖಲಿಸಿ", "pages_read": "ಓದಿದ ಪುಟಗಳು", "minutes_read": "ನಿಮಿಷಗಳು (ಐಚ್ಛಿಕ)",
"book_insights": "ಈ ಪುಸ್ತಕ ನಿಮಗೆ ಕೊಡುವುದು", "book_insights_note": "ನೀವು ಬರೆಯುತ್ತಿದ್ದಂತೆ ತಾನಾಗಿಯೇ ಉಳಿಸಲಾಗುತ್ತದೆ.",
"insight_why": "ನಾನು ಏಕೆ ಆರಂಭಿಸಿದೆ", "insight_expected": "ನಾನು ಏನು ನಿರೀಕ್ಷಿಸಿದ್ದೆ", "insight_learned": "ನಾನು ಏನು ಕಲಿತೆ",
"insight_key_ideas": "ಮುಖ್ಯ ವಿಚಾರಗಳು", "insight_applied": "ನಾನು ಏನು ಅಳವಡಿಸಿದೆ", "insight_changed": "ನನ್ನಲ್ಲಿ ಏನು ಬದಲಾಯಿತು",
"insight_skills": "ಸುಧಾರಿಸಿದ ಕೌಶಲ್ಯಗಳು", "insight_takeaway": "ಅಂತಿಮ ಪಾಠ", "insight_recommend": "ಮತ್ತೆ ಓದುತ್ತೇನೆಯೇ?",
"book_notes": "ಟಿಪ್ಪಣಿಗಳು ಮತ್ತು ಮುಖ್ಯಾಂಶಗಳು", "book_notes_empty": "ಓದುವಾಗ ಮುಖ್ಯಾಂಶ, ಟಿಪ್ಪಣಿ ಅಥವಾ ಪಾಠವನ್ನು ಬರೆದಿಡಿ.",
"add_note": "ಸೇರಿಸಿ", "delete_note": "ಟಿಪ್ಪಣಿ ಅಳಿಸಿ", "note_kind_note": "ಟಿಪ್ಪಣಿ", "note_kind_highlight": "ಮುಖ್ಯಾಂಶ", "note_kind_lesson": "ಪಾಠ",
"note_text": "ಪಠ್ಯ", "note_page": "ಪುಟ (ಐಚ್ಛಿಕ)", "page_short": "ಪು. %1$d",
"book_sessions": "ಓದಿನ ಅವಧಿಗಳು", "book_sessions_empty": "ಇನ್ನೂ ಯಾವುದೇ ಅವಧಿಗಳಿಲ್ಲ.", "session_line": "%1$d ಪುಟ · %2$d ನಿಮಿ",
"delete_session": "ಅವಧಿ ಅಳಿಸಿ", "delete_session_body": "ಈ ಅವಧಿಯನ್ನು ಅಳಿಸಬೇಕೆ? ಅದರ ಪುಟಗಳನ್ನು ನಿಮ್ಮ ಬುಕ್‌ಮಾರ್ಕ್‌ನಿಂದ ಕಳೆಯಲಾಗುತ್ತದೆ.",
"book_missing": "ಈ ಪುಸ್ತಕ ಈಗ ಇಲ್ಲ", "book_missing_body": "ಇದನ್ನು ಕಸದ ಬುಟ್ಟಿಗೆ ಸರಿಸಿರಬಹುದು.",
"book_trash_body": "ಪುಸ್ತಕ, ಅದರ ಟಿಪ್ಪಣಿಗಳು ಮತ್ತು ಅವಧಿಗಳು ಕಸದ ಬುಟ್ಟಿಗೆ ಹೋಗುತ್ತವೆ. ಇನ್ನಷ್ಟು > ಕಸದ ಬುಟ್ಟಿ ಇಂದ ಮರಳಿ ಪಡೆಯಬಹುದು.",
"book_title": "ಶೀರ್ಷಿಕೆ", "book_author": "ಲೇಖಕರು", "book_total_pages": "ಒಟ್ಟು ಪುಟಗಳು", "book_current_page": "ಈಗಿನ ಪುಟ",
"book_status": "ಸ್ಥಿತಿ", "book_target_date": "ಮುಗಿಸುವ ದಿನಾಂಕ", "book_no_target": "ಗುರಿ ದಿನಾಂಕವಿಲ್ಲ",
"error_book_title": "ಪುಸ್ತಕಕ್ಕೆ ಶೀರ್ಷಿಕೆ ನೀಡಿ.", "error_page_beyond": "ಈಗಿನ ಪುಟ ಕೊನೆಯ ಪುಟವನ್ನು ಮೀರಿದೆ.",
"home_trackers_line": "ಟ್ರ್ಯಾಕರ್‌ಗಳು: %2$d ರಲ್ಲಿ %1$d ಪೂರ್ಣ", "home_reading_line": "ಓದು: ಇಂದು %1$d ಪುಟ · %2$s",
"home_trackers_empty": "ಇನ್ನೂ ಟ್ರ್ಯಾಕರ್‌ಗಳಿಲ್ಲ. ಅಧ್ಯಯನ, ಫಿಟ್‌ನೆಸ್ ಅಥವಾ ಅಭ್ಯಾಸಕ್ಕಾಗಿ ಒಂದನ್ನು ರಚಿಸಲು ಒತ್ತಿ.",
"home_trackers_rest": "ಇಂದಿಗೆ ಏನೂ ಯೋಜಿಸಿಲ್ಲ. ವಿಶ್ರಾಂತಿ ಆನಂದಿಸಿ.",
"trash_kind_task": "ಕಾರ್ಯ", "trash_kind_tracker": "ಟ್ರ್ಯಾಕರ್", "trash_kind_book": "ಪುಸ್ತಕ",
"delete_forever_body_history": "\"%1$s\" ಮತ್ತು ಅದರ ಎಲ್ಲಾ ಇತಿಹಾಸ ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಲ್ಪಡುತ್ತದೆ. ಇದನ್ನು ಹಿಂಪಡೆಯಲು ಸಾಧ್ಯವಿಲ್ಲ.",
"sample_fitness_why": "ಉಳಿದೆಲ್ಲದಕ್ಕೂ ಹೆಚ್ಚು ಶಕ್ತಿ", "sample_study_name": "ಜಾವಾ ಬ್ಯಾಕೆಂಡ್",
"sample_study_why": "ಬ್ಯಾಕೆಂಡ್ ಸಂದರ್ಶನಗಳಲ್ಲಿ ಆತ್ಮವಿಶ್ವಾಸ ಪಡೆಯಲು",
"sample_topic_core": "Java Core", "sample_topic_collections": "Collections", "sample_topic_oop": "OOP ಮೂಲಗಳು",
"sample_topic_streams": "Streams ಮತ್ತು lambdas", "sample_topic_spring": "Spring Boot",
"sample_target_1": "HashMap ಒಳರಚನೆ ಬಗ್ಗೆ ಓದಿ", "sample_target_2": "Collections ಕುರಿತ 2 ಸಮಸ್ಯೆಗಳನ್ನು ಬಿಡಿಸಿ",
"sample_book_title": "Atomic Habits", "sample_book_author": "James Clear", "sample_book_why": "ಉಳಿಯುವ ಅಭ್ಯಾಸಗಳನ್ನು ಬೆಳೆಸಲು",
}

# Android plurals. Kannada uses "one" and "other" like English.
PLURALS_EN = {
"streak_days": {"one": "%1$d day", "other": "%1$d days"},
"streak_weeks": {"one": "%1$d week", "other": "%1$d weeks"},
"streak_months": {"one": "%1$d month", "other": "%1$d months"},
}

PLURALS_KN = {
"streak_days": {"one": "%1$d ದಿನ", "other": "%1$d ದಿನಗಳು"},
"streak_weeks": {"one": "%1$d ವಾರ", "other": "%1$d ವಾರಗಳು"},
"streak_months": {"one": "%1$d ತಿಂಗಳು", "other": "%1$d ತಿಂಗಳುಗಳು"},
}
