# Winter Arc UI text, English and Kannada. Merged into EN/KN by strings_source.py.
# The private habit is always "Digital Detox"; its original name must never appear here.
WA_EN = {
"wa_title": "Winter Arc",
"wa_mode": "Winter Arc Mode",
"wa_mode_summary": "A 90-day discipline challenge. Home becomes your Winter Arc dashboard.",
"wa_day_of": "Winter Arc — Day %1$d / %2$d",
"wa_day_short": "Day %1$d / %2$d",
"wa_starts_in": "Starts in %1$d days",
"wa_starts_tomorrow": "Starts tomorrow",
"wa_starts_on": "Your Winter Arc starts on %1$s",
"wa_paused_banner": "Paused. The day count waits for you.",
"wa_finished_banner": "90 days done. Look back at what you built.",
"wa_statement": "Discipline today,\nfreedom tomorrow.",
"wa_completed_of": "%1$d / %2$d completed",
"wa_habits_completed": "habits completed",
"wa_done_short": "done",
"wa_complete_rule": "A day counts as complete at %1$d of %2$d habits.",
"wa_back_to_arc": "Back to Winter Arc",
"wa_open_kairos": "Open everyday Kairos Era",
"wa_open_kairos_summary": "Tasks, journal and trackers. Winter Arc stays on.",

"wa_nav_home": "Home", "wa_nav_habits": "Habits", "wa_nav_study": "Study", "wa_nav_calendar": "Calendar", "wa_nav_stats": "Stats",

"wa_h_water": "Water", "wa_h_steps": "Steps", "wa_h_zero_sugar": "No Sugar", "wa_h_cold_shower": "Cold Shower",
"wa_h_reading": "Book Read", "wa_h_study": "Study", "wa_h_deep_work": "Deep Work", "wa_h_wake": "Wake < 5 AM",
"wa_h_detox": "Digital Detox", "wa_h_speak": "Speak 1 Minute",
"wa_hl_water": "Water Drink", "wa_hl_steps": "Steps + Running", "wa_hl_zero_sugar": "Zero Sugar", "wa_hl_cold_shower": "Cold Shower",
"wa_hl_reading": "Book Reading", "wa_hl_study": "Study (Java + DSA + AI)", "wa_hl_deep_work": "Deep Work", "wa_hl_wake": "Wake up before 5 AM",
"wa_hl_detox": "Digital Detox", "wa_hl_speak": "Speak for 1 Minute",
"wa_sub_water": "%1$s / day", "wa_sub_steps": "%1$s steps", "wa_sub_daily": "Daily", "wa_sub_study": "From your study plan",
"wa_sub_deep_work": "No social media distraction", "wa_sub_wake": "Sleep discipline", "wa_sub_speak": "Random topic daily",
"wa_sub_focus": "Focus",
"wa_not_yet": "Not yet", "wa_done": "Done", "wa_completed": "Completed", "wa_missed": "Missed",
"wa_target_tasks": "%1$d / %2$d tasks", "wa_target_min": "%1$d / %2$d min", "wa_target_l": "%1$s / %2$s L",
"wa_mark_done": "Mark as done", "wa_mark_not_done": "Mark as not done",
"wa_a11y_toggle": "%1$s: %2$s. Double tap to change.",
"wa_a11y_card": "%1$s, %2$s",

"wa_water_add": "+%1$d ml", "wa_water_add_l": "+1 L", "wa_water_undo": "Undo last", "wa_water_set": "Set amount",
"wa_water_left": "%1$s L to go", "wa_water_goal_met": "Goal reached. Keep sipping through the day.",
"wa_steps_remaining": "%1$s to go", "wa_steps_enter": "Steps today", "wa_steps_add": "Add steps", "wa_steps_set": "Set steps",
"wa_running": "Running", "wa_running_today": "I ran today", "wa_running_km": "Distance (km)", "wa_running_note": "Walking is the daily target. Running is recorded on its own and never required.",
"wa_steps_sensor": "Count steps with this phone", "wa_steps_sensor_summary": "Uses the phone's own step counter, on the device only. Counts while the app is open, so it may lag behind a fitness band.",
"wa_steps_sensor_none": "This phone has no step counter, so enter steps by hand.",
"wa_steps_sensor_denied": "Permission was not given. Enter steps by hand, or allow Physical activity in the phone's settings.",

"wa_reading_book": "Current book", "wa_reading_change": "Change book", "wa_reading_start": "Start reading", "wa_reading_stop": "Stop and save",
"wa_reading_log": "Log reading", "wa_reading_minutes": "Minutes", "wa_reading_pages": "Pages (optional)", "wa_reading_streak": "Reading streak: %1$d days",
"wa_reading_today": "%1$d / %2$d min today", "wa_reading_saved": "Saved %1$d min of reading",
"wa_reading_pick": "Choose the book for your Winter Arc", "wa_by_author": "by %1$s",

"wa_wake_set": "Set wake-up time", "wa_wake_now": "I'm up now", "wa_wake_clear": "Clear",
"wa_wake_ok": "✓ %1$s", "wa_wake_late": "✗ %1$s", "wa_wake_rule": "Counts when you are up before 5:00 AM.",

"wa_binary_hint": "One honest tap a day. No numbers, just the commitment.",
"wa_detox_hint": "A private commitment. It shows only as Digital Detox, everywhere.",
"wa_last_14": "Last 14 days", "wa_streak_days": "%1$d-day streak", "wa_best_streak": "Best: %1$d days",

"wa_study_title": "Study Plan", "wa_tab_today": "Today", "wa_tab_week": "This Week", "wa_tab_all": "All Topics",
"wa_todays_plan": "Today's Plan", "wa_study_none_today": "Nothing planned for this day.",
"wa_study_no_plan": "No study plan yet", "wa_study_no_plan_body": "Import your plan from a CSV file (exported from your sheet) to see each day's topics here.",
"wa_study_import": "Import plan (CSV)", "wa_study_reimport": "Reload the bundled plan", "wa_study_add": "Add a task",
"wa_study_imported": "Imported %1$d tasks from %2$s", "wa_study_import_none": "No rows on or after 5 Oct were found in that file.",
"wa_study_import_failed": "That file could not be read as a study plan.",
"wa_start_focus": "Start Focus Session", "wa_week_progress": "This Week Progress", "wa_tasks_of": "%1$d / %2$d tasks",
"wa_current_resource": "Current Resource", "wa_resource_title": "Java + DSA + AI Interview Plan", "wa_resource_sub": "From your study sheet (starting 5 Oct)",
"wa_overall_progress": "Overall progress", "wa_minutes_est": "≈ %1$d min", "wa_studied_min": "%1$d min studied",
"wa_task_title": "Task", "wa_task_category": "Category", "wa_task_duration": "Minutes", "wa_task_notes": "Notes", "wa_task_delete": "Delete task",
"wa_cat_java": "Java", "wa_cat_dsa": "DSA", "wa_cat_ai": "AI / LLM", "wa_cat_design": "System Design", "wa_cat_interview": "Interview Prep",
"wa_all_categories": "All", "wa_show_done": "Show done",
"wa_study_open_day": "Open day",

"wa_focus_title": "Deep Work", "wa_focus_start": "Start Focus Session", "wa_focus_task": "What are you working on?",
"wa_focus_pause": "Pause", "wa_focus_resume": "Resume", "wa_focus_complete": "Complete", "wa_focus_cancel": "Cancel",
"wa_focus_interrupt": "Interrupted", "wa_focus_interruptions": "%1$d interruptions",
"wa_focus_saved": "Saved %1$d min of focus", "wa_focus_today": "%1$d / %2$d min today", "wa_focus_sessions": "%1$d sessions today",
"wa_focus_length": "Length", "wa_focus_note": "Kairos Era does not watch your phone. Put it face down, start the timer, and tap Interrupted if you get pulled away.",
"wa_focus_leave": "Leave this session?", "wa_focus_leave_body": "The time so far will be saved as an unfinished session.",
"wa_focus_keep": "Keep going", "wa_focus_done_title": "Session complete",

"wa_speak_title": "Daily Speaking", "wa_speak_topic": "Today's Topic", "wa_speak_start": "Start Speaking", "wa_speak_stop": "Stop",
"wa_speak_shuffle": "Another topic", "wa_speak_done": "✓ Completed", "wa_speak_rate": "How did it go?", "wa_speak_recent": "Recent Topics",
"wa_speak_hint": "Speak for 1 minute without looking at your phone or notes. It builds confidence, communication and clarity.",
"wa_speak_no_topics": "Topics could not be loaded.", "wa_speak_again": "Practise again",
"wa_speak_rating_a11y": "Rate %1$d of 5",

"wa_calendar": "Calendar", "wa_todays_progress": "Today's Progress", "wa_day_progress": "Progress on %1$s",
"wa_legend_complete": "Complete", "wa_legend_partial": "Partial", "wa_legend_missed": "Missed", "wa_legend_today": "Today", "wa_legend_paused": "Paused",
"wa_future_locked": "Future days open when they arrive.", "wa_edit_day": "Edit this day", "wa_outside_arc": "Outside your Winter Arc",

"wa_progress": "Progress", "wa_tab_month": "Month", "wa_tab_all_time": "All Time",
"wa_this_week": "This Week", "wa_this_month": "This Month", "wa_all_time": "All Time",
"wa_habits_done_of": "%1$d / %2$d habits completed",
"wa_stat_water": "%1$s / %2$s L", "wa_stat_steps": "%1$s / %2$s", "wa_stat_hours": "%1$s / %2$s hrs", "wa_stat_days": "%1$d / %2$d days",
"wa_consistency": "Habit Consistency", "wa_consistency_rate": "Days done",
"wa_h_short_focus": "Focus", "wa_h_short_wake": "Wake Early", "wa_h_short_speak": "Speak", "wa_h_short_book": "Book",
"wa_90_title": "90-Day Winter Arc", "wa_90_open": "See all 90 days",
"wa_current_streak": "Current streak", "wa_longest_streak": "Longest streak", "wa_days_completed": "Days completed",
"wa_days_remaining": "Days remaining", "wa_avg_completion": "Average daily completion",
"wa_days_value": "%1$d days", "wa_percent": "%1$d%%",
"wa_no_data": "Nothing logged yet.",

"wa_settings": "Winter Arc settings", "wa_settings_challenge": "Challenge", "wa_start_date": "Start date",
"wa_pause": "Pause the challenge", "wa_pause_summary": "The day count stops until you resume.", "wa_resume": "Resume the challenge",
"wa_reset": "Reset the challenge", "wa_reset_summary": "Start again from Day 1. Your history is kept.",
"wa_reset_confirm": "Start again from Day 1?", "wa_reset_body": "The challenge restarts on the date you pick. Nothing you logged is deleted.",
"wa_exit": "Exit Winter Arc Mode", "wa_exit_summary": "Home goes back to the everyday dashboard. All Winter Arc data is kept.",
"wa_exit_confirm": "Exit Winter Arc Mode?", "wa_exit_body": "Nothing is deleted. Turn it on again in Settings to continue where you left off.",
"wa_exit_action": "Exit", "wa_reset_action": "Reset",
"wa_settings_habits": "Habits", "wa_habit_on": "Track this habit", "wa_target": "Daily target",
"wa_settings_study": "Study plan", "wa_settings_reminders": "Reminders", "wa_settings_app": "App settings",
"wa_settings_app_summary": "Language, appearance, backup and privacy",
"wa_rem_water": "Water", "wa_rem_reading": "Book reading", "wa_rem_study": "Study", "wa_rem_cold": "Cold shower",
"wa_rem_focus": "Deep work", "wa_rem_wake": "Wake early preparation", "wa_rem_speak": "Speaking",
"wa_rem_days": "Days", "wa_rem_off": "Off", "wa_rem_summary": "%1$s · %2$s",
"wa_rem_every_day": "Every day", "wa_rem_weekdays": "Weekdays",
"wa_rem_note": "One reminder each at most, and none once that habit is done for the day.",
"wa_rem_permission": "Allow notifications so reminders can appear.",

"wa_n_water_title": "Water check", "wa_n_water_body": "%1$s L of %2$s L so far. Time for a glass.",
"wa_n_reading_title": "Reading time", "wa_n_reading_body": "%1$d of %2$d minutes read today. Open %3$s.",
"wa_n_study_title": "Study block", "wa_n_study_body": "%1$d of %2$d study tasks done today.",
"wa_n_cold_title": "Cold shower", "wa_n_cold_body": "Thirty seconds of courage. You will feel awake all morning.",
"wa_n_focus_title": "Deep work", "wa_n_focus_body": "Phone face down. Start a focus session.",
"wa_n_wake_title": "Wind down for 5 AM", "wa_n_wake_body": "Screens off soon. Tomorrow's early start begins tonight.",
"wa_n_speak_title": "Speak for 1 minute", "wa_n_speak_body": "Today's topic is waiting.",
"wa_channel": "Winter Arc", "wa_channel_description": "Gentle Winter Arc reminders you set up.",

"wa_ob_title": "WINTER ARC", "wa_ob_lines": "90 Days.\nNo excuses.\nBuild discipline.", "wa_ob_start": "Start Winter Arc",
"wa_ob_date_title": "Choose Start Date", "wa_ob_date_today": "Today", "wa_ob_date_plan": "Mon, 5 Oct (study plan start)", "wa_ob_date_pick": "Pick a date",
"wa_ob_continue": "Continue", "wa_ob_commit_title": "Your Daily Commitments", "wa_ob_commit_body": "Turn off anything you do not want to track. You can change this later.",
"wa_ob_c_water": "3L Water", "wa_ob_c_steps": "10K Steps", "wa_ob_c_sugar": "Zero Sugar", "wa_ob_c_cold": "Cold Shower", "wa_ob_c_read": "Read 30 min",
"wa_ob_c_study": "Java + DSA + AI", "wa_ob_c_focus": "Deep Work", "wa_ob_c_wake": "Wake before 5 AM", "wa_ob_c_detox": "Digital Detox", "wa_ob_c_speak": "Speak 1 Minute",
"wa_ob_ready_title": "Your Winter Arc starts on:", "wa_ob_enter": "Enter Winter Arc", "wa_ob_need_one": "Keep at least one habit.",

"wa_widget_label": "Winter Arc", "wa_widget_quote_label": "Winter Arc · Quote", "wa_widget_clock_label": "Winter Arc · Clock",
"wa_widget_water_label": "Winter Arc · Water", "wa_widget_steps_label": "Winter Arc · Steps", "wa_widget_study_label": "Winter Arc · Study",
"wa_widget_calendar_label": "Winter Arc · Calendar",
"wa_widget_today": "Today", "wa_widget_keep_going": "Keep Going", "wa_widget_todays_study": "Today's Study",
"wa_widget_clock_line": "Early risers build the life\nthey want.", "wa_widget_no_study": "No study tasks today.",
"wa_widget_off": "Turn on Winter Arc Mode in Kairos Era.",
"wa_widget_large_label": "Winter Arc · Habits", "wa_widget_speak_label": "Winter Arc · Speaking", "wa_widget_book_label": "Winter Arc · Book",
"wa_widget_week_label": "Winter Arc · Streak",
"wa_widget_desc": "Day count and today's completion.", "wa_widget_large_desc": "Every habit for today at a glance.",
"wa_widget_quote_desc": "A daily line over the sunrise.", "wa_widget_clock_desc": "The time, and whether you woke before 5.",
"wa_widget_water_desc": "Add water in one tap.", "wa_widget_steps_desc": "Steps today and how many to go.",
"wa_widget_study_desc": "Today's study tasks and a focus button.", "wa_widget_calendar_desc": "This month's Winter Arc days.",
"wa_widget_speak_desc": "Today's speaking topic.", "wa_widget_book_desc": "Your book and today's reading.",
"wa_widget_week_desc": "Your streak and this week.",
"wa_widget_book_today": "%1$d / %2$d min today", "wa_widget_steps_left": "%1$s to go",
# Custom habits (1.2)
"wa_custom_habit": "Your habit", "wa_add_habit": "Add habit", "wa_add_habit_title": "Add your own habit", "wa_edit_habit_title": "Edit habit",
"wa_habit_name": "Name", "wa_habit_name_hint": "e.g. Push-ups, Journal, Meditate", "wa_habit_track_how": "How do you track it?",
"wa_habit_type_check": "Yes / No", "wa_habit_type_amount": "Amount", "wa_habit_target": "Daily target", "wa_habit_unit": "Unit",
"wa_habit_unit_hint": "reps, pages, km", "wa_habit_check_note": "Tick it once a day when it's done.", "wa_habit_icon": "Icon", "wa_habit_color": "Color",
"wa_habit_delete": "Delete habit", "wa_habit_delete_title": "Delete “%1$s”?",
"wa_habit_delete_body": "This removes the habit and every day you logged for it. Built-in habits can only be switched off.",
"wa_custom_goal_met": "Target reached for today.", "wa_custom_left": "%1$s to go", "wa_custom_set": "Set today's amount",
"wa_custom_target": "Target: %1$s a day", "wa_sub_custom": "Your own habit",
"wa_ob_commit_custom": "You can add your own habits any time from Home or Habits.",
}

WA_KN = {
"wa_title": "ವಿಂಟರ್ ಆರ್ಕ್",
"wa_mode": "ವಿಂಟರ್ ಆರ್ಕ್ ಮೋಡ್",
"wa_mode_summary": "90 ದಿನಗಳ ಶಿಸ್ತಿನ ಸವಾಲು. ಮುಖಪುಟ ನಿಮ್ಮ ವಿಂಟರ್ ಆರ್ಕ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಆಗುತ್ತದೆ.",
"wa_day_of": "ವಿಂಟರ್ ಆರ್ಕ್ — ದಿನ %1$d / %2$d",
"wa_day_short": "ದಿನ %1$d / %2$d",
"wa_starts_in": "%1$d ದಿನಗಳಲ್ಲಿ ಆರಂಭ",
"wa_starts_tomorrow": "ನಾಳೆ ಆರಂಭ",
"wa_starts_on": "ನಿಮ್ಮ ವಿಂಟರ್ ಆರ್ಕ್ %1$s ರಂದು ಆರಂಭವಾಗುತ್ತದೆ",
"wa_paused_banner": "ವಿರಾಮದಲ್ಲಿದೆ. ದಿನಗಳ ಎಣಿಕೆ ನಿಮಗಾಗಿ ಕಾಯುತ್ತಿದೆ.",
"wa_finished_banner": "90 ದಿನಗಳು ಪೂರ್ಣ. ನೀವು ಕಟ್ಟಿದ್ದನ್ನು ಹಿಂತಿರುಗಿ ನೋಡಿ.",
"wa_statement": "ಇಂದಿನ ಶಿಸ್ತು,\nನಾಳೆಯ ಸ್ವಾತಂತ್ರ್ಯ.",
"wa_completed_of": "%1$d / %2$d ಪೂರ್ಣ",
"wa_habits_completed": "ಅಭ್ಯಾಸಗಳು ಪೂರ್ಣ",
"wa_done_short": "ಪೂರ್ಣ",
"wa_complete_rule": "%2$d ರಲ್ಲಿ %1$d ಅಭ್ಯಾಸಗಳಾದರೆ ದಿನ ಪೂರ್ಣ ಎಂದು ಎಣಿಸಲಾಗುತ್ತದೆ.",
"wa_back_to_arc": "ವಿಂಟರ್ ಆರ್ಕ್‌ಗೆ ಹಿಂತಿರುಗಿ",
"wa_open_kairos": "ದೈನಂದಿನ ಕೈರೋಸ್ ಎರಾ ತೆರೆಯಿರಿ",
"wa_open_kairos_summary": "ಕಾರ್ಯಗಳು, ಡೈರಿ ಮತ್ತು ಟ್ರ್ಯಾಕರ್‌ಗಳು. ವಿಂಟರ್ ಆರ್ಕ್ ಚಾಲೂ ಇರುತ್ತದೆ.",

"wa_nav_home": "ಮುಖಪುಟ", "wa_nav_habits": "ಅಭ್ಯಾಸಗಳು", "wa_nav_study": "ಅಧ್ಯಯನ", "wa_nav_calendar": "ಕ್ಯಾಲೆಂಡರ್", "wa_nav_stats": "ಅಂಕಿಅಂಶ",

"wa_h_water": "ನೀರು", "wa_h_steps": "ಹೆಜ್ಜೆಗಳು", "wa_h_zero_sugar": "ಸಕ್ಕರೆ ಇಲ್ಲ", "wa_h_cold_shower": "ತಣ್ಣೀರ ಸ್ನಾನ",
"wa_h_reading": "ಪುಸ್ತಕ ಓದು", "wa_h_study": "ಅಧ್ಯಯನ", "wa_h_deep_work": "ಆಳವಾದ ಕೆಲಸ", "wa_h_wake": "ಬೆಳಿಗ್ಗೆ 5ರ ಮೊದಲು",
"wa_h_detox": "ಡಿಜಿಟಲ್ ಡಿಟಾಕ್ಸ್", "wa_h_speak": "1 ನಿಮಿಷ ಮಾತು",
"wa_hl_water": "ನೀರು ಕುಡಿಯುವುದು", "wa_hl_steps": "ಹೆಜ್ಜೆ + ಓಟ", "wa_hl_zero_sugar": "ಶೂನ್ಯ ಸಕ್ಕರೆ", "wa_hl_cold_shower": "ತಣ್ಣೀರ ಸ್ನಾನ",
"wa_hl_reading": "ಪುಸ್ತಕ ಓದುವಿಕೆ", "wa_hl_study": "ಅಧ್ಯಯನ (Java + DSA + AI)", "wa_hl_deep_work": "ಆಳವಾದ ಕೆಲಸ", "wa_hl_wake": "ಬೆಳಿಗ್ಗೆ 5ರ ಮೊದಲು ಏಳುವುದು",
"wa_hl_detox": "ಡಿಜಿಟಲ್ ಡಿಟಾಕ್ಸ್", "wa_hl_speak": "1 ನಿಮಿಷ ಮಾತನಾಡಿ",
"wa_sub_water": "ದಿನಕ್ಕೆ %1$s", "wa_sub_steps": "%1$s ಹೆಜ್ಜೆಗಳು", "wa_sub_daily": "ಪ್ರತಿದಿನ", "wa_sub_study": "ನಿಮ್ಮ ಅಧ್ಯಯನ ಯೋಜನೆಯಿಂದ",
"wa_sub_deep_work": "ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮದ ಅಡ್ಡಿ ಇಲ್ಲದೆ", "wa_sub_wake": "ನಿದ್ರೆಯ ಶಿಸ್ತು", "wa_sub_speak": "ಪ್ರತಿದಿನ ಹೊಸ ವಿಷಯ",
"wa_sub_focus": "ಏಕಾಗ್ರತೆ",
"wa_not_yet": "ಇನ್ನೂ ಇಲ್ಲ", "wa_done": "ಆಯಿತು", "wa_completed": "ಪೂರ್ಣಗೊಂಡಿದೆ", "wa_missed": "ತಪ್ಪಿದೆ",
"wa_target_tasks": "%1$d / %2$d ಕಾರ್ಯಗಳು", "wa_target_min": "%1$d / %2$d ನಿಮಿಷ", "wa_target_l": "%1$s / %2$s ಲೀ",
"wa_mark_done": "ಆಯಿತು ಎಂದು ಗುರುತಿಸಿ", "wa_mark_not_done": "ಆಗಿಲ್ಲ ಎಂದು ಗುರುತಿಸಿ",
"wa_a11y_toggle": "%1$s: %2$s. ಬದಲಿಸಲು ಎರಡು ಬಾರಿ ಟ್ಯಾಪ್ ಮಾಡಿ.",
"wa_a11y_card": "%1$s, %2$s",

"wa_water_add": "+%1$d ಮಿಲೀ", "wa_water_add_l": "+1 ಲೀ", "wa_water_undo": "ಕೊನೆಯದನ್ನು ರದ್ದುಮಾಡಿ", "wa_water_set": "ಪ್ರಮಾಣ ಹೊಂದಿಸಿ",
"wa_water_left": "ಇನ್ನೂ %1$s ಲೀ", "wa_water_goal_met": "ಗುರಿ ತಲುಪಿದೆ. ದಿನವಿಡೀ ಸ್ವಲ್ಪ ಸ್ವಲ್ಪ ಕುಡಿಯುತ್ತಿರಿ.",
"wa_steps_remaining": "ಇನ್ನೂ %1$s", "wa_steps_enter": "ಇಂದಿನ ಹೆಜ್ಜೆಗಳು", "wa_steps_add": "ಹೆಜ್ಜೆ ಸೇರಿಸಿ", "wa_steps_set": "ಹೆಜ್ಜೆ ಹೊಂದಿಸಿ",
"wa_running": "ಓಟ", "wa_running_today": "ಇಂದು ಓಡಿದೆ", "wa_running_km": "ದೂರ (ಕಿಮೀ)", "wa_running_note": "ನಡಿಗೆಯೇ ದೈನಂದಿನ ಗುರಿ. ಓಟವನ್ನು ಪ್ರತ್ಯೇಕವಾಗಿ ದಾಖಲಿಸಲಾಗುತ್ತದೆ, ಕಡ್ಡಾಯವಲ್ಲ.",
"wa_steps_sensor": "ಈ ಫೋನ್‌ನಿಂದ ಹೆಜ್ಜೆ ಎಣಿಸಿ", "wa_steps_sensor_summary": "ಫೋನ್‌ನ ಸ್ವಂತ ಹೆಜ್ಜೆ ಎಣಿಕೆಯನ್ನು ಸಾಧನದಲ್ಲೇ ಬಳಸುತ್ತದೆ. ಆ್ಯಪ್ ತೆರೆದಿರುವಾಗ ಎಣಿಸುವುದರಿಂದ ಫಿಟ್‌ನೆಸ್ ಬ್ಯಾಂಡ್‌ಗಿಂತ ಸ್ವಲ್ಪ ಹಿಂದಿರಬಹುದು.",
"wa_steps_sensor_none": "ಈ ಫೋನ್‌ನಲ್ಲಿ ಹೆಜ್ಜೆ ಎಣಿಕೆ ಇಲ್ಲ, ಆದ್ದರಿಂದ ಕೈಯಾರೆ ನಮೂದಿಸಿ.",
"wa_steps_sensor_denied": "ಅನುಮತಿ ಸಿಗಲಿಲ್ಲ. ಕೈಯಾರೆ ನಮೂದಿಸಿ, ಅಥವಾ ಫೋನ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ದೈಹಿಕ ಚಟುವಟಿಕೆಗೆ ಅನುಮತಿ ನೀಡಿ.",

"wa_reading_book": "ಈಗಿನ ಪುಸ್ತಕ", "wa_reading_change": "ಪುಸ್ತಕ ಬದಲಿಸಿ", "wa_reading_start": "ಓದು ಆರಂಭಿಸಿ", "wa_reading_stop": "ನಿಲ್ಲಿಸಿ ಉಳಿಸಿ",
"wa_reading_log": "ಓದು ದಾಖಲಿಸಿ", "wa_reading_minutes": "ನಿಮಿಷಗಳು", "wa_reading_pages": "ಪುಟಗಳು (ಐಚ್ಛಿಕ)", "wa_reading_streak": "ಓದಿನ ಸರಣಿ: %1$d ದಿನಗಳು",
"wa_reading_today": "ಇಂದು %1$d / %2$d ನಿಮಿಷ", "wa_reading_saved": "%1$d ನಿಮಿಷದ ಓದು ಉಳಿಸಲಾಗಿದೆ",
"wa_reading_pick": "ನಿಮ್ಮ ವಿಂಟರ್ ಆರ್ಕ್‌ಗೆ ಪುಸ್ತಕ ಆಯ್ಕೆಮಾಡಿ", "wa_by_author": "%1$s ಅವರಿಂದ",

"wa_wake_set": "ಎದ್ದ ಸಮಯ ಹೊಂದಿಸಿ", "wa_wake_now": "ಈಗ ಎದ್ದೆ", "wa_wake_clear": "ಅಳಿಸಿ",
"wa_wake_ok": "✓ %1$s", "wa_wake_late": "✗ %1$s", "wa_wake_rule": "ಬೆಳಿಗ್ಗೆ 5:00ರ ಮೊದಲು ಎದ್ದರೆ ಮಾತ್ರ ಎಣಿಕೆ.",

"wa_binary_hint": "ದಿನಕ್ಕೆ ಒಂದು ಪ್ರಾಮಾಣಿಕ ಟ್ಯಾಪ್. ಸಂಖ್ಯೆಗಳಿಲ್ಲ, ಬದ್ಧತೆ ಮಾತ್ರ.",
"wa_detox_hint": "ಖಾಸಗಿ ಬದ್ಧತೆ. ಎಲ್ಲೆಡೆ ಡಿಜಿಟಲ್ ಡಿಟಾಕ್ಸ್ ಎಂದು ಮಾತ್ರ ಕಾಣುತ್ತದೆ.",
"wa_last_14": "ಕಳೆದ 14 ದಿನಗಳು", "wa_streak_days": "%1$d ದಿನಗಳ ಸರಣಿ", "wa_best_streak": "ಅತ್ಯುತ್ತಮ: %1$d ದಿನಗಳು",

"wa_study_title": "ಅಧ್ಯಯನ ಯೋಜನೆ", "wa_tab_today": "ಇಂದು", "wa_tab_week": "ಈ ವಾರ", "wa_tab_all": "ಎಲ್ಲ ವಿಷಯಗಳು",
"wa_todays_plan": "ಇಂದಿನ ಯೋಜನೆ", "wa_study_none_today": "ಈ ದಿನಕ್ಕೆ ಏನೂ ಯೋಜಿಸಿಲ್ಲ.",
"wa_study_no_plan": "ಇನ್ನೂ ಅಧ್ಯಯನ ಯೋಜನೆ ಇಲ್ಲ", "wa_study_no_plan_body": "ಪ್ರತಿದಿನದ ವಿಷಯಗಳನ್ನು ಇಲ್ಲಿ ನೋಡಲು ನಿಮ್ಮ ಶೀಟ್‌ನಿಂದ ರಫ್ತು ಮಾಡಿದ CSV ಫೈಲ್‌ನಿಂದ ಯೋಜನೆಯನ್ನು ಆಮದು ಮಾಡಿ.",
"wa_study_import": "ಯೋಜನೆ ಆಮದು (CSV)", "wa_study_reimport": "ಒಳಗೊಂಡ ಯೋಜನೆಯನ್ನು ಮರುಲೋಡ್ ಮಾಡಿ", "wa_study_add": "ಕಾರ್ಯ ಸೇರಿಸಿ",
"wa_study_imported": "%2$s ರಿಂದ %1$d ಕಾರ್ಯಗಳನ್ನು ಆಮದು ಮಾಡಲಾಗಿದೆ", "wa_study_import_none": "ಆ ಫೈಲ್‌ನಲ್ಲಿ ಅಕ್ಟೋಬರ್ 5 ಅಥವಾ ನಂತರದ ಸಾಲುಗಳು ಸಿಗಲಿಲ್ಲ.",
"wa_study_import_failed": "ಆ ಫೈಲ್ ಅನ್ನು ಅಧ್ಯಯನ ಯೋಜನೆಯಾಗಿ ಓದಲಾಗಲಿಲ್ಲ.",
"wa_start_focus": "ಏಕಾಗ್ರತೆ ಅವಧಿ ಆರಂಭಿಸಿ", "wa_week_progress": "ಈ ವಾರದ ಪ್ರಗತಿ", "wa_tasks_of": "%1$d / %2$d ಕಾರ್ಯಗಳು",
"wa_current_resource": "ಈಗಿನ ಸಂಪನ್ಮೂಲ", "wa_resource_title": "Java + DSA + AI ಸಂದರ್ಶನ ಯೋಜನೆ", "wa_resource_sub": "ನಿಮ್ಮ ಅಧ್ಯಯನ ಶೀಟ್‌ನಿಂದ (ಅಕ್ಟೋಬರ್ 5 ರಿಂದ)",
"wa_overall_progress": "ಒಟ್ಟು ಪ್ರಗತಿ", "wa_minutes_est": "≈ %1$d ನಿಮಿಷ", "wa_studied_min": "%1$d ನಿಮಿಷ ಅಧ್ಯಯನ",
"wa_task_title": "ಕಾರ್ಯ", "wa_task_category": "ವರ್ಗ", "wa_task_duration": "ನಿಮಿಷಗಳು", "wa_task_notes": "ಟಿಪ್ಪಣಿಗಳು", "wa_task_delete": "ಕಾರ್ಯ ಅಳಿಸಿ",
"wa_cat_java": "Java", "wa_cat_dsa": "DSA", "wa_cat_ai": "AI / LLM", "wa_cat_design": "ಸಿಸ್ಟಮ್ ವಿನ್ಯಾಸ", "wa_cat_interview": "ಸಂದರ್ಶನ ತಯಾರಿ",
"wa_all_categories": "ಎಲ್ಲವೂ", "wa_show_done": "ಮುಗಿದವನ್ನು ತೋರಿಸಿ",
"wa_study_open_day": "ದಿನ ತೆರೆಯಿರಿ",

"wa_focus_title": "ಆಳವಾದ ಕೆಲಸ", "wa_focus_start": "ಏಕಾಗ್ರತೆ ಅವಧಿ ಆರಂಭಿಸಿ", "wa_focus_task": "ನೀವು ಯಾವುದರ ಮೇಲೆ ಕೆಲಸ ಮಾಡುತ್ತಿದ್ದೀರಿ?",
"wa_focus_pause": "ವಿರಾಮ", "wa_focus_resume": "ಮುಂದುವರಿಸಿ", "wa_focus_complete": "ಪೂರ್ಣಗೊಳಿಸಿ", "wa_focus_cancel": "ರದ್ದುಮಾಡಿ",
"wa_focus_interrupt": "ಅಡ್ಡಿಯಾಯಿತು", "wa_focus_interruptions": "%1$d ಅಡ್ಡಿಗಳು",
"wa_focus_saved": "%1$d ನಿಮಿಷದ ಏಕಾಗ್ರತೆ ಉಳಿಸಲಾಗಿದೆ", "wa_focus_today": "ಇಂದು %1$d / %2$d ನಿಮಿಷ", "wa_focus_sessions": "ಇಂದು %1$d ಅವಧಿಗಳು",
"wa_focus_length": "ಅವಧಿ", "wa_focus_note": "ಕೈರೋಸ್ ಎರಾ ನಿಮ್ಮ ಫೋನ್ ಅನ್ನು ಗಮನಿಸುವುದಿಲ್ಲ. ಫೋನ್ ಕವುಚಿ ಇಡಿ, ಟೈಮರ್ ಆರಂಭಿಸಿ, ಗಮನ ತಪ್ಪಿದರೆ ಅಡ್ಡಿಯಾಯಿತು ಒತ್ತಿ.",
"wa_focus_leave": "ಈ ಅವಧಿಯಿಂದ ಹೊರಡುವಿರಾ?", "wa_focus_leave_body": "ಇದುವರೆಗಿನ ಸಮಯವನ್ನು ಅಪೂರ್ಣ ಅವಧಿಯಾಗಿ ಉಳಿಸಲಾಗುತ್ತದೆ.",
"wa_focus_keep": "ಮುಂದುವರಿಸಿ", "wa_focus_done_title": "ಅವಧಿ ಪೂರ್ಣ",

"wa_speak_title": "ದೈನಂದಿನ ಮಾತು", "wa_speak_topic": "ಇಂದಿನ ವಿಷಯ", "wa_speak_start": "ಮಾತು ಆರಂಭಿಸಿ", "wa_speak_stop": "ನಿಲ್ಲಿಸಿ",
"wa_speak_shuffle": "ಬೇರೆ ವಿಷಯ", "wa_speak_done": "✓ ಪೂರ್ಣಗೊಂಡಿದೆ", "wa_speak_rate": "ಹೇಗಿತ್ತು?", "wa_speak_recent": "ಇತ್ತೀಚಿನ ವಿಷಯಗಳು",
"wa_speak_hint": "ಫೋನ್ ಅಥವಾ ಟಿಪ್ಪಣಿ ನೋಡದೆ 1 ನಿಮಿಷ ಮಾತನಾಡಿ. ಇದು ಆತ್ಮವಿಶ್ವಾಸ, ಸಂವಹನ ಮತ್ತು ಸ್ಪಷ್ಟತೆಯನ್ನು ಬೆಳೆಸುತ್ತದೆ.",
"wa_speak_no_topics": "ವಿಷಯಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗಲಿಲ್ಲ.", "wa_speak_again": "ಮತ್ತೆ ಅಭ್ಯಾಸ ಮಾಡಿ",
"wa_speak_rating_a11y": "5ರಲ್ಲಿ %1$d ರೇಟಿಂಗ್",

"wa_calendar": "ಕ್ಯಾಲೆಂಡರ್", "wa_todays_progress": "ಇಂದಿನ ಪ್ರಗತಿ", "wa_day_progress": "%1$s ರ ಪ್ರಗತಿ",
"wa_legend_complete": "ಪೂರ್ಣ", "wa_legend_partial": "ಭಾಗಶಃ", "wa_legend_missed": "ತಪ್ಪಿದೆ", "wa_legend_today": "ಇಂದು", "wa_legend_paused": "ವಿರಾಮ",
"wa_future_locked": "ಮುಂದಿನ ದಿನಗಳು ಬಂದಾಗ ತೆರೆಯುತ್ತವೆ.", "wa_edit_day": "ಈ ದಿನವನ್ನು ತಿದ್ದಿ", "wa_outside_arc": "ನಿಮ್ಮ ವಿಂಟರ್ ಆರ್ಕ್‌ನ ಹೊರಗೆ",

"wa_progress": "ಪ್ರಗತಿ", "wa_tab_month": "ತಿಂಗಳು", "wa_tab_all_time": "ಒಟ್ಟು",
"wa_this_week": "ಈ ವಾರ", "wa_this_month": "ಈ ತಿಂಗಳು", "wa_all_time": "ಒಟ್ಟು",
"wa_habits_done_of": "%1$d / %2$d ಅಭ್ಯಾಸಗಳು ಪೂರ್ಣ",
"wa_stat_water": "%1$s / %2$s ಲೀ", "wa_stat_steps": "%1$s / %2$s", "wa_stat_hours": "%1$s / %2$s ಗಂ", "wa_stat_days": "%1$d / %2$d ದಿನ",
"wa_consistency": "ಅಭ್ಯಾಸದ ನಿರಂತರತೆ", "wa_consistency_rate": "ಪೂರ್ಣ ದಿನಗಳು",
"wa_h_short_focus": "ಏಕಾಗ್ರತೆ", "wa_h_short_wake": "ಬೇಗ ಏಳು", "wa_h_short_speak": "ಮಾತು", "wa_h_short_book": "ಪುಸ್ತಕ",
"wa_90_title": "90 ದಿನಗಳ ವಿಂಟರ್ ಆರ್ಕ್", "wa_90_open": "ಎಲ್ಲ 90 ದಿನಗಳನ್ನು ನೋಡಿ",
"wa_current_streak": "ಈಗಿನ ಸರಣಿ", "wa_longest_streak": "ದೀರ್ಘ ಸರಣಿ", "wa_days_completed": "ಪೂರ್ಣ ದಿನಗಳು",
"wa_days_remaining": "ಉಳಿದ ದಿನಗಳು", "wa_avg_completion": "ಸರಾಸರಿ ದೈನಂದಿನ ಪೂರ್ಣತೆ",
"wa_days_value": "%1$d ದಿನಗಳು", "wa_percent": "%1$d%%",
"wa_no_data": "ಇನ್ನೂ ಏನೂ ದಾಖಲಾಗಿಲ್ಲ.",

"wa_settings": "ವಿಂಟರ್ ಆರ್ಕ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು", "wa_settings_challenge": "ಸವಾಲು", "wa_start_date": "ಆರಂಭದ ದಿನಾಂಕ",
"wa_pause": "ಸವಾಲನ್ನು ವಿರಾಮಗೊಳಿಸಿ", "wa_pause_summary": "ಮುಂದುವರಿಸುವವರೆಗೆ ದಿನಗಳ ಎಣಿಕೆ ನಿಲ್ಲುತ್ತದೆ.", "wa_resume": "ಸವಾಲನ್ನು ಮುಂದುವರಿಸಿ",
"wa_reset": "ಸವಾಲನ್ನು ಮರುಆರಂಭಿಸಿ", "wa_reset_summary": "ದಿನ 1 ರಿಂದ ಮತ್ತೆ ಆರಂಭಿಸಿ. ನಿಮ್ಮ ಇತಿಹಾಸ ಉಳಿಯುತ್ತದೆ.",
"wa_reset_confirm": "ದಿನ 1 ರಿಂದ ಮತ್ತೆ ಆರಂಭಿಸಬೇಕೇ?", "wa_reset_body": "ನೀವು ಆರಿಸುವ ದಿನಾಂಕದಿಂದ ಸವಾಲು ಮರುಆರಂಭವಾಗುತ್ತದೆ. ದಾಖಲಿಸಿದ ಯಾವುದೂ ಅಳಿಸುವುದಿಲ್ಲ.",
"wa_exit": "ವಿಂಟರ್ ಆರ್ಕ್ ಮೋಡ್‌ನಿಂದ ಹೊರಬನ್ನಿ", "wa_exit_summary": "ಮುಖಪುಟ ದೈನಂದಿನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಮರಳುತ್ತದೆ. ಎಲ್ಲ ವಿಂಟರ್ ಆರ್ಕ್ ಮಾಹಿತಿ ಉಳಿಯುತ್ತದೆ.",
"wa_exit_confirm": "ವಿಂಟರ್ ಆರ್ಕ್ ಮೋಡ್‌ನಿಂದ ಹೊರಬರಬೇಕೇ?", "wa_exit_body": "ಯಾವುದೂ ಅಳಿಸುವುದಿಲ್ಲ. ಬಿಟ್ಟಲ್ಲಿಂದ ಮುಂದುವರಿಸಲು ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಮತ್ತೆ ಚಾಲೂ ಮಾಡಿ.",
"wa_exit_action": "ಹೊರಬನ್ನಿ", "wa_reset_action": "ಮರುಆರಂಭಿಸಿ",
"wa_settings_habits": "ಅಭ್ಯಾಸಗಳು", "wa_habit_on": "ಈ ಅಭ್ಯಾಸವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ", "wa_target": "ದೈನಂದಿನ ಗುರಿ",
"wa_settings_study": "ಅಧ್ಯಯನ ಯೋಜನೆ", "wa_settings_reminders": "ಜ್ಞಾಪನೆಗಳು", "wa_settings_app": "ಆ್ಯಪ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
"wa_settings_app_summary": "ಭಾಷೆ, ನೋಟ, ಬ್ಯಾಕಪ್ ಮತ್ತು ಗೌಪ್ಯತೆ",
"wa_rem_water": "ನೀರು", "wa_rem_reading": "ಪುಸ್ತಕ ಓದು", "wa_rem_study": "ಅಧ್ಯಯನ", "wa_rem_cold": "ತಣ್ಣೀರ ಸ್ನಾನ",
"wa_rem_focus": "ಆಳವಾದ ಕೆಲಸ", "wa_rem_wake": "ಬೇಗ ಏಳಲು ತಯಾರಿ", "wa_rem_speak": "ಮಾತು",
"wa_rem_days": "ದಿನಗಳು", "wa_rem_off": "ಆಫ್", "wa_rem_summary": "%1$s · %2$s",
"wa_rem_every_day": "ಪ್ರತಿದಿನ", "wa_rem_weekdays": "ವಾರದ ದಿನಗಳು",
"wa_rem_note": "ಪ್ರತಿಯೊಂದಕ್ಕೂ ಹೆಚ್ಚೆಂದರೆ ಒಂದು ಜ್ಞಾಪನೆ, ಆ ದಿನ ಅಭ್ಯಾಸ ಮುಗಿದ ಮೇಲೆ ಯಾವುದೂ ಇಲ್ಲ.",
"wa_rem_permission": "ಜ್ಞಾಪನೆಗಳು ಕಾಣಿಸಲು ಅಧಿಸೂಚನೆಗಳಿಗೆ ಅನುಮತಿ ನೀಡಿ.",

"wa_n_water_title": "ನೀರಿನ ನೆನಪು", "wa_n_water_body": "ಇದುವರೆಗೆ %2$s ಲೀ ನಲ್ಲಿ %1$s ಲೀ. ಒಂದು ಲೋಟ ಕುಡಿಯುವ ಸಮಯ.",
"wa_n_reading_title": "ಓದುವ ಸಮಯ", "wa_n_reading_body": "ಇಂದು %2$d ರಲ್ಲಿ %1$d ನಿಮಿಷ ಓದಿದ್ದೀರಿ. %3$s ತೆರೆಯಿರಿ.",
"wa_n_study_title": "ಅಧ್ಯಯನದ ಸಮಯ", "wa_n_study_body": "ಇಂದು %2$d ರಲ್ಲಿ %1$d ಅಧ್ಯಯನ ಕಾರ್ಯಗಳು ಮುಗಿದಿವೆ.",
"wa_n_cold_title": "ತಣ್ಣೀರ ಸ್ನಾನ", "wa_n_cold_body": "ಮೂವತ್ತು ಸೆಕೆಂಡಿನ ಧೈರ್ಯ. ಬೆಳಿಗ್ಗೆಯೆಲ್ಲ ಚುರುಕಾಗಿರುತ್ತೀರಿ.",
"wa_n_focus_title": "ಆಳವಾದ ಕೆಲಸ", "wa_n_focus_body": "ಫೋನ್ ಕವುಚಿ ಇಡಿ. ಏಕಾಗ್ರತೆ ಅವಧಿ ಆರಂಭಿಸಿ.",
"wa_n_wake_title": "ಬೆಳಿಗ್ಗೆ 5ಕ್ಕೆ ತಯಾರಿ", "wa_n_wake_body": "ಶೀಘ್ರದಲ್ಲೇ ಪರದೆಗಳನ್ನು ಆಫ್ ಮಾಡಿ. ನಾಳೆಯ ಬೇಗನೆ ಏಳುವಿಕೆ ಇಂದು ರಾತ್ರಿ ಆರಂಭ.",
"wa_n_speak_title": "1 ನಿಮಿಷ ಮಾತನಾಡಿ", "wa_n_speak_body": "ಇಂದಿನ ವಿಷಯ ಕಾಯುತ್ತಿದೆ.",
"wa_channel": "ವಿಂಟರ್ ಆರ್ಕ್", "wa_channel_description": "ನೀವು ಹೊಂದಿಸಿದ ಸೌಮ್ಯ ವಿಂಟರ್ ಆರ್ಕ್ ಜ್ಞಾಪನೆಗಳು.",

"wa_ob_title": "ವಿಂಟರ್ ಆರ್ಕ್", "wa_ob_lines": "90 ದಿನಗಳು.\nನೆಪಗಳಿಲ್ಲ.\nಶಿಸ್ತನ್ನು ಕಟ್ಟಿ.", "wa_ob_start": "ವಿಂಟರ್ ಆರ್ಕ್ ಆರಂಭಿಸಿ",
"wa_ob_date_title": "ಆರಂಭದ ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ", "wa_ob_date_today": "ಇಂದು", "wa_ob_date_plan": "ಸೋಮ, ಅಕ್ಟೋಬರ್ 5 (ಅಧ್ಯಯನ ಯೋಜನೆ ಆರಂಭ)", "wa_ob_date_pick": "ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ",
"wa_ob_continue": "ಮುಂದುವರಿಸಿ", "wa_ob_commit_title": "ನಿಮ್ಮ ದೈನಂದಿನ ಬದ್ಧತೆಗಳು", "wa_ob_commit_body": "ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಬೇಡವಾದುದನ್ನು ಆಫ್ ಮಾಡಿ. ನಂತರ ಬದಲಿಸಬಹುದು.",
"wa_ob_c_water": "3 ಲೀ ನೀರು", "wa_ob_c_steps": "10K ಹೆಜ್ಜೆಗಳು", "wa_ob_c_sugar": "ಶೂನ್ಯ ಸಕ್ಕರೆ", "wa_ob_c_cold": "ತಣ್ಣೀರ ಸ್ನಾನ", "wa_ob_c_read": "30 ನಿಮಿಷ ಓದು",
"wa_ob_c_study": "Java + DSA + AI", "wa_ob_c_focus": "ಆಳವಾದ ಕೆಲಸ", "wa_ob_c_wake": "ಬೆಳಿಗ್ಗೆ 5ರ ಮೊದಲು ಏಳು", "wa_ob_c_detox": "ಡಿಜಿಟಲ್ ಡಿಟಾಕ್ಸ್", "wa_ob_c_speak": "1 ನಿಮಿಷ ಮಾತು",
"wa_ob_ready_title": "ನಿಮ್ಮ ವಿಂಟರ್ ಆರ್ಕ್ ಆರಂಭ:", "wa_ob_enter": "ವಿಂಟರ್ ಆರ್ಕ್ ಪ್ರವೇಶಿಸಿ", "wa_ob_need_one": "ಕನಿಷ್ಠ ಒಂದು ಅಭ್ಯಾಸ ಇರಲಿ.",

"wa_widget_label": "ವಿಂಟರ್ ಆರ್ಕ್", "wa_widget_quote_label": "ವಿಂಟರ್ ಆರ್ಕ್ · ಉಕ್ತಿ", "wa_widget_clock_label": "ವಿಂಟರ್ ಆರ್ಕ್ · ಗಡಿಯಾರ",
"wa_widget_water_label": "ವಿಂಟರ್ ಆರ್ಕ್ · ನೀರು", "wa_widget_steps_label": "ವಿಂಟರ್ ಆರ್ಕ್ · ಹೆಜ್ಜೆ", "wa_widget_study_label": "ವಿಂಟರ್ ಆರ್ಕ್ · ಅಧ್ಯಯನ",
"wa_widget_calendar_label": "ವಿಂಟರ್ ಆರ್ಕ್ · ಕ್ಯಾಲೆಂಡರ್",
"wa_widget_today": "ಇಂದು", "wa_widget_keep_going": "ಮುಂದುವರಿಯಿರಿ", "wa_widget_todays_study": "ಇಂದಿನ ಅಧ್ಯಯನ",
"wa_widget_clock_line": "ಬೇಗ ಏಳುವವರು ತಮಗೆ\nಬೇಕಾದ ಬದುಕು ಕಟ್ಟುತ್ತಾರೆ.", "wa_widget_no_study": "ಇಂದು ಅಧ್ಯಯನ ಕಾರ್ಯಗಳಿಲ್ಲ.",
"wa_widget_off": "ಕೈರೋಸ್ ಎರಾದಲ್ಲಿ ವಿಂಟರ್ ಆರ್ಕ್ ಮೋಡ್ ಆನ್ ಮಾಡಿ.",
"wa_widget_large_label": "ವಿಂಟರ್ ಆರ್ಕ್ · ಅಭ್ಯಾಸಗಳು", "wa_widget_speak_label": "ವಿಂಟರ್ ಆರ್ಕ್ · ಮಾತು", "wa_widget_book_label": "ವಿಂಟರ್ ಆರ್ಕ್ · ಪುಸ್ತಕ",
"wa_widget_week_label": "ವಿಂಟರ್ ಆರ್ಕ್ · ಸರಣಿ",
"wa_widget_desc": "ದಿನದ ಎಣಿಕೆ ಮತ್ತು ಇಂದಿನ ಪೂರ್ಣತೆ.", "wa_widget_large_desc": "ಇಂದಿನ ಎಲ್ಲ ಅಭ್ಯಾಸಗಳು ಒಂದೇ ನೋಟದಲ್ಲಿ.",
"wa_widget_quote_desc": "ಸೂರ್ಯೋದಯದ ಮೇಲೆ ದಿನದ ಸಾಲು.", "wa_widget_clock_desc": "ಸಮಯ, ಮತ್ತು 5ರ ಮೊದಲು ಎದ್ದಿರಾ ಎಂಬುದು.",
"wa_widget_water_desc": "ಒಂದೇ ಟ್ಯಾಪ್‌ನಲ್ಲಿ ನೀರು ಸೇರಿಸಿ.", "wa_widget_steps_desc": "ಇಂದಿನ ಹೆಜ್ಜೆಗಳು ಮತ್ತು ಉಳಿದವು.",
"wa_widget_study_desc": "ಇಂದಿನ ಅಧ್ಯಯನ ಕಾರ್ಯಗಳು ಮತ್ತು ಫೋಕಸ್ ಬಟನ್.", "wa_widget_calendar_desc": "ಈ ತಿಂಗಳ ವಿಂಟರ್ ಆರ್ಕ್ ದಿನಗಳು.",
"wa_widget_speak_desc": "ಇಂದಿನ ಮಾತಿನ ವಿಷಯ.", "wa_widget_book_desc": "ನಿಮ್ಮ ಪುಸ್ತಕ ಮತ್ತು ಇಂದಿನ ಓದು.",
"wa_widget_week_desc": "ನಿಮ್ಮ ಸರಣಿ ಮತ್ತು ಈ ವಾರ.",
"wa_widget_book_today": "ಇಂದು %1$d / %2$d ನಿಮಿಷ", "wa_widget_steps_left": "ಇನ್ನೂ %1$s",
# Custom habits (1.2)
"wa_custom_habit": "ನಿಮ್ಮ ಅಭ್ಯಾಸ", "wa_add_habit": "ಅಭ್ಯಾಸ ಸೇರಿಸಿ", "wa_add_habit_title": "ನಿಮ್ಮದೇ ಅಭ್ಯಾಸ ಸೇರಿಸಿ", "wa_edit_habit_title": "ಅಭ್ಯಾಸ ತಿದ್ದಿ",
"wa_habit_name": "ಹೆಸರು", "wa_habit_name_hint": "ಉದಾ: ಪುಷ್-ಅಪ್, ದಿನಚರಿ, ಧ್ಯಾನ", "wa_habit_track_how": "ಇದನ್ನು ಹೇಗೆ ದಾಖಲಿಸುತ್ತೀರಿ?",
"wa_habit_type_check": "ಹೌದು / ಇಲ್ಲ", "wa_habit_type_amount": "ಪ್ರಮಾಣ", "wa_habit_target": "ದೈನಂದಿನ ಗುರಿ", "wa_habit_unit": "ಘಟಕ",
"wa_habit_unit_hint": "ಬಾರಿ, ಪುಟ, ಕಿ.ಮೀ", "wa_habit_check_note": "ಮುಗಿದಾಗ ದಿನಕ್ಕೆ ಒಮ್ಮೆ ಗುರುತು ಹಾಕಿ.", "wa_habit_icon": "ಚಿಹ್ನೆ", "wa_habit_color": "ಬಣ್ಣ",
"wa_habit_delete": "ಅಭ್ಯಾಸ ಅಳಿಸಿ", "wa_habit_delete_title": "“%1$s” ಅಳಿಸಬೇಕೇ?",
"wa_habit_delete_body": "ಇದು ಈ ಅಭ್ಯಾಸವನ್ನು ಮತ್ತು ಅದಕ್ಕೆ ದಾಖಲಿಸಿದ ಎಲ್ಲ ದಿನಗಳನ್ನು ಅಳಿಸುತ್ತದೆ. ಅಂತರ್ನಿರ್ಮಿತ ಅಭ್ಯಾಸಗಳನ್ನು ಆಫ್ ಮಾತ್ರ ಮಾಡಬಹುದು.",
"wa_custom_goal_met": "ಇಂದಿನ ಗುರಿ ತಲುಪಿದ್ದೀರಿ.", "wa_custom_left": "ಇನ್ನೂ %1$s ಬಾಕಿ", "wa_custom_set": "ಇಂದಿನ ಪ್ರಮಾಣ ಹೊಂದಿಸಿ",
"wa_custom_target": "ಗುರಿ: ದಿನಕ್ಕೆ %1$s", "wa_sub_custom": "ನಿಮ್ಮದೇ ಅಭ್ಯಾಸ",
"wa_ob_commit_custom": "ಮುಖಪುಟ ಅಥವಾ ಅಭ್ಯಾಸಗಳಿಂದ ಯಾವಾಗ ಬೇಕಾದರೂ ನಿಮ್ಮದೇ ಅಭ್ಯಾಸಗಳನ್ನು ಸೇರಿಸಬಹುದು.",
}
